run:
  timeout: 3m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - gofmt
    - goimports
    - misspell
    - unconvert
    - revive
    - gosec

linters-settings:
  revive:
    rules:
      - name: exported
      - name: var-naming
      - name: package-comments
  gosec:
    excludes:
      - G101

issues:
  exclude-rules:
    - path: _test\.go
      linters: [gosec, revive]
