global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: offlinepay-transferworker
    static_configs:
      - targets: ['transferworker:9102']
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
