// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one

INSERT INTO accounts (id, user_id, kind, balance_kobo)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, kind, balance_kobo, created_at, updated_at
`

type CreateAccountParams struct {
	ID          string      `json:"id"`
	UserID      string      `json:"user_id"`
	Kind        AccountKind `json:"kind"`
	BalanceKobo int64       `json:"balance_kobo"`
}

// Account CRUD + balance mutators. The ledger layer owns all writes to
// balance_kobo via the Increment/Decrement helpers so the account row
// and its ledger entries always move together inside one tx.
func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.BalanceKobo,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.BalanceKobo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementAccountBalance = `-- name: DecrementAccountBalance :one
UPDATE accounts
SET balance_kobo = balance_kobo - $2, updated_at = now()
WHERE id = $1 AND balance_kobo >= $2
RETURNING id, user_id, kind, balance_kobo, created_at, updated_at
`

type DecrementAccountBalanceParams struct {
	ID          string `json:"id"`
	BalanceKobo int64  `json:"balance_kobo"`
}

func (q *Queries) DecrementAccountBalance(ctx context.Context, arg DecrementAccountBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, decrementAccountBalance, arg.ID, arg.BalanceKobo)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.BalanceKobo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureSystemSuspenseAccount = `-- name: EnsureSystemSuspenseAccount :exec
WITH ensure_user AS (
    INSERT INTO users (
        id, phone, account_number, bvn, kyc_tier,
        device_attestation_id, realm_key_version, created_at,
        first_name, last_name, email, password_hash, email_verified
    )
    VALUES (
        'system-settlement', 'system-settlement', '0000000000', NULL, 'SYSTEM',
        NULL, 0, now(),
        'System', 'Settlement', 'system-settlement@internal.invalid', '', false
    )
    ON CONFLICT (id) DO NOTHING
    RETURNING id
)
INSERT INTO accounts (id, user_id, kind, balance_kobo, created_at, updated_at)
VALUES ('system-suspense', 'system-settlement', 'suspense', 0, now(), now())
ON CONFLICT (id) DO NOTHING
`

// EnsureSystemSuspenseAccount is an idempotent boot-time safety net for
// the singleton suspense account + its owning system user. The initial
// schema seeds both rows, so on a freshly migrated DB this is a no-op;
// the upsert exists to keep Phase 4a ledger posts (which DEBIT
// system-suspense) working against DBs restored from partial backups or
// ad-hoc dev wipes.
//
// The system user is invisible to any human-facing surface — it never
// logs in, and the SYSTEM kyc_tier + non-numeric account_number keep it
// out of the signup/transfer paths.
func (q *Queries) EnsureSystemSuspenseAccount(ctx context.Context) error {
	_, err := q.db.Exec(ctx, ensureSystemSuspenseAccount)
	return err
}

const forceDecrementAccountBalance = `-- name: ForceDecrementAccountBalance :one
UPDATE accounts
SET balance_kobo = balance_kobo - $2, updated_at = now()
WHERE id = $1
RETURNING id, user_id, kind, balance_kobo, created_at, updated_at
`

type ForceDecrementAccountBalanceParams struct {
	ID          string `json:"id"`
	BalanceKobo int64  `json:"balance_kobo"`
}

// ForceDecrementAccountBalance is the unguarded decrement path. Only
// valid for account kinds exempt from the non-negative check — in
// practice, the suspense account while it briefly holds the merchant
// leg of a two-phase settlement.
func (q *Queries) ForceDecrementAccountBalance(ctx context.Context, arg ForceDecrementAccountBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, forceDecrementAccountBalance, arg.ID, arg.BalanceKobo)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.BalanceKobo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, user_id, kind, balance_kobo, created_at, updated_at FROM accounts WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.BalanceKobo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByUserAndKind = `-- name: GetAccountByUserAndKind :one
SELECT id, user_id, kind, balance_kobo, created_at, updated_at FROM accounts WHERE user_id = $1 AND kind = $2
`

type GetAccountByUserAndKindParams struct {
	UserID string      `json:"user_id"`
	Kind   AccountKind `json:"kind"`
}

func (q *Queries) GetAccountByUserAndKind(ctx context.Context, arg GetAccountByUserAndKindParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByUserAndKind, arg.UserID, arg.Kind)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.BalanceKobo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserBalancesForAdmin = `-- name: GetUserBalancesForAdmin :one
SELECT u.id,
       u.phone,
       u.kyc_tier,
       u.realm_key_version,
       u.created_at,
       COALESCE(am.balance_kobo, 0)::BIGINT AS main_balance_kobo,
       COALESCE(al.balance_kobo, 0)::BIGINT AS lien_balance_kobo,
       (SELECT MAX(last_seen_at) FROM devices WHERE user_id = u.id)::timestamptz AS last_seen_at
FROM users u
LEFT JOIN accounts am ON am.user_id = u.id AND am.kind = 'main'
LEFT JOIN accounts al ON al.user_id = u.id AND al.kind = 'lien_holding'
WHERE u.id = $1
`

type GetUserBalancesForAdminRow struct {
	ID              string             `json:"id"`
	Phone           string             `json:"phone"`
	KycTier         string             `json:"kyc_tier"`
	RealmKeyVersion int32              `json:"realm_key_version"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	MainBalanceKobo int64              `json:"main_balance_kobo"`
	LienBalanceKobo int64              `json:"lien_balance_kobo"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
}

// GetUserBalancesForAdmin is the backoffice user-detail single-row
// lookup. Joins the main + lien-holding balances so one round trip
// renders the whole panel. Returns one row even when the user has no
// accounts provisioned yet — COALESCE holds the balances at 0.
//
// The "lien" balance is the live offline-wallet float: funds committed
// to an active ceiling and spendable offline via signed payment tokens.
func (q *Queries) GetUserBalancesForAdmin(ctx context.Context, id string) (GetUserBalancesForAdminRow, error) {
	row := q.db.QueryRow(ctx, getUserBalancesForAdmin, id)
	var i GetUserBalancesForAdminRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.KycTier,
		&i.RealmKeyVersion,
		&i.CreatedAt,
		&i.MainBalanceKobo,
		&i.LienBalanceKobo,
		&i.LastSeenAt,
	)
	return i, err
}

const incrementAccountBalance = `-- name: IncrementAccountBalance :one
UPDATE accounts
SET balance_kobo = balance_kobo + $2, updated_at = now()
WHERE id = $1
RETURNING id, user_id, kind, balance_kobo, created_at, updated_at
`

type IncrementAccountBalanceParams struct {
	ID          string `json:"id"`
	BalanceKobo int64  `json:"balance_kobo"`
}

func (q *Queries) IncrementAccountBalance(ctx context.Context, arg IncrementAccountBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, incrementAccountBalance, arg.ID, arg.BalanceKobo)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.BalanceKobo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccountsByUser = `-- name: ListAccountsByUser :many
SELECT id, user_id, kind, balance_kobo, created_at, updated_at FROM accounts WHERE user_id = $1 ORDER BY kind
`

func (q *Queries) ListAccountsByUser(ctx context.Context, userID string) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.BalanceKobo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsForAdmin = `-- name: ListAccountsForAdmin :many
SELECT id,
       kind::text AS kind,
       balance_kobo
FROM accounts
WHERE user_id = $1
ORDER BY kind
`

type ListAccountsForAdminRow struct {
	ID          string `json:"id"`
	Kind        string `json:"kind"`
	BalanceKobo int64  `json:"balance_kobo"`
}

// ListAccountsForAdmin returns every account row for one user, with
// `kind` cast to text for the admin JSON payload (the frontend treats
// it as an opaque string).
func (q *Queries) ListAccountsForAdmin(ctx context.Context, userID string) ([]ListAccountsForAdminRow, error) {
	rows, err := q.db.Query(ctx, listAccountsForAdmin, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsForAdminRow{}
	for rows.Next() {
		var i ListAccountsForAdminRow
		if err := rows.Scan(&i.ID, &i.Kind, &i.BalanceKobo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMainAccountForUser = `-- name: LockMainAccountForUser :one
SELECT id, user_id FROM accounts
WHERE user_id = $1 AND kind = 'main'
FOR UPDATE
`

type LockMainAccountForUserRow struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

// LockMainAccountForUser takes a row-level lock on the user's main
// account so the transfer processor can debit and credit inside one tx.
// FOR UPDATE is required: concurrent transfer ledger writes must
// serialise through this lock to preserve balance invariants.
func (q *Queries) LockMainAccountForUser(ctx context.Context, userID string) (LockMainAccountForUserRow, error) {
	row := q.db.QueryRow(ctx, lockMainAccountForUser, userID)
	var i LockMainAccountForUserRow
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}
