// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_sessions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdminSession = `-- name: CreateAdminSession :exec

INSERT INTO admin_sessions (id, admin_user_id, refresh_hash, user_agent, ip, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAdminSessionParams struct {
	ID          string             `json:"id"`
	AdminUserID string             `json:"admin_user_id"`
	RefreshHash string             `json:"refresh_hash"`
	UserAgent   string             `json:"user_agent"`
	Ip          string             `json:"ip"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// Admin refresh-session storage. Login creates a session; rotation
// inserts the replacement row and revokes the predecessor in one tx;
// logout revokes by hash.
// CreateAdminSession records a freshly issued refresh token at login.
// user_agent + ip are captured for audit/session-list rendering.
func (q *Queries) CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) error {
	_, err := q.db.Exec(ctx, createAdminSession,
		arg.ID,
		arg.AdminUserID,
		arg.RefreshHash,
		arg.UserAgent,
		arg.Ip,
		arg.ExpiresAt,
	)
	return err
}

const createAdminSessionRotation = `-- name: CreateAdminSessionRotation :exec
INSERT INTO admin_sessions (id, admin_user_id, refresh_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateAdminSessionRotationParams struct {
	ID          string             `json:"id"`
	AdminUserID string             `json:"admin_user_id"`
	RefreshHash string             `json:"refresh_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// CreateAdminSessionRotation records a post-refresh replacement
// session. user_agent + ip are not re-captured on rotation; the
// columns default to ” at the DB level.
func (q *Queries) CreateAdminSessionRotation(ctx context.Context, arg CreateAdminSessionRotationParams) error {
	_, err := q.db.Exec(ctx, createAdminSessionRotation,
		arg.ID,
		arg.AdminUserID,
		arg.RefreshHash,
		arg.ExpiresAt,
	)
	return err
}

const getAdminSessionByRefreshHash = `-- name: GetAdminSessionByRefreshHash :one
SELECT id, admin_user_id, revoked_at, expires_at
FROM admin_sessions
WHERE refresh_hash = $1
`

type GetAdminSessionByRefreshHashRow struct {
	ID          string             `json:"id"`
	AdminUserID string             `json:"admin_user_id"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// GetAdminSessionByRefreshHash returns the refresh-validation
// projection: the session id (to revoke on rotate), admin_user_id
// (to reload roles), and the lifecycle timestamps (to detect expiry
// and prior revocation).
func (q *Queries) GetAdminSessionByRefreshHash(ctx context.Context, refreshHash string) (GetAdminSessionByRefreshHashRow, error) {
	row := q.db.QueryRow(ctx, getAdminSessionByRefreshHash, refreshHash)
	var i GetAdminSessionByRefreshHashRow
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.RevokedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const revokeAdminSessionByHash = `-- name: RevokeAdminSessionByHash :exec
UPDATE admin_sessions
SET revoked_at = now()
WHERE refresh_hash = $1 AND revoked_at IS NULL
`

// RevokeAdminSessionByHash is the logout path. The revoked_at IS NULL
// guard keeps logout idempotent — repeat calls do nothing.
func (q *Queries) RevokeAdminSessionByHash(ctx context.Context, refreshHash string) error {
	_, err := q.db.Exec(ctx, revokeAdminSessionByHash, refreshHash)
	return err
}

const revokeAdminSessionByID = `-- name: RevokeAdminSessionByID :exec
UPDATE admin_sessions
SET revoked_at = now()
WHERE id = $1
`

// RevokeAdminSessionByID marks one session revoked. Used by the
// rotate leg of Refresh when the id is already resolved.
func (q *Queries) RevokeAdminSessionByID(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, revokeAdminSessionByID, id)
	return err
}
