// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdminUser = `-- name: CreateAdminUser :exec

INSERT INTO admin_users (id, email, full_name, password_hash)
VALUES ($1, $2, $3, $4)
`

type CreateAdminUserParams struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	FullName     string `json:"full_name"`
	PasswordHash string `json:"password_hash"`
}

// Admin user + role queries for the backoffice. admin_users is the
// internal-staff identity table — distinct from the end-user `users`
// table and its auth surface in user_auth.sql. Session and audit
// queries live in admin_sessions.sql / admin_audit.sql respectively.
// CreateAdminUser inserts a bcrypt-hashed admin user. Role grants are
// applied separately via GrantAdminRoleByName so the admin-create
// service can iterate over a caller-supplied role slice.
func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) error {
	_, err := q.db.Exec(ctx, createAdminUser,
		arg.ID,
		arg.Email,
		arg.FullName,
		arg.PasswordHash,
	)
	return err
}

const getAdminUserByID = `-- name: GetAdminUserByID :one
SELECT id, email, full_name, status, created_at
FROM admin_users
WHERE id = $1
`

type GetAdminUserByIDRow struct {
	ID        string             `json:"id"`
	Email     string             `json:"email"`
	FullName  string             `json:"full_name"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// GetAdminUserByID returns the public-facing admin profile. Used after
// create, and after refresh to reload the session's admin context.
func (q *Queries) GetAdminUserByID(ctx context.Context, id string) (GetAdminUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getAdminUserByID, id)
	var i GetAdminUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminUserForLogin = `-- name: GetAdminUserForLogin :one
SELECT id, email, full_name, status, created_at, password_hash
FROM admin_users
WHERE email = $1
`

type GetAdminUserForLoginRow struct {
	ID           string             `json:"id"`
	Email        string             `json:"email"`
	FullName     string             `json:"full_name"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	PasswordHash string             `json:"password_hash"`
}

// GetAdminUserForLogin returns the login-path projection: the public
// profile fields plus password_hash so the service bcrypt-checks in
// one round trip.
func (q *Queries) GetAdminUserForLogin(ctx context.Context, email string) (GetAdminUserForLoginRow, error) {
	row := q.db.QueryRow(ctx, getAdminUserForLogin, email)
	var i GetAdminUserForLoginRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Status,
		&i.CreatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const grantAdminRoleByName = `-- name: GrantAdminRoleByName :exec
INSERT INTO admin_user_roles (admin_user_id, role_id)
SELECT $1, id FROM admin_roles WHERE name = $2
`

type GrantAdminRoleByNameParams struct {
	AdminUserID string `json:"admin_user_id"`
	Name        string `json:"name"`
}

// GrantAdminRoleByName binds one role to an admin user by role name.
// A non-existent role name silently no-ops — the inner SELECT returns
// zero rows and the INSERT inserts zero.
func (q *Queries) GrantAdminRoleByName(ctx context.Context, arg GrantAdminRoleByNameParams) error {
	_, err := q.db.Exec(ctx, grantAdminRoleByName, arg.AdminUserID, arg.Name)
	return err
}

const listAdminRoleNamesForUser = `-- name: ListAdminRoleNamesForUser :many
SELECT r.name
FROM admin_roles r
JOIN admin_user_roles ur ON ur.role_id = r.id
WHERE ur.admin_user_id = $1
ORDER BY r.name
`

// ListAdminRoleNamesForUser returns the caller's role names, alpha
// sorted. Feeds both Login and Refresh so the issued JWT carries the
// current role set.
func (q *Queries) ListAdminRoleNamesForUser(ctx context.Context, adminUserID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listAdminRoleNamesForUser, adminUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAdminUserLastLogin = `-- name: TouchAdminUserLastLogin :exec
UPDATE admin_users
SET last_login_at = now()
WHERE id = $1
`

// TouchAdminUserLastLogin stamps a successful login. Best-effort: the
// service intentionally ignores errors so login never fails on this.
func (q *Queries) TouchAdminUserLastLogin(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchAdminUserLastLogin, id)
	return err
}
