// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_audit.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAdminAuditLog = `-- name: CountAdminAuditLog :one
SELECT COUNT(*)::BIGINT AS total FROM admin_audit_log
`

func (q *Queries) CountAdminAuditLog(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminAuditLog)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const insertAdminAuditLog = `-- name: InsertAdminAuditLog :exec

INSERT INTO admin_audit_log
    (admin_user_id, admin_email, action, target_type, target_id, payload, ip, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAdminAuditLogParams struct {
	AdminUserID *string `json:"admin_user_id"`
	AdminEmail  string  `json:"admin_email"`
	Action      string  `json:"action"`
	TargetType  string  `json:"target_type"`
	TargetID    string  `json:"target_id"`
	Payload     []byte  `json:"payload"`
	Ip          string  `json:"ip"`
	UserAgent   string  `json:"user_agent"`
}

// Admin audit log. The service's Audit() helper is best-effort — the
// insert returns nothing and errors are logged, not surfaced. The
// list/count pair powers the backoffice audit page.
// InsertAdminAuditLog appends one audit row. `payload` is JSONB;
// callers pre-marshal to []byte before invoking.
func (q *Queries) InsertAdminAuditLog(ctx context.Context, arg InsertAdminAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAdminAuditLog,
		arg.AdminUserID,
		arg.AdminEmail,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Payload,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}

const listAdminAuditLog = `-- name: ListAdminAuditLog :many
SELECT id, admin_email, action, target_type, target_id, ip, created_at
FROM admin_audit_log
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListAdminAuditLogParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAdminAuditLogRow struct {
	ID         int64              `json:"id"`
	AdminEmail string             `json:"admin_email"`
	Action     string             `json:"action"`
	TargetType string             `json:"target_type"`
	TargetID   string             `json:"target_id"`
	Ip         string             `json:"ip"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAdminAuditLog(ctx context.Context, arg ListAdminAuditLogParams) ([]ListAdminAuditLogRow, error) {
	rows, err := q.db.Query(ctx, listAdminAuditLog, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminAuditLogRow{}
	for rows.Next() {
		var i ListAdminAuditLogRow
		if err := rows.Scan(
			&i.ID,
			&i.AdminEmail,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
