// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bank_keys.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBankSigningKey = `-- name: CreateBankSigningKey :one

INSERT INTO bank_signing_keys (key_id, pubkey, privkey_enc, active_from)
VALUES ($1, $2, $3, $4)
RETURNING key_id, pubkey, privkey_enc, active_from, retired_at, created_at
`

type CreateBankSigningKeyParams struct {
	KeyID      string             `json:"key_id"`
	Pubkey     []byte             `json:"pubkey"`
	PrivkeyEnc []byte             `json:"privkey_enc"`
	ActiveFrom pgtype.Timestamptz `json:"active_from"`
}

// Bank-side Ed25519 signing keys. Rotation is "insert new, retire old";
// historical ceilings verify against the snapshotted pubkey stored in
// ceiling_tokens.payer_pubkey rather than the live row here.
func (q *Queries) CreateBankSigningKey(ctx context.Context, arg CreateBankSigningKeyParams) (BankSigningKey, error) {
	row := q.db.QueryRow(ctx, createBankSigningKey,
		arg.KeyID,
		arg.Pubkey,
		arg.PrivkeyEnc,
		arg.ActiveFrom,
	)
	var i BankSigningKey
	err := row.Scan(
		&i.KeyID,
		&i.Pubkey,
		&i.PrivkeyEnc,
		&i.ActiveFrom,
		&i.RetiredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveBankSigningKey = `-- name: GetActiveBankSigningKey :one
SELECT key_id, pubkey, privkey_enc, active_from, retired_at, created_at FROM bank_signing_keys
WHERE retired_at IS NULL
ORDER BY active_from DESC
LIMIT 1
`

func (q *Queries) GetActiveBankSigningKey(ctx context.Context) (BankSigningKey, error) {
	row := q.db.QueryRow(ctx, getActiveBankSigningKey)
	var i BankSigningKey
	err := row.Scan(
		&i.KeyID,
		&i.Pubkey,
		&i.PrivkeyEnc,
		&i.ActiveFrom,
		&i.RetiredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getBankSigningKey = `-- name: GetBankSigningKey :one
SELECT key_id, pubkey, privkey_enc, active_from, retired_at, created_at FROM bank_signing_keys WHERE key_id = $1
`

func (q *Queries) GetBankSigningKey(ctx context.Context, keyID string) (BankSigningKey, error) {
	row := q.db.QueryRow(ctx, getBankSigningKey, keyID)
	var i BankSigningKey
	err := row.Scan(
		&i.KeyID,
		&i.Pubkey,
		&i.PrivkeyEnc,
		&i.ActiveFrom,
		&i.RetiredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveBankSigningKeys = `-- name: ListActiveBankSigningKeys :many
SELECT key_id, pubkey, privkey_enc, active_from, retired_at, created_at FROM bank_signing_keys
WHERE retired_at IS NULL
ORDER BY active_from DESC
`

func (q *Queries) ListActiveBankSigningKeys(ctx context.Context) ([]BankSigningKey, error) {
	rows, err := q.db.Query(ctx, listActiveBankSigningKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BankSigningKey{}
	for rows.Next() {
		var i BankSigningKey
		if err := rows.Scan(
			&i.KeyID,
			&i.Pubkey,
			&i.PrivkeyEnc,
			&i.ActiveFrom,
			&i.RetiredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retireAllActiveBankSigningKeys = `-- name: RetireAllActiveBankSigningKeys :exec
UPDATE bank_signing_keys
SET retired_at = $1
WHERE retired_at IS NULL
`

// RetireAllActiveBankSigningKeys stamps retired_at on every still-active
// row. Called by opsctl rotate-bank-key immediately before inserting
// the freshly minted key so the new key is the only live one.
func (q *Queries) RetireAllActiveBankSigningKeys(ctx context.Context, retiredAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, retireAllActiveBankSigningKeys, retiredAt)
	return err
}

const retireBankSigningKey = `-- name: RetireBankSigningKey :exec
UPDATE bank_signing_keys SET retired_at = $2 WHERE key_id = $1
`

type RetireBankSigningKeyParams struct {
	KeyID     string             `json:"key_id"`
	RetiredAt pgtype.Timestamptz `json:"retired_at"`
}

func (q *Queries) RetireBankSigningKey(ctx context.Context, arg RetireBankSigningKeyParams) error {
	_, err := q.db.Exec(ctx, retireBankSigningKey, arg.KeyID, arg.RetiredAt)
	return err
}
