// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ceilings.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCeilingToken = `-- name: CreateCeilingToken :one

INSERT INTO ceiling_tokens (
    id, payer_user_id, ceiling_kobo, sequence_start,
    issued_at, expires_at, payer_pubkey, bank_key_id, bank_sig,
    status, lien_account_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, payer_user_id, ceiling_kobo, sequence_start, issued_at, expires_at, payer_pubkey, bank_key_id, bank_sig, status, lien_account_id, created_at, release_after
`

type CreateCeilingTokenParams struct {
	ID            string             `json:"id"`
	PayerUserID   string             `json:"payer_user_id"`
	CeilingKobo   int64              `json:"ceiling_kobo"`
	SequenceStart int64              `json:"sequence_start"`
	IssuedAt      pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	PayerPubkey   []byte             `json:"payer_pubkey"`
	BankKeyID     string             `json:"bank_key_id"`
	BankSig       []byte             `json:"bank_sig"`
	Status        CeilingStatus      `json:"status"`
	LienAccountID string             `json:"lien_account_id"`
}

// Ceiling-token CRUD + lifecycle transitions. Ceilings drive the
// offline-spending authorisation budget; each payer can have at most
// one live (ACTIVE or RECOVERY_PENDING) ceiling at a time.
func (q *Queries) CreateCeilingToken(ctx context.Context, arg CreateCeilingTokenParams) (CeilingToken, error) {
	row := q.db.QueryRow(ctx, createCeilingToken,
		arg.ID,
		arg.PayerUserID,
		arg.CeilingKobo,
		arg.SequenceStart,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.PayerPubkey,
		arg.BankKeyID,
		arg.BankSig,
		arg.Status,
		arg.LienAccountID,
	)
	var i CeilingToken
	err := row.Scan(
		&i.ID,
		&i.PayerUserID,
		&i.CeilingKobo,
		&i.SequenceStart,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.PayerPubkey,
		&i.BankKeyID,
		&i.BankSig,
		&i.Status,
		&i.LienAccountID,
		&i.CreatedAt,
		&i.ReleaseAfter,
	)
	return i, err
}

const forceExpireActiveCeiling = `-- name: ForceExpireActiveCeiling :execrows
UPDATE ceiling_tokens
SET status = 'EXPIRED'
WHERE id = $1 AND status = 'ACTIVE'
`

// ForceExpireActiveCeiling flips one ceiling to EXPIRED iff it is
// currently ACTIVE. Used by opsctl force-expire-ceiling; returns
// rows-affected so the caller can distinguish "id not found / already
// terminal" from a real transition.
func (q *Queries) ForceExpireActiveCeiling(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, forceExpireActiveCeiling, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveCeilingForUser = `-- name: GetActiveCeilingForUser :one
SELECT id, payer_user_id, ceiling_kobo, sequence_start, issued_at, expires_at, payer_pubkey, bank_key_id, bank_sig, status, lien_account_id, created_at, release_after FROM ceiling_tokens
WHERE payer_user_id = $1 AND status = 'ACTIVE'
`

func (q *Queries) GetActiveCeilingForUser(ctx context.Context, payerUserID string) (CeilingToken, error) {
	row := q.db.QueryRow(ctx, getActiveCeilingForUser, payerUserID)
	var i CeilingToken
	err := row.Scan(
		&i.ID,
		&i.PayerUserID,
		&i.CeilingKobo,
		&i.SequenceStart,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.PayerPubkey,
		&i.BankKeyID,
		&i.BankSig,
		&i.Status,
		&i.LienAccountID,
		&i.CreatedAt,
		&i.ReleaseAfter,
	)
	return i, err
}

const getCeilingRecoveryDetails = `-- name: GetCeilingRecoveryDetails :one
SELECT id, status::text AS status, ceiling_kobo, release_after,
       issued_at, expires_at
FROM ceiling_tokens
WHERE id = $1
`

type GetCeilingRecoveryDetailsRow struct {
	ID           string             `json:"id"`
	Status       string             `json:"status"`
	CeilingKobo  int64              `json:"ceiling_kobo"`
	ReleaseAfter pgtype.Timestamptz `json:"release_after"`
	IssuedAt     pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

// GetCeilingRecoveryDetails returns the narrow projection the BFF
// surfaces to the Flutter client while it polls recovery status.
// status + release_after + ceiling_kobo are the client-rendered
// fields; the remaining columns support the admin-side overlay.
func (q *Queries) GetCeilingRecoveryDetails(ctx context.Context, id string) (GetCeilingRecoveryDetailsRow, error) {
	row := q.db.QueryRow(ctx, getCeilingRecoveryDetails, id)
	var i GetCeilingRecoveryDetailsRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CeilingKobo,
		&i.ReleaseAfter,
		&i.IssuedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getCeilingToken = `-- name: GetCeilingToken :one
SELECT id, payer_user_id, ceiling_kobo, sequence_start, issued_at, expires_at, payer_pubkey, bank_key_id, bank_sig, status, lien_account_id, created_at, release_after FROM ceiling_tokens WHERE id = $1
`

func (q *Queries) GetCeilingToken(ctx context.Context, id string) (CeilingToken, error) {
	row := q.db.QueryRow(ctx, getCeilingToken, id)
	var i CeilingToken
	err := row.Scan(
		&i.ID,
		&i.PayerUserID,
		&i.CeilingKobo,
		&i.SequenceStart,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.PayerPubkey,
		&i.BankKeyID,
		&i.BankSig,
		&i.Status,
		&i.LienAccountID,
		&i.CreatedAt,
		&i.ReleaseAfter,
	)
	return i, err
}

const getCurrentCeilingForPayer = `-- name: GetCurrentCeilingForPayer :one
SELECT c.id,
       c.status::text       AS status,
       c.ceiling_kobo,
       COALESCE((
           SELECT SUM(settled_amount_kobo)
           FROM payment_tokens p
           WHERE p.ceiling_id = c.id
       ), 0)::BIGINT         AS settled_kobo,
       (c.ceiling_kobo - COALESCE((
           SELECT SUM(settled_amount_kobo)
           FROM payment_tokens p
           WHERE p.ceiling_id = c.id
       ), 0))::BIGINT        AS remaining_kobo,
       c.issued_at,
       c.expires_at,
       c.release_after
FROM ceiling_tokens c
WHERE c.payer_user_id = $1
  AND c.status IN ('ACTIVE', 'RECOVERY_PENDING')
ORDER BY c.issued_at DESC
LIMIT 1
`

type GetCurrentCeilingForPayerRow struct {
	ID            string             `json:"id"`
	Status        string             `json:"status"`
	CeilingKobo   int64              `json:"ceiling_kobo"`
	SettledKobo   int64              `json:"settled_kobo"`
	RemainingKobo int64              `json:"remaining_kobo"`
	IssuedAt      pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	ReleaseAfter  pgtype.Timestamptz `json:"release_after"`
}

// GetCurrentCeilingForPayer returns the payer's most recent non-
// terminal ceiling with its live settled and remaining totals. The
// Flutter client uses the single result to render the tri-state panel
// (active / recovery_pending / none) in one round trip.
//
// `remaining_kobo` = ceiling_kobo - SUM(settled across attached
// payment tokens). Same math releaseCeiling uses to size the lien
// release, so ops surfaces can cross-check against the lien balance.
func (q *Queries) GetCurrentCeilingForPayer(ctx context.Context, payerUserID string) (GetCurrentCeilingForPayerRow, error) {
	row := q.db.QueryRow(ctx, getCurrentCeilingForPayer, payerUserID)
	var i GetCurrentCeilingForPayerRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CeilingKobo,
		&i.SettledKobo,
		&i.RemainingKobo,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.ReleaseAfter,
	)
	return i, err
}

const listCeilingsByUser = `-- name: ListCeilingsByUser :many
SELECT id, payer_user_id, ceiling_kobo, sequence_start, issued_at, expires_at, payer_pubkey, bank_key_id, bank_sig, status, lien_account_id, created_at, release_after FROM ceiling_tokens
WHERE payer_user_id = $1
ORDER BY issued_at DESC
`

func (q *Queries) ListCeilingsByUser(ctx context.Context, payerUserID string) ([]CeilingToken, error) {
	rows, err := q.db.Query(ctx, listCeilingsByUser, payerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CeilingToken{}
	for rows.Next() {
		var i CeilingToken
		if err := rows.Scan(
			&i.ID,
			&i.PayerUserID,
			&i.CeilingKobo,
			&i.SequenceStart,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.PayerPubkey,
			&i.BankKeyID,
			&i.BankSig,
			&i.Status,
			&i.LienAccountID,
			&i.CreatedAt,
			&i.ReleaseAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCeilingsForAdmin = `-- name: ListCeilingsForAdmin :many
SELECT c.id,
       c.status::text                                         AS status,
       c.ceiling_kobo,
       (c.ceiling_kobo - COALESCE((
           SELECT SUM(settled_amount_kobo)
           FROM payment_tokens p
           WHERE p.ceiling_id = c.id
       ), 0))::BIGINT                                         AS remaining_kobo,
       c.issued_at,
       c.expires_at
FROM ceiling_tokens c
WHERE c.payer_user_id = $1
ORDER BY c.issued_at DESC
LIMIT $2
`

type ListCeilingsForAdminParams struct {
	PayerUserID string `json:"payer_user_id"`
	Limit       int32  `json:"limit"`
}

type ListCeilingsForAdminRow struct {
	ID            string             `json:"id"`
	Status        string             `json:"status"`
	CeilingKobo   int64              `json:"ceiling_kobo"`
	RemainingKobo int64              `json:"remaining_kobo"`
	IssuedAt      pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

// ListCeilingsForAdmin returns the payer's most recent ceilings with
// their live remaining balance (ceiling_kobo - SUM(settled across
// attached payment_tokens)). Feeds the backoffice user-detail view.
func (q *Queries) ListCeilingsForAdmin(ctx context.Context, arg ListCeilingsForAdminParams) ([]ListCeilingsForAdminRow, error) {
	rows, err := q.db.Query(ctx, listCeilingsForAdmin, arg.PayerUserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCeilingsForAdminRow{}
	for rows.Next() {
		var i ListCeilingsForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.CeilingKobo,
			&i.RemainingKobo,
			&i.IssuedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredActiveCeilings = `-- name: ListExpiredActiveCeilings :many
SELECT id, payer_user_id, ceiling_kobo, sequence_start, issued_at, expires_at, payer_pubkey, bank_key_id, bank_sig, status, lien_account_id, created_at, release_after FROM ceiling_tokens
WHERE status = 'ACTIVE' AND expires_at < $1
`

func (q *Queries) ListExpiredActiveCeilings(ctx context.Context, expiresAt pgtype.Timestamptz) ([]CeilingToken, error) {
	rows, err := q.db.Query(ctx, listExpiredActiveCeilings, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CeilingToken{}
	for rows.Next() {
		var i CeilingToken
		if err := rows.Scan(
			&i.ID,
			&i.PayerUserID,
			&i.CeilingKobo,
			&i.SequenceStart,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.PayerPubkey,
			&i.BankKeyID,
			&i.BankSig,
			&i.Status,
			&i.LienAccountID,
			&i.CreatedAt,
			&i.ReleaseAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleasableExpiredCeilings = `-- name: ListReleasableExpiredCeilings :many
SELECT c.id, c.payer_user_id, c.ceiling_kobo, c.sequence_start, c.issued_at, c.expires_at, c.payer_pubkey, c.bank_key_id, c.bank_sig, c.status, c.lien_account_id, c.created_at, c.release_after FROM ceiling_tokens c
WHERE (
        (c.status = 'ACTIVE'            AND c.expires_at    < $1)
     OR (c.status = 'RECOVERY_PENDING'  AND c.release_after < $1)
      )
  AND NOT EXISTS (
    SELECT 1 FROM payment_tokens p
    WHERE p.ceiling_id = c.id
      AND p.status IN ('PENDING', 'SUBMITTED')
  )
`

// ListReleasableExpiredCeilings picks up ceilings ready to be released
// back to the main wallet:
//  1. ACTIVE ceilings past their grace window (normal expiry path).
//  2. RECOVERY_PENDING ceilings past release_after (recovery
//     quarantine elapsed).
//
// Rows with in-flight payment claims are skipped — those funds are
// legitimately owed and will be claimed by the merchant settlement.
func (q *Queries) ListReleasableExpiredCeilings(ctx context.Context, expiresAt pgtype.Timestamptz) ([]CeilingToken, error) {
	rows, err := q.db.Query(ctx, listReleasableExpiredCeilings, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CeilingToken{}
	for rows.Next() {
		var i CeilingToken
		if err := rows.Scan(
			&i.ID,
			&i.PayerUserID,
			&i.CeilingKobo,
			&i.SequenceStart,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.PayerPubkey,
			&i.BankKeyID,
			&i.BankSig,
			&i.Status,
			&i.LienAccountID,
			&i.CreatedAt,
			&i.ReleaseAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCeilingRecoveryPending = `-- name: MarkCeilingRecoveryPending :execrows
UPDATE ceiling_tokens
SET status = 'RECOVERY_PENDING',
    release_after = $2
WHERE id = $1 AND status = 'ACTIVE'
`

type MarkCeilingRecoveryPendingParams struct {
	ID           string             `json:"id"`
	ReleaseAfter pgtype.Timestamptz `json:"release_after"`
}

// MarkCeilingRecoveryPending transitions an ACTIVE ceiling into
// RECOVERY_PENDING and stamps release_after. Returns rows-affected so
// the caller can distinguish "no active ceiling", "already
// recovering", and "success".
func (q *Queries) MarkCeilingRecoveryPending(ctx context.Context, arg MarkCeilingRecoveryPendingParams) (int64, error) {
	result, err := q.db.Exec(ctx, markCeilingRecoveryPending, arg.ID, arg.ReleaseAfter)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sumSettledForCeiling = `-- name: SumSettledForCeiling :one
SELECT COALESCE(SUM(settled_amount_kobo), 0)::BIGINT AS settled_kobo
FROM payment_tokens
WHERE ceiling_id = $1
`

// SumSettledForCeiling returns the total settled amount across every
// payment token attached to this ceiling. releaseCeiling subtracts
// this from ceiling_kobo to derive the remaining lien — attempting
// to debit the full ceiling would trip the balance_kobo >= $amount
// guard the moment any merchant claim has landed.
func (q *Queries) SumSettledForCeiling(ctx context.Context, ceilingID string) (int64, error) {
	row := q.db.QueryRow(ctx, sumSettledForCeiling, ceilingID)
	var settled_kobo int64
	err := row.Scan(&settled_kobo)
	return settled_kobo, err
}

const updateCeilingStatus = `-- name: UpdateCeilingStatus :exec
UPDATE ceiling_tokens SET status = $2 WHERE id = $1
`

type UpdateCeilingStatusParams struct {
	ID     string        `json:"id"`
	Status CeilingStatus `json:"status"`
}

func (q *Queries) UpdateCeilingStatus(ctx context.Context, arg UpdateCeilingStatusParams) error {
	_, err := q.db.Exec(ctx, updateCeilingStatus, arg.ID, arg.Status)
	return err
}
