// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDevice = `-- name: CreateDevice :one

INSERT INTO devices (id, user_id, attestation_blob, public_key, active, last_seen_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, attestation_blob, public_key, active, last_seen_at, attestation_platform, attestation_verified_at, created_at, updated_at
`

type CreateDeviceParams struct {
	ID              string             `json:"id"`
	UserID          string             `json:"user_id"`
	AttestationBlob []byte             `json:"attestation_blob"`
	PublicKey       []byte             `json:"public_key"`
	Active          bool               `json:"active"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
}

// Device registry. One active device per user is enforced at the
// schema level (partial unique index); these queries own the lifecycle
// (register, touch, deactivate) plus the admin read surface.
func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.ID,
		arg.UserID,
		arg.AttestationBlob,
		arg.PublicKey,
		arg.Active,
		arg.LastSeenAt,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AttestationBlob,
		&i.PublicKey,
		&i.Active,
		&i.LastSeenAt,
		&i.AttestationPlatform,
		&i.AttestationVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateDevice = `-- name: DeactivateDevice :exec
UPDATE devices SET active = FALSE, updated_at = now() WHERE id = $1
`

func (q *Queries) DeactivateDevice(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deactivateDevice, id)
	return err
}

const getActiveDeviceForUser = `-- name: GetActiveDeviceForUser :one
SELECT id, user_id, attestation_blob, public_key, active, last_seen_at, attestation_platform, attestation_verified_at, created_at, updated_at FROM devices WHERE user_id = $1 AND active = TRUE
`

func (q *Queries) GetActiveDeviceForUser(ctx context.Context, userID string) (Device, error) {
	row := q.db.QueryRow(ctx, getActiveDeviceForUser, userID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AttestationBlob,
		&i.PublicKey,
		&i.Active,
		&i.LastSeenAt,
		&i.AttestationPlatform,
		&i.AttestationVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDevice = `-- name: GetDevice :one
SELECT id, user_id, attestation_blob, public_key, active, last_seen_at, attestation_platform, attestation_verified_at, created_at, updated_at FROM devices WHERE id = $1
`

func (q *Queries) GetDevice(ctx context.Context, id string) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AttestationBlob,
		&i.PublicKey,
		&i.Active,
		&i.LastSeenAt,
		&i.AttestationPlatform,
		&i.AttestationVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDevicesForAdmin = `-- name: ListDevicesForAdmin :many
SELECT id,
       active,
       last_seen_at,
       created_at
FROM devices
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListDevicesForAdminRow struct {
	ID         string             `json:"id"`
	Active     bool               `json:"active"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// ListDevicesForAdmin returns the backoffice projection for one
// user's devices, newest first. Narrow column set so the backoffice
// payload stays stable independent of internal schema additions.
func (q *Queries) ListDevicesForAdmin(ctx context.Context, userID string) ([]ListDevicesForAdminRow, error) {
	rows, err := q.db.Query(ctx, listDevicesForAdmin, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDevicesForAdminRow{}
	for rows.Next() {
		var i ListDevicesForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Active,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchDevice = `-- name: TouchDevice :exec
UPDATE devices SET last_seen_at = $2, updated_at = now() WHERE id = $1
`

type TouchDeviceParams struct {
	ID         string             `json:"id"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) TouchDevice(ctx context.Context, arg TouchDeviceParams) error {
	_, err := q.db.Exec(ctx, touchDevice, arg.ID, arg.LastSeenAt)
	return err
}
