// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fraud.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFraudSignalsByUser = `-- name: CountFraudSignalsByUser :one
SELECT COUNT(*)::BIGINT AS count FROM fraud_signals WHERE user_id = $1
`

func (q *Queries) CountFraudSignalsByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countFraudSignalsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFraudSignalsGlobal = `-- name: CountFraudSignalsGlobal :one
SELECT COUNT(*)::BIGINT AS count FROM fraud_signals
`

func (q *Queries) CountFraudSignalsGlobal(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFraudSignalsGlobal)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertFraudScore = `-- name: InsertFraudScore :exec
INSERT INTO fraud_scores
    (id, transfer_id, sender_id, decision, rule, reason, rule_hits, amount_kobo)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertFraudScoreParams struct {
	ID         string  `json:"id"`
	TransferID string  `json:"transfer_id"`
	SenderID   string  `json:"sender_id"`
	Decision   string  `json:"decision"`
	Rule       *string `json:"rule"`
	Reason     *string `json:"reason"`
	RuleHits   []byte  `json:"rule_hits"`
	AmountKobo int64   `json:"amount_kobo"`
}

// InsertFraudScore records a BLOCK or FLAG decision for one transfer.
// ALLOW outcomes are trace-only and never written to this table so it
// stays small and queryable.
func (q *Queries) InsertFraudScore(ctx context.Context, arg InsertFraudScoreParams) error {
	_, err := q.db.Exec(ctx, insertFraudScore,
		arg.ID,
		arg.TransferID,
		arg.SenderID,
		arg.Decision,
		arg.Rule,
		arg.Reason,
		arg.RuleHits,
		arg.AmountKobo,
	)
	return err
}

const insertFraudSignal = `-- name: InsertFraudSignal :one

INSERT INTO fraud_signals (
    id, user_id, signal_type, ceiling_token_id, transaction_id,
    details, severity, weight
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, signal_type, ceiling_token_id, transaction_id, details, severity, weight, created_at
`

type InsertFraudSignalParams struct {
	ID             string          `json:"id"`
	UserID         string          `json:"user_id"`
	SignalType     FraudSignalType `json:"signal_type"`
	CeilingTokenID *string         `json:"ceiling_token_id"`
	TransactionID  *string         `json:"transaction_id"`
	Details        string          `json:"details"`
	Severity       string          `json:"severity"`
	Weight         float64         `json:"weight"`
}

// Fraud signals (cryptographic/offline anomalies on payment_tokens)
// and fraud scores (scoring decisions on online transfers). The two
// streams are distinct domains and deliberately unioned only at the
// admin-reporting layer.
func (q *Queries) InsertFraudSignal(ctx context.Context, arg InsertFraudSignalParams) (FraudSignal, error) {
	row := q.db.QueryRow(ctx, insertFraudSignal,
		arg.ID,
		arg.UserID,
		arg.SignalType,
		arg.CeilingTokenID,
		arg.TransactionID,
		arg.Details,
		arg.Severity,
		arg.Weight,
	)
	var i FraudSignal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SignalType,
		&i.CeilingTokenID,
		&i.TransactionID,
		&i.Details,
		&i.Severity,
		&i.Weight,
		&i.CreatedAt,
	)
	return i, err
}

const listFraudSignalsByUser = `-- name: ListFraudSignalsByUser :many
SELECT id, user_id, signal_type, ceiling_token_id, transaction_id, details, severity, weight, created_at FROM fraud_signals
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListFraudSignalsByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) ListFraudSignalsByUser(ctx context.Context, arg ListFraudSignalsByUserParams) ([]FraudSignal, error) {
	rows, err := q.db.Query(ctx, listFraudSignalsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FraudSignal{}
	for rows.Next() {
		var i FraudSignal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SignalType,
			&i.CeilingTokenID,
			&i.TransactionID,
			&i.Details,
			&i.Severity,
			&i.Weight,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFraudSignalsForAdmin = `-- name: ListFraudSignalsForAdmin :many
SELECT id,
       signal_type::text AS signal,
       severity,
       weight,
       created_at
FROM fraud_signals
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListFraudSignalsForAdminParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

type ListFraudSignalsForAdminRow struct {
	ID        string             `json:"id"`
	Signal    string             `json:"signal"`
	Severity  string             `json:"severity"`
	Weight    float64            `json:"weight"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// ListFraudSignalsForAdmin powers the backoffice user-detail view.
// Caller caps via $2; typical page is 20 newest signals.
func (q *Queries) ListFraudSignalsForAdmin(ctx context.Context, arg ListFraudSignalsForAdminParams) ([]ListFraudSignalsForAdminRow, error) {
	rows, err := q.db.Query(ctx, listFraudSignalsForAdmin, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFraudSignalsForAdminRow{}
	for rows.Next() {
		var i ListFraudSignalsForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Signal,
			&i.Severity,
			&i.Weight,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFraudSignalsForUser = `-- name: ListFraudSignalsForUser :many
SELECT id, user_id, signal_type, ceiling_token_id, transaction_id, details, severity, weight, created_at FROM fraud_signals
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListFraudSignalsForUser(ctx context.Context, userID string) ([]FraudSignal, error) {
	rows, err := q.db.Query(ctx, listFraudSignalsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FraudSignal{}
	for rows.Next() {
		var i FraudSignal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SignalType,
			&i.CeilingTokenID,
			&i.TransactionID,
			&i.Details,
			&i.Severity,
			&i.Weight,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFraudSignalsGlobal = `-- name: ListFraudSignalsGlobal :many
SELECT id,
       user_id,
       signal_type::text AS signal,
       severity,
       weight,
       details,
       ceiling_token_id,
       transaction_id,
       created_at
FROM fraud_signals
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListFraudSignalsGlobalParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListFraudSignalsGlobalRow struct {
	ID             string             `json:"id"`
	UserID         string             `json:"user_id"`
	Signal         string             `json:"signal"`
	Severity       string             `json:"severity"`
	Weight         float64            `json:"weight"`
	Details        string             `json:"details"`
	CeilingTokenID *string            `json:"ceiling_token_id"`
	TransactionID  *string            `json:"transaction_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// ListFraudSignalsGlobal powers the fraud dashboard. Widens the
// per-user projection with user_id, details, and the optional ceiling
// and transaction refs so the operator can click through to context
// from a single page.
func (q *Queries) ListFraudSignalsGlobal(ctx context.Context, arg ListFraudSignalsGlobalParams) ([]ListFraudSignalsGlobalRow, error) {
	rows, err := q.db.Query(ctx, listFraudSignalsGlobal, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFraudSignalsGlobalRow{}
	for rows.Next() {
		var i ListFraudSignalsGlobalRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Signal,
			&i.Severity,
			&i.Weight,
			&i.Details,
			&i.CeilingTokenID,
			&i.TransactionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
