// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kyc.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getKYCSubmissionSubmittedAt = `-- name: GetKYCSubmissionSubmittedAt :one
SELECT submitted_at FROM kyc_submissions WHERE id = $1
`

// GetKYCSubmissionSubmittedAt reads back the DB-assigned default
// timestamp post-insert so the caller's returned struct reflects the
// server clock rather than a client-supplied value.
func (q *Queries) GetKYCSubmissionSubmittedAt(ctx context.Context, id string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getKYCSubmissionSubmittedAt, id)
	var submitted_at pgtype.Timestamptz
	err := row.Scan(&submitted_at)
	return submitted_at, err
}

const insertKYCSubmission = `-- name: InsertKYCSubmission :exec

INSERT INTO kyc_submissions
    (id, user_id, id_type, id_number, status, rejection_reason,
     tier_granted, submitted_by, verified_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertKYCSubmissionParams struct {
	ID              string             `json:"id"`
	UserID          string             `json:"user_id"`
	IDType          string             `json:"id_type"`
	IDNumber        string             `json:"id_number"`
	Status          string             `json:"status"`
	RejectionReason *string            `json:"rejection_reason"`
	TierGranted     *string            `json:"tier_granted"`
	SubmittedBy     *string            `json:"submitted_by"`
	VerifiedAt      pgtype.Timestamptz `json:"verified_at"`
}

// KYC submissions + history reads. Tier promotion itself mutates the
// users table and lives in users.sql (PromoteUserToTier).
// InsertKYCSubmission records one submission. Status is caller-
// computed ('VERIFIED' or 'REJECTED'); the column's check constraint
// rejects stray values.
func (q *Queries) InsertKYCSubmission(ctx context.Context, arg InsertKYCSubmissionParams) error {
	_, err := q.db.Exec(ctx, insertKYCSubmission,
		arg.ID,
		arg.UserID,
		arg.IDType,
		arg.IDNumber,
		arg.Status,
		arg.RejectionReason,
		arg.TierGranted,
		arg.SubmittedBy,
		arg.VerifiedAt,
	)
	return err
}

const listKYCSubmissionsByUser = `-- name: ListKYCSubmissionsByUser :many
SELECT id, user_id, id_type, id_number, status, rejection_reason,
       tier_granted, submitted_by, submitted_at, verified_at
FROM kyc_submissions
WHERE user_id = $1
ORDER BY submitted_at DESC
`

// ListKYCSubmissionsByUser powers the per-user KYC history view.
func (q *Queries) ListKYCSubmissionsByUser(ctx context.Context, userID string) ([]KycSubmission, error) {
	rows, err := q.db.Query(ctx, listKYCSubmissionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KycSubmission{}
	for rows.Next() {
		var i KycSubmission
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.IDType,
			&i.IDNumber,
			&i.Status,
			&i.RejectionReason,
			&i.TierGranted,
			&i.SubmittedBy,
			&i.SubmittedAt,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
