// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger.sql

package sqlcgen

import (
	"context"
)

const insertLedgerEntry = `-- name: InsertLedgerEntry :one

INSERT INTO ledger_entries (id, txn_id, account_id, direction, amount_kobo, memo)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, txn_id, account_id, direction, amount_kobo, memo, created_at
`

type InsertLedgerEntryParams struct {
	ID         string          `json:"id"`
	TxnID      string          `json:"txn_id"`
	AccountID  string          `json:"account_id"`
	Direction  LedgerDirection `json:"direction"`
	AmountKobo int64           `json:"amount_kobo"`
	Memo       *string         `json:"memo"`
}

// Double-entry ledger primitives. Every posting is a pair (DEBIT +
// CREDIT) sharing one txn_id; the deferred constraint trigger on
// ledger_entries enforces balance at COMMIT. These queries are the
// mechanical insert/read path — ledger-balance invariants live in the
// trigger and the Repo.Tx boundary.
func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, insertLedgerEntry,
		arg.ID,
		arg.TxnID,
		arg.AccountID,
		arg.Direction,
		arg.AmountKobo,
		arg.Memo,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.TxnID,
		&i.AccountID,
		&i.Direction,
		&i.AmountKobo,
		&i.Memo,
		&i.CreatedAt,
	)
	return i, err
}

const listLedgerEntriesByAccount = `-- name: ListLedgerEntriesByAccount :many
SELECT id, txn_id, account_id, direction, amount_kobo, memo, created_at FROM ledger_entries
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLedgerEntriesByAccountParams struct {
	AccountID string `json:"account_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListLedgerEntriesByAccount(ctx context.Context, arg ListLedgerEntriesByAccountParams) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesByAccount, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEntry{}
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.TxnID,
			&i.AccountID,
			&i.Direction,
			&i.AmountKobo,
			&i.Memo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEntriesByTxn = `-- name: ListLedgerEntriesByTxn :many
SELECT id, txn_id, account_id, direction, amount_kobo, memo, created_at FROM ledger_entries WHERE txn_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListLedgerEntriesByTxn(ctx context.Context, txnID string) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesByTxn, txnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEntry{}
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.TxnID,
			&i.AccountID,
			&i.Direction,
			&i.AmountKobo,
			&i.Memo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumAccountCredits = `-- name: SumAccountCredits :one
SELECT COALESCE(SUM(amount_kobo), 0)::BIGINT AS total
FROM ledger_entries WHERE account_id = $1 AND direction = 'CREDIT'
`

func (q *Queries) SumAccountCredits(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, sumAccountCredits, accountID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const sumAccountDebits = `-- name: SumAccountDebits :one
SELECT COALESCE(SUM(amount_kobo), 0)::BIGINT AS total
FROM ledger_entries WHERE account_id = $1 AND direction = 'DEBIT'
`

func (q *Queries) SumAccountDebits(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, sumAccountDebits, accountID)
	var total int64
	err := row.Scan(&total)
	return total, err
}
