// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccountKind string

const (
	AccountKindMain             AccountKind = "main"
	AccountKindLienHolding      AccountKind = "lien_holding"
	AccountKindReceivingPending AccountKind = "receiving_pending"
	AccountKindSuspense         AccountKind = "suspense"
)

func (e *AccountKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountKind(s)
	case string:
		*e = AccountKind(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountKind: %T", src)
	}
	return nil
}

type NullAccountKind struct {
	AccountKind AccountKind `json:"account_kind"`
	Valid       bool        `json:"valid"` // Valid is true if AccountKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountKind) Scan(value interface{}) error {
	if value == nil {
		ns.AccountKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountKind), nil
}

type CeilingStatus string

const (
	CeilingStatusACTIVE          CeilingStatus = "ACTIVE"
	CeilingStatusRECOVERYPENDING CeilingStatus = "RECOVERY_PENDING"
	CeilingStatusEXPIRED         CeilingStatus = "EXPIRED"
	CeilingStatusEXHAUSTED       CeilingStatus = "EXHAUSTED"
	CeilingStatusREVOKED         CeilingStatus = "REVOKED"
)

func (e *CeilingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CeilingStatus(s)
	case string:
		*e = CeilingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CeilingStatus: %T", src)
	}
	return nil
}

type NullCeilingStatus struct {
	CeilingStatus CeilingStatus `json:"ceiling_status"`
	Valid         bool          `json:"valid"` // Valid is true if CeilingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCeilingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CeilingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CeilingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCeilingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CeilingStatus), nil
}

type FraudSignalType string

const (
	FraudSignalTypeDOUBLESPEND       FraudSignalType = "DOUBLE_SPEND"
	FraudSignalTypeCEILINGEXHAUSTION FraudSignalType = "CEILING_EXHAUSTION"
	FraudSignalTypeGEOGRAPHICANOMALY FraudSignalType = "GEOGRAPHIC_ANOMALY"
	FraudSignalTypeSEQUENCEANOMALY   FraudSignalType = "SEQUENCE_ANOMALY"
	FraudSignalTypeDEVICECHANGE      FraudSignalType = "DEVICE_CHANGE"
	FraudSignalTypeVELOCITYBREACH    FraudSignalType = "VELOCITY_BREACH"
	FraudSignalTypeSIGNATUREINVALID  FraudSignalType = "SIGNATURE_INVALID"
)

func (e *FraudSignalType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FraudSignalType(s)
	case string:
		*e = FraudSignalType(s)
	default:
		return fmt.Errorf("unsupported scan type for FraudSignalType: %T", src)
	}
	return nil
}

type NullFraudSignalType struct {
	FraudSignalType FraudSignalType `json:"fraud_signal_type"`
	Valid           bool            `json:"valid"` // Valid is true if FraudSignalType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFraudSignalType) Scan(value interface{}) error {
	if value == nil {
		ns.FraudSignalType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FraudSignalType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFraudSignalType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FraudSignalType), nil
}

type LedgerDirection string

const (
	LedgerDirectionDEBIT  LedgerDirection = "DEBIT"
	LedgerDirectionCREDIT LedgerDirection = "CREDIT"
)

func (e *LedgerDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LedgerDirection(s)
	case string:
		*e = LedgerDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for LedgerDirection: %T", src)
	}
	return nil
}

type NullLedgerDirection struct {
	LedgerDirection LedgerDirection `json:"ledger_direction"`
	Valid           bool            `json:"valid"` // Valid is true if LedgerDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLedgerDirection) Scan(value interface{}) error {
	if value == nil {
		ns.LedgerDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LedgerDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLedgerDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LedgerDirection), nil
}

type PaymentStatus string

const (
	PaymentStatusQUEUED           PaymentStatus = "QUEUED"
	PaymentStatusSUBMITTED        PaymentStatus = "SUBMITTED"
	PaymentStatusPENDING          PaymentStatus = "PENDING"
	PaymentStatusSETTLED          PaymentStatus = "SETTLED"
	PaymentStatusPARTIALLYSETTLED PaymentStatus = "PARTIALLY_SETTLED"
	PaymentStatusREJECTED         PaymentStatus = "REJECTED"
	PaymentStatusEXPIRED          PaymentStatus = "EXPIRED"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus `json:"payment_status"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type ReconciliationStatus string

const (
	ReconciliationStatusCLEAN       ReconciliationStatus = "CLEAN"
	ReconciliationStatusDISCREPANCY ReconciliationStatus = "DISCREPANCY"
	ReconciliationStatusINPROGRESS  ReconciliationStatus = "IN_PROGRESS"
)

func (e *ReconciliationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReconciliationStatus(s)
	case string:
		*e = ReconciliationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReconciliationStatus: %T", src)
	}
	return nil
}

type NullReconciliationStatus struct {
	ReconciliationStatus ReconciliationStatus `json:"reconciliation_status"`
	Valid                bool                 `json:"valid"` // Valid is true if ReconciliationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReconciliationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReconciliationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReconciliationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReconciliationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReconciliationStatus), nil
}

type ReconciliationType string

const (
	ReconciliationTypePAYER    ReconciliationType = "PAYER"
	ReconciliationTypeMERCHANT ReconciliationType = "MERCHANT"
	ReconciliationTypeLEDGER   ReconciliationType = "LEDGER"
)

func (e *ReconciliationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReconciliationType(s)
	case string:
		*e = ReconciliationType(s)
	default:
		return fmt.Errorf("unsupported scan type for ReconciliationType: %T", src)
	}
	return nil
}

type NullReconciliationType struct {
	ReconciliationType ReconciliationType `json:"reconciliation_type"`
	Valid              bool               `json:"valid"` // Valid is true if ReconciliationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReconciliationType) Scan(value interface{}) error {
	if value == nil {
		ns.ReconciliationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReconciliationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReconciliationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReconciliationType), nil
}

type TransactionKind string

const (
	TransactionKindOFFLINEFUND            TransactionKind = "OFFLINE_FUND"
	TransactionKindOFFLINEDRAIN           TransactionKind = "OFFLINE_DRAIN"
	TransactionKindOFFLINEEXPIRYRELEASE   TransactionKind = "OFFLINE_EXPIRY_RELEASE"
	TransactionKindOFFLINEPAYMENTSENT     TransactionKind = "OFFLINE_PAYMENT_SENT"
	TransactionKindOFFLINEPAYMENTRECEIVED TransactionKind = "OFFLINE_PAYMENT_RECEIVED"
	TransactionKindTRANSFERSENT           TransactionKind = "TRANSFER_SENT"
	TransactionKindTRANSFERRECEIVED       TransactionKind = "TRANSFER_RECEIVED"
	TransactionKindDEMOMINT               TransactionKind = "DEMO_MINT"
	TransactionKindOFFLINERECOVERYRELEASE TransactionKind = "OFFLINE_RECOVERY_RELEASE"
)

func (e *TransactionKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionKind(s)
	case string:
		*e = TransactionKind(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionKind: %T", src)
	}
	return nil
}

type NullTransactionKind struct {
	TransactionKind TransactionKind `json:"transaction_kind"`
	Valid           bool            `json:"valid"` // Valid is true if TransactionKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionKind) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionKind), nil
}

type TransactionLifecycleStatus string

const (
	TransactionLifecycleStatusPENDING   TransactionLifecycleStatus = "PENDING"
	TransactionLifecycleStatusCOMPLETED TransactionLifecycleStatus = "COMPLETED"
	TransactionLifecycleStatusFAILED    TransactionLifecycleStatus = "FAILED"
	TransactionLifecycleStatusREVERSED  TransactionLifecycleStatus = "REVERSED"
)

func (e *TransactionLifecycleStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionLifecycleStatus(s)
	case string:
		*e = TransactionLifecycleStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionLifecycleStatus: %T", src)
	}
	return nil
}

type NullTransactionLifecycleStatus struct {
	TransactionLifecycleStatus TransactionLifecycleStatus `json:"transaction_lifecycle_status"`
	Valid                      bool                       `json:"valid"` // Valid is true if TransactionLifecycleStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionLifecycleStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionLifecycleStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionLifecycleStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionLifecycleStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionLifecycleStatus), nil
}

type Account struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	Kind        AccountKind        `json:"kind"`
	BalanceKobo int64              `json:"balance_kobo"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AdminAuditLog struct {
	ID          int64              `json:"id"`
	AdminUserID *string            `json:"admin_user_id"`
	AdminEmail  string             `json:"admin_email"`
	Action      string             `json:"action"`
	TargetType  string             `json:"target_type"`
	TargetID    string             `json:"target_id"`
	Payload     []byte             `json:"payload"`
	Ip          string             `json:"ip"`
	UserAgent   string             `json:"user_agent"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AdminRole struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AdminSession struct {
	ID          string             `json:"id"`
	AdminUserID string             `json:"admin_user_id"`
	RefreshHash string             `json:"refresh_hash"`
	UserAgent   string             `json:"user_agent"`
	Ip          string             `json:"ip"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
}

type AdminUser struct {
	ID           string             `json:"id"`
	Email        string             `json:"email"`
	FullName     string             `json:"full_name"`
	PasswordHash string             `json:"password_hash"`
	TotpSecret   *string            `json:"totp_secret"`
	TotpEnrolled bool               `json:"totp_enrolled"`
	Status       string             `json:"status"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type AdminUserRole struct {
	AdminUserID string             `json:"admin_user_id"`
	RoleID      string             `json:"role_id"`
	GrantedAt   pgtype.Timestamptz `json:"granted_at"`
}

type BankSigningKey struct {
	KeyID      string             `json:"key_id"`
	Pubkey     []byte             `json:"pubkey"`
	PrivkeyEnc []byte             `json:"privkey_enc"`
	ActiveFrom pgtype.Timestamptz `json:"active_from"`
	RetiredAt  pgtype.Timestamptz `json:"retired_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type CeilingToken struct {
	ID            string             `json:"id"`
	PayerUserID   string             `json:"payer_user_id"`
	CeilingKobo   int64              `json:"ceiling_kobo"`
	SequenceStart int64              `json:"sequence_start"`
	IssuedAt      pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	PayerPubkey   []byte             `json:"payer_pubkey"`
	BankKeyID     string             `json:"bank_key_id"`
	BankSig       []byte             `json:"bank_sig"`
	Status        CeilingStatus      `json:"status"`
	LienAccountID string             `json:"lien_account_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ReleaseAfter  pgtype.Timestamptz `json:"release_after"`
}

type Device struct {
	ID                    string             `json:"id"`
	UserID                string             `json:"user_id"`
	AttestationBlob       []byte             `json:"attestation_blob"`
	PublicKey             []byte             `json:"public_key"`
	Active                bool               `json:"active"`
	LastSeenAt            pgtype.Timestamptz `json:"last_seen_at"`
	AttestationPlatform   *string            `json:"attestation_platform"`
	AttestationVerifiedAt pgtype.Timestamptz `json:"attestation_verified_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type FraudScore struct {
	ID         string             `json:"id"`
	TransferID string             `json:"transfer_id"`
	SenderID   string             `json:"sender_id"`
	Decision   string             `json:"decision"`
	Rule       *string            `json:"rule"`
	Reason     *string            `json:"reason"`
	RuleHits   []byte             `json:"rule_hits"`
	AmountKobo int64              `json:"amount_kobo"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type FraudSignal struct {
	ID             string             `json:"id"`
	UserID         string             `json:"user_id"`
	SignalType     FraudSignalType    `json:"signal_type"`
	CeilingTokenID *string            `json:"ceiling_token_id"`
	TransactionID  *string            `json:"transaction_id"`
	Details        string             `json:"details"`
	Severity       string             `json:"severity"`
	Weight         float64            `json:"weight"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type KycSubmission struct {
	ID              string             `json:"id"`
	UserID          string             `json:"user_id"`
	IDType          string             `json:"id_type"`
	IDNumber        string             `json:"id_number"`
	Status          string             `json:"status"`
	RejectionReason *string            `json:"rejection_reason"`
	TierGranted     *string            `json:"tier_granted"`
	SubmittedBy     *string            `json:"submitted_by"`
	SubmittedAt     pgtype.Timestamptz `json:"submitted_at"`
	VerifiedAt      pgtype.Timestamptz `json:"verified_at"`
}

type LedgerEntry struct {
	ID         string             `json:"id"`
	TxnID      string             `json:"txn_id"`
	AccountID  string             `json:"account_id"`
	Direction  LedgerDirection    `json:"direction"`
	AmountKobo int64              `json:"amount_kobo"`
	Memo       *string            `json:"memo"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type OtpChallenge struct {
	Identifier string             `json:"identifier"`
	CodeHash   string             `json:"code_hash"`
	Purpose    string             `json:"purpose"`
	Attempts   int32              `json:"attempts"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
}

type Outbox struct {
	ID            string             `json:"id"`
	Aggregate     string             `json:"aggregate"`
	AggregateID   string             `json:"aggregate_id"`
	Payload       []byte             `json:"payload"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	DispatchedAt  pgtype.Timestamptz `json:"dispatched_at"`
	Attempts      int32              `json:"attempts"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
}

type PaymentToken struct {
	ID                   string             `json:"id"`
	CeilingID            string             `json:"ceiling_id"`
	PayerUserID          string             `json:"payer_user_id"`
	PayeeUserID          string             `json:"payee_user_id"`
	AmountKobo           int64              `json:"amount_kobo"`
	SequenceNumber       int64              `json:"sequence_number"`
	RemainingCeilingKobo int64              `json:"remaining_ceiling_kobo"`
	SettledAmountKobo    int64              `json:"settled_amount_kobo"`
	SignedAt             pgtype.Timestamptz `json:"signed_at"`
	PayerSig             []byte             `json:"payer_sig"`
	Status               PaymentStatus      `json:"status"`
	RejectionReason      *string            `json:"rejection_reason"`
	SettlementBatchID    *string            `json:"settlement_batch_id"`
	SubmittedAt          pgtype.Timestamptz `json:"submitted_at"`
	SettledAt            pgtype.Timestamptz `json:"settled_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	SessionNonce         []byte             `json:"session_nonce"`
	RequestHash          []byte             `json:"request_hash"`
	RequestAmountKobo    int64              `json:"request_amount_kobo"`
	SubmittedByUserID    *string            `json:"submitted_by_user_id"`
}

type ProcessedEvent struct {
	OutboxID    string             `json:"outbox_id"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
	Status      string             `json:"status"`
}

type PushToken struct {
	FcmToken  string             `json:"fcm_token"`
	UserID    string             `json:"user_id"`
	Platform  string             `json:"platform"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RealmKey struct {
	Version    int32              `json:"version"`
	KeyEnc     []byte             `json:"key_enc"`
	ActiveFrom pgtype.Timestamptz `json:"active_from"`
	RetiredAt  pgtype.Timestamptz `json:"retired_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ReconciliationRun struct {
	ID            string               `json:"id"`
	Type          ReconciliationType   `json:"type"`
	EntityID      string               `json:"entity_id"`
	RunAt         pgtype.Timestamptz   `json:"run_at"`
	Status        ReconciliationStatus `json:"status"`
	Discrepancies []byte               `json:"discrepancies"`
	CreatedAt     pgtype.Timestamptz   `json:"created_at"`
}

type SigningKey struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	DeviceID  *string            `json:"device_id"`
	PublicKey []byte             `json:"public_key"`
	Active    bool               `json:"active"`
	RotatedAt pgtype.Timestamptz `json:"rotated_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Transaction struct {
	ID                 string                     `json:"id"`
	UserID             string                     `json:"user_id"`
	CounterpartyUserID *string                    `json:"counterparty_user_id"`
	Kind               TransactionKind            `json:"kind"`
	Status             TransactionLifecycleStatus `json:"status"`
	Direction          LedgerDirection            `json:"direction"`
	AmountKobo         int64                      `json:"amount_kobo"`
	SettledAmountKobo  *int64                     `json:"settled_amount_kobo"`
	Memo               *string                    `json:"memo"`
	PaymentTokenID     *string                    `json:"payment_token_id"`
	TransferID         *string                    `json:"transfer_id"`
	CeilingID          *string                    `json:"ceiling_id"`
	GroupID            string                     `json:"group_id"`
	FailureReason      *string                    `json:"failure_reason"`
	CreatedAt          pgtype.Timestamptz         `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz         `json:"updated_at"`
}

type Transfer struct {
	ID                    string             `json:"id"`
	SenderUserID          string             `json:"sender_user_id"`
	ReceiverUserID        string             `json:"receiver_user_id"`
	ReceiverAccountNumber string             `json:"receiver_account_number"`
	AmountKobo            int64              `json:"amount_kobo"`
	Status                string             `json:"status"`
	Reference             string             `json:"reference"`
	FailureReason         *string            `json:"failure_reason"`
	Flagged               bool               `json:"flagged"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	SettledAt             pgtype.Timestamptz `json:"settled_at"`
}

type User struct {
	ID                  string             `json:"id"`
	Phone               string             `json:"phone"`
	AccountNumber       string             `json:"account_number"`
	Bvn                 *string            `json:"bvn"`
	KycTier             string             `json:"kyc_tier"`
	DeviceAttestationID *string            `json:"device_attestation_id"`
	RealmKeyVersion     int32              `json:"realm_key_version"`
	FirstName           string             `json:"first_name"`
	LastName            string             `json:"last_name"`
	Email               string             `json:"email"`
	PasswordHash        string             `json:"password_hash"`
	EmailVerified       bool               `json:"email_verified"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type UserPin struct {
	UserID    string             `json:"user_id"`
	PinHash   string             `json:"pin_hash"`
	Attempts  int32              `json:"attempts"`
	LockedAt  pgtype.Timestamptz `json:"locked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserSession struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	RefreshHash string             `json:"refresh_hash"`
	UserAgent   string             `json:"user_agent"`
	Ip          string             `json:"ip"`
	DeviceID    *string            `json:"device_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
}
