// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpOutboxAttempt = `-- name: BumpOutboxAttempt :exec
UPDATE outbox
SET attempts = attempts + 1,
    next_attempt_at = $2
WHERE id = $1
`

type BumpOutboxAttemptParams struct {
	ID            string             `json:"id"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
}

func (q *Queries) BumpOutboxAttempt(ctx context.Context, arg BumpOutboxAttemptParams) error {
	_, err := q.db.Exec(ctx, bumpOutboxAttempt, arg.ID, arg.NextAttemptAt)
	return err
}

const claimOutboxBatch = `-- name: ClaimOutboxBatch :many
SELECT id, aggregate, aggregate_id, payload, attempts
FROM outbox
WHERE dispatched_at IS NULL AND next_attempt_at <= now()
ORDER BY created_at
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type ClaimOutboxBatchRow struct {
	ID          string `json:"id"`
	Aggregate   string `json:"aggregate"`
	AggregateID string `json:"aggregate_id"`
	Payload     []byte `json:"payload"`
	Attempts    int32  `json:"attempts"`
}

// ClaimOutboxBatch pulls up to $1 ready-to-dispatch rows and locks
// them so competing dispatchers don't double-process. SKIP LOCKED lets
// the dispatcher fan out horizontally without explicit coordination.
func (q *Queries) ClaimOutboxBatch(ctx context.Context, limit int32) ([]ClaimOutboxBatchRow, error) {
	rows, err := q.db.Query(ctx, claimOutboxBatch, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimOutboxBatchRow{}
	for rows.Next() {
		var i ClaimOutboxBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.Aggregate,
			&i.AggregateID,
			&i.Payload,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOutboxEntry = `-- name: InsertOutboxEntry :exec

INSERT INTO outbox (id, aggregate, aggregate_id, payload)
VALUES ($1, $2, $3, $4)
`

type InsertOutboxEntryParams struct {
	ID          string `json:"id"`
	Aggregate   string `json:"aggregate"`
	AggregateID string `json:"aggregate_id"`
	Payload     []byte `json:"payload"`
}

// Transactional outbox for async event dispatch. Writes land in the
// same tx as the aggregate mutation; the dispatcher picks rows up
// with Claim → Mark (on success) / BumpAttempt (on retry) so at-least-
// once delivery is preserved across crashes.
func (q *Queries) InsertOutboxEntry(ctx context.Context, arg InsertOutboxEntryParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEntry,
		arg.ID,
		arg.Aggregate,
		arg.AggregateID,
		arg.Payload,
	)
	return err
}

const markOutboxDispatched = `-- name: MarkOutboxDispatched :exec
UPDATE outbox SET dispatched_at = now() WHERE id = $1
`

func (q *Queries) MarkOutboxDispatched(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markOutboxDispatched, id)
	return err
}
