// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminOverviewStats = `-- name: AdminOverviewStats :one

SELECT
    (SELECT COUNT(*) FROM users)::BIGINT                                                     AS users_total,
    (SELECT COUNT(DISTINCT user_id) FROM devices WHERE last_seen_at > now() - interval '24 hours')::BIGINT AS users_active_24h,
    (SELECT COUNT(DISTINCT user_id) FROM devices WHERE last_seen_at > now() - interval '7 days')::BIGINT   AS users_active_7d,
    (SELECT COUNT(*) FROM devices WHERE active = TRUE)::BIGINT                                AS devices_active,
    COALESCE((SELECT SUM(balance_kobo) FROM accounts WHERE kind = 'lien_holding'), 0)::BIGINT AS lien_float_kobo,
    COALESCE((SELECT SUM(balance_kobo) FROM accounts WHERE kind = 'receiving_pending'), 0)::BIGINT AS pending_settlement_kobo,
    (
        (SELECT COUNT(*) FROM payment_tokens WHERE created_at > now() - interval '24 hours')
      + (SELECT COUNT(*) FROM transfers       WHERE created_at > now() - interval '24 hours')
    )::BIGINT AS txn_count_24h,
    (
        COALESCE((SELECT SUM(amount_kobo) FROM payment_tokens WHERE created_at > now() - interval '24 hours'), 0)
      + COALESCE((SELECT SUM(amount_kobo) FROM transfers       WHERE created_at > now() - interval '24 hours'), 0)
    )::BIGINT AS txn_volume_24h_kobo,
    (SELECT COUNT(*) FROM fraud_signals WHERE created_at > now() - interval '24 hours')::BIGINT AS fraud_signals_24h,
    (SELECT COUNT(*) FROM ceiling_tokens WHERE status = 'ACTIVE')::BIGINT                      AS ceilings_active
`

type AdminOverviewStatsRow struct {
	UsersTotal            int64 `json:"users_total"`
	UsersActive24h        int64 `json:"users_active_24h"`
	UsersActive7d         int64 `json:"users_active_7d"`
	DevicesActive         int64 `json:"devices_active"`
	LienFloatKobo         int64 `json:"lien_float_kobo"`
	PendingSettlementKobo int64 `json:"pending_settlement_kobo"`
	TxnCount24h           int64 `json:"txn_count_24h"`
	TxnVolume24hKobo      int64 `json:"txn_volume_24h_kobo"`
	FraudSignals24h       int64 `json:"fraud_signals_24h"`
	CeilingsActive        int64 `json:"ceilings_active"`
}

// ----------------------------------------------------------------------
// Dashboard aggregates
// ----------------------------------------------------------------------
// AdminOverviewStats is the dashboard landing query — one round trip
// for every tile on the landing page. Column ordering is significant:
// the service maps the result positionally, so additions append rather
// than insert.
//
// txn_count_24h / txn_volume_24h_kobo aggregate BOTH money-movement
// streams (offline payment_tokens + online transfers). Counting only
// one stream would under-report whenever the bulk of activity is on
// the other, which is common early in operation.
func (q *Queries) AdminOverviewStats(ctx context.Context) (AdminOverviewStatsRow, error) {
	row := q.db.QueryRow(ctx, adminOverviewStats)
	var i AdminOverviewStatsRow
	err := row.Scan(
		&i.UsersTotal,
		&i.UsersActive24h,
		&i.UsersActive7d,
		&i.DevicesActive,
		&i.LienFloatKobo,
		&i.PendingSettlementKobo,
		&i.TxnCount24h,
		&i.TxnVolume24hKobo,
		&i.FraudSignals24h,
		&i.CeilingsActive,
	)
	return i, err
}

const adminVolumeSeries = `-- name: AdminVolumeSeries :many
SELECT date_trunc('day', created_at)::timestamptz AS day,
       COUNT(*)::BIGINT                           AS count,
       COALESCE(SUM(amount_kobo), 0)::BIGINT      AS volume_kobo
FROM (
    SELECT amount_kobo, created_at FROM payment_tokens
    WHERE created_at > now() - ($1::int * interval '1 day')
    UNION ALL
    SELECT amount_kobo, created_at FROM transfers
    WHERE created_at > now() - ($1::int * interval '1 day')
) movements
GROUP BY 1
ORDER BY 1
`

type AdminVolumeSeriesRow struct {
	Day        pgtype.Timestamptz `json:"day"`
	Count      int64              `json:"count"`
	VolumeKobo int64              `json:"volume_kobo"`
}

// AdminVolumeSeries returns a per-day count + volume for the last $1
// days, summed across payment_tokens (offline) and transfers (online
// P2P). The inner UNION ALL keeps each row source-attributable so a
// future chart variant can split by stream without a schema change;
// the outer aggregate matches the single-line view the dashboard
// currently renders.
//
// Caller validates the 1..180 range; we multiply the int-day value
// into an interval rather than inline-formatting it.
func (q *Queries) AdminVolumeSeries(ctx context.Context, dollar_1 int32) ([]AdminVolumeSeriesRow, error) {
	rows, err := q.db.Query(ctx, adminVolumeSeries, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminVolumeSeriesRow{}
	for rows.Next() {
		var i AdminVolumeSeriesRow
		if err := rows.Scan(&i.Day, &i.Count, &i.VolumeKobo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countInFlightPaymentsForCeiling = `-- name: CountInFlightPaymentsForCeiling :one
SELECT COUNT(*) FROM payment_tokens
WHERE ceiling_id = $1 AND status IN ('PENDING', 'SUBMITTED')
`

func (q *Queries) CountInFlightPaymentsForCeiling(ctx context.Context, ceilingID string) (int64, error) {
	row := q.db.QueryRow(ctx, countInFlightPaymentsForCeiling, ceilingID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPaymentTokensForAdmin = `-- name: CountPaymentTokensForAdmin :one

SELECT (
    (SELECT COUNT(*) FROM payment_tokens)
  + (SELECT COUNT(*) FROM transfers)
)::BIGINT AS total
`

// Count twins. Each variant shares its WHERE clause with the matching
// List query so the page total is exactly the row count the listing
// would produce.
// CountPaymentTokensForAdmin counts both streams of the unified feed
// (payment_tokens + transfers) so the unfiltered page total matches
// the UNION ALL in ListPaymentTokensForAdmin.
func (q *Queries) CountPaymentTokensForAdmin(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentTokensForAdmin)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countPaymentTokensForAdminByBatch = `-- name: CountPaymentTokensForAdminByBatch :one
SELECT COUNT(*)::BIGINT AS total FROM payment_tokens WHERE settlement_batch_id = $1
`

func (q *Queries) CountPaymentTokensForAdminByBatch(ctx context.Context, settlementBatchID *string) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentTokensForAdminByBatch, settlementBatchID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countPaymentTokensForAdminByPayee = `-- name: CountPaymentTokensForAdminByPayee :one
SELECT COUNT(*)::BIGINT AS total FROM payment_tokens WHERE payee_user_id = $1
`

func (q *Queries) CountPaymentTokensForAdminByPayee(ctx context.Context, payeeUserID string) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentTokensForAdminByPayee, payeeUserID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countPaymentTokensForAdminByPayer = `-- name: CountPaymentTokensForAdminByPayer :one
SELECT COUNT(*)::BIGINT AS total FROM payment_tokens WHERE payer_user_id = $1
`

func (q *Queries) CountPaymentTokensForAdminByPayer(ctx context.Context, payerUserID string) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentTokensForAdminByPayer, payerUserID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countPaymentTokensForAdminByPayerAndPayee = `-- name: CountPaymentTokensForAdminByPayerAndPayee :one
SELECT COUNT(*)::BIGINT AS total FROM payment_tokens
WHERE payer_user_id = $1 AND payee_user_id = $2
`

type CountPaymentTokensForAdminByPayerAndPayeeParams struct {
	PayerUserID string `json:"payer_user_id"`
	PayeeUserID string `json:"payee_user_id"`
}

func (q *Queries) CountPaymentTokensForAdminByPayerAndPayee(ctx context.Context, arg CountPaymentTokensForAdminByPayerAndPayeeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentTokensForAdminByPayerAndPayee, arg.PayerUserID, arg.PayeeUserID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countPaymentTokensForAdminByStatus = `-- name: CountPaymentTokensForAdminByStatus :one
SELECT COUNT(*)::BIGINT AS total FROM payment_tokens WHERE status::text = $1
`

func (q *Queries) CountPaymentTokensForAdminByStatus(ctx context.Context, status PaymentStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentTokensForAdminByStatus, status)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countPaymentTokensForAdminByStatusAndPayee = `-- name: CountPaymentTokensForAdminByStatusAndPayee :one
SELECT COUNT(*)::BIGINT AS total FROM payment_tokens
WHERE status::text = $1 AND payee_user_id = $2
`

type CountPaymentTokensForAdminByStatusAndPayeeParams struct {
	Status      PaymentStatus `json:"status"`
	PayeeUserID string        `json:"payee_user_id"`
}

func (q *Queries) CountPaymentTokensForAdminByStatusAndPayee(ctx context.Context, arg CountPaymentTokensForAdminByStatusAndPayeeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentTokensForAdminByStatusAndPayee, arg.Status, arg.PayeeUserID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countPaymentTokensForAdminByStatusAndPayer = `-- name: CountPaymentTokensForAdminByStatusAndPayer :one
SELECT COUNT(*)::BIGINT AS total FROM payment_tokens
WHERE status::text = $1 AND payer_user_id = $2
`

type CountPaymentTokensForAdminByStatusAndPayerParams struct {
	Status      PaymentStatus `json:"status"`
	PayerUserID string        `json:"payer_user_id"`
}

func (q *Queries) CountPaymentTokensForAdminByStatusAndPayer(ctx context.Context, arg CountPaymentTokensForAdminByStatusAndPayerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentTokensForAdminByStatusAndPayer, arg.Status, arg.PayerUserID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countPaymentTokensForAdminByStatusAndPayerAndPayee = `-- name: CountPaymentTokensForAdminByStatusAndPayerAndPayee :one
SELECT COUNT(*)::BIGINT AS total FROM payment_tokens
WHERE status::text = $1 AND payer_user_id = $2 AND payee_user_id = $3
`

type CountPaymentTokensForAdminByStatusAndPayerAndPayeeParams struct {
	Status      PaymentStatus `json:"status"`
	PayerUserID string        `json:"payer_user_id"`
	PayeeUserID string        `json:"payee_user_id"`
}

func (q *Queries) CountPaymentTokensForAdminByStatusAndPayerAndPayee(ctx context.Context, arg CountPaymentTokensForAdminByStatusAndPayerAndPayeeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentTokensForAdminByStatusAndPayerAndPayee, arg.Status, arg.PayerUserID, arg.PayeeUserID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countSettlementBatches = `-- name: CountSettlementBatches :one

SELECT COUNT(DISTINCT settlement_batch_id)::BIGINT AS total
FROM payment_tokens
WHERE settlement_batch_id IS NOT NULL
`

// ----------------------------------------------------------------------
// Settlement batch rollups
// ----------------------------------------------------------------------
func (q *Queries) CountSettlementBatches(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSettlementBatches)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createPaymentToken = `-- name: CreatePaymentToken :one

INSERT INTO payment_tokens (
    id, ceiling_id, payer_user_id, payee_user_id,
    amount_kobo, sequence_number, remaining_ceiling_kobo,
    signed_at, payer_sig, status,
    session_nonce, request_hash, request_amount_kobo,
    submitted_by_user_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, ceiling_id, payer_user_id, payee_user_id, amount_kobo, sequence_number, remaining_ceiling_kobo, settled_amount_kobo, signed_at, payer_sig, status, rejection_reason, settlement_batch_id, submitted_at, settled_at, created_at, updated_at, session_nonce, request_hash, request_amount_kobo, submitted_by_user_id
`

type CreatePaymentTokenParams struct {
	ID                   string             `json:"id"`
	CeilingID            string             `json:"ceiling_id"`
	PayerUserID          string             `json:"payer_user_id"`
	PayeeUserID          string             `json:"payee_user_id"`
	AmountKobo           int64              `json:"amount_kobo"`
	SequenceNumber       int64              `json:"sequence_number"`
	RemainingCeilingKobo int64              `json:"remaining_ceiling_kobo"`
	SignedAt             pgtype.Timestamptz `json:"signed_at"`
	PayerSig             []byte             `json:"payer_sig"`
	Status               PaymentStatus      `json:"status"`
	SessionNonce         []byte             `json:"session_nonce"`
	RequestHash          []byte             `json:"request_hash"`
	RequestAmountKobo    int64              `json:"request_amount_kobo"`
	SubmittedByUserID    *string            `json:"submitted_by_user_id"`
}

// Payment-token CRUD + lifecycle updates, plus the admin/dashboard
// projections that read across payment_tokens and transfers as one
// unified money-movement feed.
func (q *Queries) CreatePaymentToken(ctx context.Context, arg CreatePaymentTokenParams) (PaymentToken, error) {
	row := q.db.QueryRow(ctx, createPaymentToken,
		arg.ID,
		arg.CeilingID,
		arg.PayerUserID,
		arg.PayeeUserID,
		arg.AmountKobo,
		arg.SequenceNumber,
		arg.RemainingCeilingKobo,
		arg.SignedAt,
		arg.PayerSig,
		arg.Status,
		arg.SessionNonce,
		arg.RequestHash,
		arg.RequestAmountKobo,
		arg.SubmittedByUserID,
	)
	var i PaymentToken
	err := row.Scan(
		&i.ID,
		&i.CeilingID,
		&i.PayerUserID,
		&i.PayeeUserID,
		&i.AmountKobo,
		&i.SequenceNumber,
		&i.RemainingCeilingKobo,
		&i.SettledAmountKobo,
		&i.SignedAt,
		&i.PayerSig,
		&i.Status,
		&i.RejectionReason,
		&i.SettlementBatchID,
		&i.SubmittedAt,
		&i.SettledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionNonce,
		&i.RequestHash,
		&i.RequestAmountKobo,
		&i.SubmittedByUserID,
	)
	return i, err
}

const getPaymentBySequence = `-- name: GetPaymentBySequence :one
SELECT id, ceiling_id, payer_user_id, payee_user_id, amount_kobo, sequence_number, remaining_ceiling_kobo, settled_amount_kobo, signed_at, payer_sig, status, rejection_reason, settlement_batch_id, submitted_at, settled_at, created_at, updated_at, session_nonce, request_hash, request_amount_kobo, submitted_by_user_id FROM payment_tokens
WHERE payer_user_id = $1 AND sequence_number = $2
`

type GetPaymentBySequenceParams struct {
	PayerUserID    string `json:"payer_user_id"`
	SequenceNumber int64  `json:"sequence_number"`
}

func (q *Queries) GetPaymentBySequence(ctx context.Context, arg GetPaymentBySequenceParams) (PaymentToken, error) {
	row := q.db.QueryRow(ctx, getPaymentBySequence, arg.PayerUserID, arg.SequenceNumber)
	var i PaymentToken
	err := row.Scan(
		&i.ID,
		&i.CeilingID,
		&i.PayerUserID,
		&i.PayeeUserID,
		&i.AmountKobo,
		&i.SequenceNumber,
		&i.RemainingCeilingKobo,
		&i.SettledAmountKobo,
		&i.SignedAt,
		&i.PayerSig,
		&i.Status,
		&i.RejectionReason,
		&i.SettlementBatchID,
		&i.SubmittedAt,
		&i.SettledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionNonce,
		&i.RequestHash,
		&i.RequestAmountKobo,
		&i.SubmittedByUserID,
	)
	return i, err
}

const getPaymentToken = `-- name: GetPaymentToken :one
SELECT id, ceiling_id, payer_user_id, payee_user_id, amount_kobo, sequence_number, remaining_ceiling_kobo, settled_amount_kobo, signed_at, payer_sig, status, rejection_reason, settlement_batch_id, submitted_at, settled_at, created_at, updated_at, session_nonce, request_hash, request_amount_kobo, submitted_by_user_id FROM payment_tokens WHERE id = $1
`

func (q *Queries) GetPaymentToken(ctx context.Context, id string) (PaymentToken, error) {
	row := q.db.QueryRow(ctx, getPaymentToken, id)
	var i PaymentToken
	err := row.Scan(
		&i.ID,
		&i.CeilingID,
		&i.PayerUserID,
		&i.PayeeUserID,
		&i.AmountKobo,
		&i.SequenceNumber,
		&i.RemainingCeilingKobo,
		&i.SettledAmountKobo,
		&i.SignedAt,
		&i.PayerSig,
		&i.Status,
		&i.RejectionReason,
		&i.SettlementBatchID,
		&i.SubmittedAt,
		&i.SettledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionNonce,
		&i.RequestHash,
		&i.RequestAmountKobo,
		&i.SubmittedByUserID,
	)
	return i, err
}

const getPaymentTokenForAdmin = `-- name: GetPaymentTokenForAdmin :one
SELECT id, payer_user_id, payee_user_id, amount_kobo, settled_amount_kobo,
       status::text AS status, sequence_number, ceiling_id, settlement_batch_id,
       rejection_reason, created_at, submitted_at, settled_at,
       'payment_token'::text AS kind
FROM payment_tokens
WHERE id = $1
`

type GetPaymentTokenForAdminRow struct {
	ID                string             `json:"id"`
	PayerUserID       string             `json:"payer_user_id"`
	PayeeUserID       string             `json:"payee_user_id"`
	AmountKobo        int64              `json:"amount_kobo"`
	SettledAmountKobo int64              `json:"settled_amount_kobo"`
	Status            string             `json:"status"`
	SequenceNumber    int64              `json:"sequence_number"`
	CeilingID         string             `json:"ceiling_id"`
	SettlementBatchID *string            `json:"settlement_batch_id"`
	RejectionReason   *string            `json:"rejection_reason"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	SettledAt         pgtype.Timestamptz `json:"settled_at"`
	Kind              string             `json:"kind"`
}

// GetPaymentTokenForAdmin is the single-row accessor for the
// transaction-detail endpoint. Column set matches the List variants
// above so the UI renders with one adapter.
func (q *Queries) GetPaymentTokenForAdmin(ctx context.Context, id string) (GetPaymentTokenForAdminRow, error) {
	row := q.db.QueryRow(ctx, getPaymentTokenForAdmin, id)
	var i GetPaymentTokenForAdminRow
	err := row.Scan(
		&i.ID,
		&i.PayerUserID,
		&i.PayeeUserID,
		&i.AmountKobo,
		&i.SettledAmountKobo,
		&i.Status,
		&i.SequenceNumber,
		&i.CeilingID,
		&i.SettlementBatchID,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.SubmittedAt,
		&i.SettledAt,
		&i.Kind,
	)
	return i, err
}

const getSettlementBatchHeader = `-- name: GetSettlementBatchHeader :one
SELECT $1::text                                                 AS id,
       COUNT(*)::BIGINT                                         AS txn_count,
       COALESCE(SUM(amount_kobo), 0)::BIGINT                    AS submitted_volume_kobo,
       COALESCE(SUM(settled_amount_kobo), 0)::BIGINT            AS settled_volume_kobo,
       MIN(submitted_at)::timestamptz                           AS first_submitted_at,
       MAX(settled_at)::timestamptz                             AS last_settled_at
FROM payment_tokens
WHERE settlement_batch_id = $1
`

type GetSettlementBatchHeaderRow struct {
	ID                  string             `json:"id"`
	TxnCount            int64              `json:"txn_count"`
	SubmittedVolumeKobo int64              `json:"submitted_volume_kobo"`
	SettledVolumeKobo   int64              `json:"settled_volume_kobo"`
	FirstSubmittedAt    pgtype.Timestamptz `json:"first_submitted_at"`
	LastSettledAt       pgtype.Timestamptz `json:"last_settled_at"`
}

func (q *Queries) GetSettlementBatchHeader(ctx context.Context, dollar_1 string) (GetSettlementBatchHeaderRow, error) {
	row := q.db.QueryRow(ctx, getSettlementBatchHeader, dollar_1)
	var i GetSettlementBatchHeaderRow
	err := row.Scan(
		&i.ID,
		&i.TxnCount,
		&i.SubmittedVolumeKobo,
		&i.SettledVolumeKobo,
		&i.FirstSubmittedAt,
		&i.LastSettledAt,
	)
	return i, err
}

const getSettlementBatchStatusCounts = `-- name: GetSettlementBatchStatusCounts :many
SELECT status::text AS status,
       COUNT(*)::BIGINT AS count
FROM payment_tokens
WHERE settlement_batch_id = $1
GROUP BY status
`

type GetSettlementBatchStatusCountsRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) GetSettlementBatchStatusCounts(ctx context.Context, settlementBatchID *string) ([]GetSettlementBatchStatusCountsRow, error) {
	rows, err := q.db.Query(ctx, getSettlementBatchStatusCounts, settlementBatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSettlementBatchStatusCountsRow{}
	for rows.Next() {
		var i GetSettlementBatchStatusCountsRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransferForAdmin = `-- name: GetTransferForAdmin :one
SELECT id,
       sender_user_id   AS payer_user_id,
       receiver_user_id AS payee_user_id,
       amount_kobo,
       (CASE WHEN status = 'SETTLED' THEN amount_kobo ELSE 0 END)::BIGINT AS settled_amount_kobo,
       status,
       0::BIGINT        AS sequence_number,
       ''::text         AS ceiling_id,
       NULL::text       AS settlement_batch_id,
       failure_reason   AS rejection_reason,
       created_at,
       NULL::timestamptz AS submitted_at,
       settled_at,
       'transfer'::text AS kind
FROM transfers
WHERE id = $1
`

type GetTransferForAdminRow struct {
	ID                string             `json:"id"`
	PayerUserID       string             `json:"payer_user_id"`
	PayeeUserID       string             `json:"payee_user_id"`
	AmountKobo        int64              `json:"amount_kobo"`
	SettledAmountKobo int64              `json:"settled_amount_kobo"`
	Status            string             `json:"status"`
	SequenceNumber    int64              `json:"sequence_number"`
	CeilingID         string             `json:"ceiling_id"`
	SettlementBatchID *string            `json:"settlement_batch_id"`
	RejectionReason   *string            `json:"rejection_reason"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	SettledAt         pgtype.Timestamptz `json:"settled_at"`
	Kind              string             `json:"kind"`
}

// GetTransferForAdmin is the transfer-detail accessor. Returns the
// same shape as GetPaymentTokenForAdmin so the admin service can
// look up either kind by id and hand the dashboard a uniform row.
func (q *Queries) GetTransferForAdmin(ctx context.Context, id string) (GetTransferForAdminRow, error) {
	row := q.db.QueryRow(ctx, getTransferForAdmin, id)
	var i GetTransferForAdminRow
	err := row.Scan(
		&i.ID,
		&i.PayerUserID,
		&i.PayeeUserID,
		&i.AmountKobo,
		&i.SettledAmountKobo,
		&i.Status,
		&i.SequenceNumber,
		&i.CeilingID,
		&i.SettlementBatchID,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.SubmittedAt,
		&i.SettledAt,
		&i.Kind,
	)
	return i, err
}

const listPayersWithStalePending = `-- name: ListPayersWithStalePending :many
SELECT payer_user_id, MIN(submitted_at) AS first_pending_at
FROM payment_tokens
WHERE status = 'PENDING'
GROUP BY payer_user_id
HAVING MIN(submitted_at) < $1
`

type ListPayersWithStalePendingRow struct {
	PayerUserID    string      `json:"payer_user_id"`
	FirstPendingAt interface{} `json:"first_pending_at"`
}

// Returns distinct payer_user_ids whose oldest PENDING payment is older
// than $1. Used by the auto-settle sweeper.
func (q *Queries) ListPayersWithStalePending(ctx context.Context, submittedAt pgtype.Timestamptz) ([]ListPayersWithStalePendingRow, error) {
	rows, err := q.db.Query(ctx, listPayersWithStalePending, submittedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPayersWithStalePendingRow{}
	for rows.Next() {
		var i ListPayersWithStalePendingRow
		if err := rows.Scan(&i.PayerUserID, &i.FirstPendingAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentTokensForAdmin = `-- name: ListPaymentTokensForAdmin :many

SELECT id, payer_user_id, payee_user_id, amount_kobo, settled_amount_kobo,
       status, sequence_number, ceiling_id, settlement_batch_id,
       rejection_reason, created_at, submitted_at, settled_at, kind
FROM (
    SELECT id, payer_user_id, payee_user_id, amount_kobo, settled_amount_kobo,
           status::text AS status, sequence_number, ceiling_id, settlement_batch_id,
           rejection_reason, created_at, submitted_at, settled_at,
           'payment_token'::text AS kind
    FROM payment_tokens
    UNION ALL
    SELECT id,
           sender_user_id   AS payer_user_id,
           receiver_user_id AS payee_user_id,
           amount_kobo,
           (CASE WHEN status = 'SETTLED' THEN amount_kobo ELSE 0 END)::BIGINT AS settled_amount_kobo,
           status,
           0::BIGINT        AS sequence_number,
           ''::text         AS ceiling_id,
           NULL::text       AS settlement_batch_id,
           failure_reason   AS rejection_reason,
           created_at,
           NULL::timestamptz AS submitted_at,
           settled_at,
           'transfer'::text AS kind
    FROM transfers
) movements
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPaymentTokensForAdminParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPaymentTokensForAdminRow struct {
	ID                string             `json:"id"`
	PayerUserID       string             `json:"payer_user_id"`
	PayeeUserID       string             `json:"payee_user_id"`
	AmountKobo        int64              `json:"amount_kobo"`
	SettledAmountKobo int64              `json:"settled_amount_kobo"`
	Status            string             `json:"status"`
	SequenceNumber    int64              `json:"sequence_number"`
	CeilingID         string             `json:"ceiling_id"`
	SettlementBatchID *string            `json:"settlement_batch_id"`
	RejectionReason   *string            `json:"rejection_reason"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	SettledAt         pgtype.Timestamptz `json:"settled_at"`
	Kind              string             `json:"kind"`
}

// ----------------------------------------------------------------------
// Admin list + count projections for payment_tokens.
//
// The backoffice supports filtering by any combination of {status,
// payer, payee, settlement_batch_id}. Following the codebase's "no
// runtime-built SQL" rule, the eight combinations are spelled out as
// named queries with matching count twins; the service layer dispatches
// on which filter fields are non-empty.
// ----------------------------------------------------------------------
// ListPaymentTokensForAdmin is the unfiltered admin transactions feed:
// UNION-ALL of `payment_tokens` (offline ceiling-backed flow) and
// `transfers` (online P2P flow), normalised to a single row shape
// tagged with `kind` so the UI can distinguish the source.
//
// The filtered variants below stay payment_tokens-only — their
// predicates (payment_status enum, batch_id, sequence_number) don't
// have analogues on the transfers side.
func (q *Queries) ListPaymentTokensForAdmin(ctx context.Context, arg ListPaymentTokensForAdminParams) ([]ListPaymentTokensForAdminRow, error) {
	rows, err := q.db.Query(ctx, listPaymentTokensForAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentTokensForAdminRow{}
	for rows.Next() {
		var i ListPaymentTokensForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.PayerUserID,
			&i.PayeeUserID,
			&i.AmountKobo,
			&i.SettledAmountKobo,
			&i.Status,
			&i.SequenceNumber,
			&i.CeilingID,
			&i.SettlementBatchID,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.SubmittedAt,
			&i.SettledAt,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentTokensForAdminByBatch = `-- name: ListPaymentTokensForAdminByBatch :many
SELECT id, payer_user_id, payee_user_id, amount_kobo, settled_amount_kobo,
       status::text AS status, sequence_number, ceiling_id, settlement_batch_id,
       rejection_reason, created_at, submitted_at, settled_at,
       'payment_token'::text AS kind
FROM payment_tokens
WHERE settlement_batch_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPaymentTokensForAdminByBatchParams struct {
	SettlementBatchID *string `json:"settlement_batch_id"`
	Limit             int32   `json:"limit"`
	Offset            int32   `json:"offset"`
}

type ListPaymentTokensForAdminByBatchRow struct {
	ID                string             `json:"id"`
	PayerUserID       string             `json:"payer_user_id"`
	PayeeUserID       string             `json:"payee_user_id"`
	AmountKobo        int64              `json:"amount_kobo"`
	SettledAmountKobo int64              `json:"settled_amount_kobo"`
	Status            string             `json:"status"`
	SequenceNumber    int64              `json:"sequence_number"`
	CeilingID         string             `json:"ceiling_id"`
	SettlementBatchID *string            `json:"settlement_batch_id"`
	RejectionReason   *string            `json:"rejection_reason"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	SettledAt         pgtype.Timestamptz `json:"settled_at"`
	Kind              string             `json:"kind"`
}

func (q *Queries) ListPaymentTokensForAdminByBatch(ctx context.Context, arg ListPaymentTokensForAdminByBatchParams) ([]ListPaymentTokensForAdminByBatchRow, error) {
	rows, err := q.db.Query(ctx, listPaymentTokensForAdminByBatch, arg.SettlementBatchID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentTokensForAdminByBatchRow{}
	for rows.Next() {
		var i ListPaymentTokensForAdminByBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.PayerUserID,
			&i.PayeeUserID,
			&i.AmountKobo,
			&i.SettledAmountKobo,
			&i.Status,
			&i.SequenceNumber,
			&i.CeilingID,
			&i.SettlementBatchID,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.SubmittedAt,
			&i.SettledAt,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentTokensForAdminByPayee = `-- name: ListPaymentTokensForAdminByPayee :many
SELECT id, payer_user_id, payee_user_id, amount_kobo, settled_amount_kobo,
       status::text AS status, sequence_number, ceiling_id, settlement_batch_id,
       rejection_reason, created_at, submitted_at, settled_at,
       'payment_token'::text AS kind
FROM payment_tokens
WHERE payee_user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPaymentTokensForAdminByPayeeParams struct {
	PayeeUserID string `json:"payee_user_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

type ListPaymentTokensForAdminByPayeeRow struct {
	ID                string             `json:"id"`
	PayerUserID       string             `json:"payer_user_id"`
	PayeeUserID       string             `json:"payee_user_id"`
	AmountKobo        int64              `json:"amount_kobo"`
	SettledAmountKobo int64              `json:"settled_amount_kobo"`
	Status            string             `json:"status"`
	SequenceNumber    int64              `json:"sequence_number"`
	CeilingID         string             `json:"ceiling_id"`
	SettlementBatchID *string            `json:"settlement_batch_id"`
	RejectionReason   *string            `json:"rejection_reason"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	SettledAt         pgtype.Timestamptz `json:"settled_at"`
	Kind              string             `json:"kind"`
}

func (q *Queries) ListPaymentTokensForAdminByPayee(ctx context.Context, arg ListPaymentTokensForAdminByPayeeParams) ([]ListPaymentTokensForAdminByPayeeRow, error) {
	rows, err := q.db.Query(ctx, listPaymentTokensForAdminByPayee, arg.PayeeUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentTokensForAdminByPayeeRow{}
	for rows.Next() {
		var i ListPaymentTokensForAdminByPayeeRow
		if err := rows.Scan(
			&i.ID,
			&i.PayerUserID,
			&i.PayeeUserID,
			&i.AmountKobo,
			&i.SettledAmountKobo,
			&i.Status,
			&i.SequenceNumber,
			&i.CeilingID,
			&i.SettlementBatchID,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.SubmittedAt,
			&i.SettledAt,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentTokensForAdminByPayer = `-- name: ListPaymentTokensForAdminByPayer :many
SELECT id, payer_user_id, payee_user_id, amount_kobo, settled_amount_kobo,
       status::text AS status, sequence_number, ceiling_id, settlement_batch_id,
       rejection_reason, created_at, submitted_at, settled_at,
       'payment_token'::text AS kind
FROM payment_tokens
WHERE payer_user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPaymentTokensForAdminByPayerParams struct {
	PayerUserID string `json:"payer_user_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

type ListPaymentTokensForAdminByPayerRow struct {
	ID                string             `json:"id"`
	PayerUserID       string             `json:"payer_user_id"`
	PayeeUserID       string             `json:"payee_user_id"`
	AmountKobo        int64              `json:"amount_kobo"`
	SettledAmountKobo int64              `json:"settled_amount_kobo"`
	Status            string             `json:"status"`
	SequenceNumber    int64              `json:"sequence_number"`
	CeilingID         string             `json:"ceiling_id"`
	SettlementBatchID *string            `json:"settlement_batch_id"`
	RejectionReason   *string            `json:"rejection_reason"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	SettledAt         pgtype.Timestamptz `json:"settled_at"`
	Kind              string             `json:"kind"`
}

func (q *Queries) ListPaymentTokensForAdminByPayer(ctx context.Context, arg ListPaymentTokensForAdminByPayerParams) ([]ListPaymentTokensForAdminByPayerRow, error) {
	rows, err := q.db.Query(ctx, listPaymentTokensForAdminByPayer, arg.PayerUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentTokensForAdminByPayerRow{}
	for rows.Next() {
		var i ListPaymentTokensForAdminByPayerRow
		if err := rows.Scan(
			&i.ID,
			&i.PayerUserID,
			&i.PayeeUserID,
			&i.AmountKobo,
			&i.SettledAmountKobo,
			&i.Status,
			&i.SequenceNumber,
			&i.CeilingID,
			&i.SettlementBatchID,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.SubmittedAt,
			&i.SettledAt,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentTokensForAdminByPayerAndPayee = `-- name: ListPaymentTokensForAdminByPayerAndPayee :many
SELECT id, payer_user_id, payee_user_id, amount_kobo, settled_amount_kobo,
       status::text AS status, sequence_number, ceiling_id, settlement_batch_id,
       rejection_reason, created_at, submitted_at, settled_at,
       'payment_token'::text AS kind
FROM payment_tokens
WHERE payer_user_id = $1 AND payee_user_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListPaymentTokensForAdminByPayerAndPayeeParams struct {
	PayerUserID string `json:"payer_user_id"`
	PayeeUserID string `json:"payee_user_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

type ListPaymentTokensForAdminByPayerAndPayeeRow struct {
	ID                string             `json:"id"`
	PayerUserID       string             `json:"payer_user_id"`
	PayeeUserID       string             `json:"payee_user_id"`
	AmountKobo        int64              `json:"amount_kobo"`
	SettledAmountKobo int64              `json:"settled_amount_kobo"`
	Status            string             `json:"status"`
	SequenceNumber    int64              `json:"sequence_number"`
	CeilingID         string             `json:"ceiling_id"`
	SettlementBatchID *string            `json:"settlement_batch_id"`
	RejectionReason   *string            `json:"rejection_reason"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	SettledAt         pgtype.Timestamptz `json:"settled_at"`
	Kind              string             `json:"kind"`
}

func (q *Queries) ListPaymentTokensForAdminByPayerAndPayee(ctx context.Context, arg ListPaymentTokensForAdminByPayerAndPayeeParams) ([]ListPaymentTokensForAdminByPayerAndPayeeRow, error) {
	rows, err := q.db.Query(ctx, listPaymentTokensForAdminByPayerAndPayee,
		arg.PayerUserID,
		arg.PayeeUserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentTokensForAdminByPayerAndPayeeRow{}
	for rows.Next() {
		var i ListPaymentTokensForAdminByPayerAndPayeeRow
		if err := rows.Scan(
			&i.ID,
			&i.PayerUserID,
			&i.PayeeUserID,
			&i.AmountKobo,
			&i.SettledAmountKobo,
			&i.Status,
			&i.SequenceNumber,
			&i.CeilingID,
			&i.SettlementBatchID,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.SubmittedAt,
			&i.SettledAt,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentTokensForAdminByStatus = `-- name: ListPaymentTokensForAdminByStatus :many
SELECT id, payer_user_id, payee_user_id, amount_kobo, settled_amount_kobo,
       status::text AS status, sequence_number, ceiling_id, settlement_batch_id,
       rejection_reason, created_at, submitted_at, settled_at,
       'payment_token'::text AS kind
FROM payment_tokens
WHERE status::text = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPaymentTokensForAdminByStatusParams struct {
	Status PaymentStatus `json:"status"`
	Limit  int32         `json:"limit"`
	Offset int32         `json:"offset"`
}

type ListPaymentTokensForAdminByStatusRow struct {
	ID                string             `json:"id"`
	PayerUserID       string             `json:"payer_user_id"`
	PayeeUserID       string             `json:"payee_user_id"`
	AmountKobo        int64              `json:"amount_kobo"`
	SettledAmountKobo int64              `json:"settled_amount_kobo"`
	Status            string             `json:"status"`
	SequenceNumber    int64              `json:"sequence_number"`
	CeilingID         string             `json:"ceiling_id"`
	SettlementBatchID *string            `json:"settlement_batch_id"`
	RejectionReason   *string            `json:"rejection_reason"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	SettledAt         pgtype.Timestamptz `json:"settled_at"`
	Kind              string             `json:"kind"`
}

func (q *Queries) ListPaymentTokensForAdminByStatus(ctx context.Context, arg ListPaymentTokensForAdminByStatusParams) ([]ListPaymentTokensForAdminByStatusRow, error) {
	rows, err := q.db.Query(ctx, listPaymentTokensForAdminByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentTokensForAdminByStatusRow{}
	for rows.Next() {
		var i ListPaymentTokensForAdminByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.PayerUserID,
			&i.PayeeUserID,
			&i.AmountKobo,
			&i.SettledAmountKobo,
			&i.Status,
			&i.SequenceNumber,
			&i.CeilingID,
			&i.SettlementBatchID,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.SubmittedAt,
			&i.SettledAt,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentTokensForAdminByStatusAndPayee = `-- name: ListPaymentTokensForAdminByStatusAndPayee :many
SELECT id, payer_user_id, payee_user_id, amount_kobo, settled_amount_kobo,
       status::text AS status, sequence_number, ceiling_id, settlement_batch_id,
       rejection_reason, created_at, submitted_at, settled_at,
       'payment_token'::text AS kind
FROM payment_tokens
WHERE status::text = $1 AND payee_user_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListPaymentTokensForAdminByStatusAndPayeeParams struct {
	Status      PaymentStatus `json:"status"`
	PayeeUserID string        `json:"payee_user_id"`
	Limit       int32         `json:"limit"`
	Offset      int32         `json:"offset"`
}

type ListPaymentTokensForAdminByStatusAndPayeeRow struct {
	ID                string             `json:"id"`
	PayerUserID       string             `json:"payer_user_id"`
	PayeeUserID       string             `json:"payee_user_id"`
	AmountKobo        int64              `json:"amount_kobo"`
	SettledAmountKobo int64              `json:"settled_amount_kobo"`
	Status            string             `json:"status"`
	SequenceNumber    int64              `json:"sequence_number"`
	CeilingID         string             `json:"ceiling_id"`
	SettlementBatchID *string            `json:"settlement_batch_id"`
	RejectionReason   *string            `json:"rejection_reason"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	SettledAt         pgtype.Timestamptz `json:"settled_at"`
	Kind              string             `json:"kind"`
}

func (q *Queries) ListPaymentTokensForAdminByStatusAndPayee(ctx context.Context, arg ListPaymentTokensForAdminByStatusAndPayeeParams) ([]ListPaymentTokensForAdminByStatusAndPayeeRow, error) {
	rows, err := q.db.Query(ctx, listPaymentTokensForAdminByStatusAndPayee,
		arg.Status,
		arg.PayeeUserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentTokensForAdminByStatusAndPayeeRow{}
	for rows.Next() {
		var i ListPaymentTokensForAdminByStatusAndPayeeRow
		if err := rows.Scan(
			&i.ID,
			&i.PayerUserID,
			&i.PayeeUserID,
			&i.AmountKobo,
			&i.SettledAmountKobo,
			&i.Status,
			&i.SequenceNumber,
			&i.CeilingID,
			&i.SettlementBatchID,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.SubmittedAt,
			&i.SettledAt,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentTokensForAdminByStatusAndPayer = `-- name: ListPaymentTokensForAdminByStatusAndPayer :many
SELECT id, payer_user_id, payee_user_id, amount_kobo, settled_amount_kobo,
       status::text AS status, sequence_number, ceiling_id, settlement_batch_id,
       rejection_reason, created_at, submitted_at, settled_at,
       'payment_token'::text AS kind
FROM payment_tokens
WHERE status::text = $1 AND payer_user_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListPaymentTokensForAdminByStatusAndPayerParams struct {
	Status      PaymentStatus `json:"status"`
	PayerUserID string        `json:"payer_user_id"`
	Limit       int32         `json:"limit"`
	Offset      int32         `json:"offset"`
}

type ListPaymentTokensForAdminByStatusAndPayerRow struct {
	ID                string             `json:"id"`
	PayerUserID       string             `json:"payer_user_id"`
	PayeeUserID       string             `json:"payee_user_id"`
	AmountKobo        int64              `json:"amount_kobo"`
	SettledAmountKobo int64              `json:"settled_amount_kobo"`
	Status            string             `json:"status"`
	SequenceNumber    int64              `json:"sequence_number"`
	CeilingID         string             `json:"ceiling_id"`
	SettlementBatchID *string            `json:"settlement_batch_id"`
	RejectionReason   *string            `json:"rejection_reason"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	SettledAt         pgtype.Timestamptz `json:"settled_at"`
	Kind              string             `json:"kind"`
}

func (q *Queries) ListPaymentTokensForAdminByStatusAndPayer(ctx context.Context, arg ListPaymentTokensForAdminByStatusAndPayerParams) ([]ListPaymentTokensForAdminByStatusAndPayerRow, error) {
	rows, err := q.db.Query(ctx, listPaymentTokensForAdminByStatusAndPayer,
		arg.Status,
		arg.PayerUserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentTokensForAdminByStatusAndPayerRow{}
	for rows.Next() {
		var i ListPaymentTokensForAdminByStatusAndPayerRow
		if err := rows.Scan(
			&i.ID,
			&i.PayerUserID,
			&i.PayeeUserID,
			&i.AmountKobo,
			&i.SettledAmountKobo,
			&i.Status,
			&i.SequenceNumber,
			&i.CeilingID,
			&i.SettlementBatchID,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.SubmittedAt,
			&i.SettledAt,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentTokensForAdminByStatusAndPayerAndPayee = `-- name: ListPaymentTokensForAdminByStatusAndPayerAndPayee :many
SELECT id, payer_user_id, payee_user_id, amount_kobo, settled_amount_kobo,
       status::text AS status, sequence_number, ceiling_id, settlement_batch_id,
       rejection_reason, created_at, submitted_at, settled_at,
       'payment_token'::text AS kind
FROM payment_tokens
WHERE status::text = $1 AND payer_user_id = $2 AND payee_user_id = $3
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListPaymentTokensForAdminByStatusAndPayerAndPayeeParams struct {
	Status      PaymentStatus `json:"status"`
	PayerUserID string        `json:"payer_user_id"`
	PayeeUserID string        `json:"payee_user_id"`
	Limit       int32         `json:"limit"`
	Offset      int32         `json:"offset"`
}

type ListPaymentTokensForAdminByStatusAndPayerAndPayeeRow struct {
	ID                string             `json:"id"`
	PayerUserID       string             `json:"payer_user_id"`
	PayeeUserID       string             `json:"payee_user_id"`
	AmountKobo        int64              `json:"amount_kobo"`
	SettledAmountKobo int64              `json:"settled_amount_kobo"`
	Status            string             `json:"status"`
	SequenceNumber    int64              `json:"sequence_number"`
	CeilingID         string             `json:"ceiling_id"`
	SettlementBatchID *string            `json:"settlement_batch_id"`
	RejectionReason   *string            `json:"rejection_reason"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	SettledAt         pgtype.Timestamptz `json:"settled_at"`
	Kind              string             `json:"kind"`
}

func (q *Queries) ListPaymentTokensForAdminByStatusAndPayerAndPayee(ctx context.Context, arg ListPaymentTokensForAdminByStatusAndPayerAndPayeeParams) ([]ListPaymentTokensForAdminByStatusAndPayerAndPayeeRow, error) {
	rows, err := q.db.Query(ctx, listPaymentTokensForAdminByStatusAndPayerAndPayee,
		arg.Status,
		arg.PayerUserID,
		arg.PayeeUserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentTokensForAdminByStatusAndPayerAndPayeeRow{}
	for rows.Next() {
		var i ListPaymentTokensForAdminByStatusAndPayerAndPayeeRow
		if err := rows.Scan(
			&i.ID,
			&i.PayerUserID,
			&i.PayeeUserID,
			&i.AmountKobo,
			&i.SettledAmountKobo,
			&i.Status,
			&i.SequenceNumber,
			&i.CeilingID,
			&i.SettlementBatchID,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.SubmittedAt,
			&i.SettledAt,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByPayee = `-- name: ListPaymentsByPayee :many
SELECT id, ceiling_id, payer_user_id, payee_user_id, amount_kobo, sequence_number, remaining_ceiling_kobo, settled_amount_kobo, signed_at, payer_sig, status, rejection_reason, settlement_batch_id, submitted_at, settled_at, created_at, updated_at, session_nonce, request_hash, request_amount_kobo, submitted_by_user_id FROM payment_tokens
WHERE payee_user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPaymentsByPayee(ctx context.Context, payeeUserID string) ([]PaymentToken, error) {
	rows, err := q.db.Query(ctx, listPaymentsByPayee, payeeUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentToken{}
	for rows.Next() {
		var i PaymentToken
		if err := rows.Scan(
			&i.ID,
			&i.CeilingID,
			&i.PayerUserID,
			&i.PayeeUserID,
			&i.AmountKobo,
			&i.SequenceNumber,
			&i.RemainingCeilingKobo,
			&i.SettledAmountKobo,
			&i.SignedAt,
			&i.PayerSig,
			&i.Status,
			&i.RejectionReason,
			&i.SettlementBatchID,
			&i.SubmittedAt,
			&i.SettledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SessionNonce,
			&i.RequestHash,
			&i.RequestAmountKobo,
			&i.SubmittedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByPayer = `-- name: ListPaymentsByPayer :many
SELECT id, ceiling_id, payer_user_id, payee_user_id, amount_kobo, sequence_number, remaining_ceiling_kobo, settled_amount_kobo, signed_at, payer_sig, status, rejection_reason, settlement_batch_id, submitted_at, settled_at, created_at, updated_at, session_nonce, request_hash, request_amount_kobo, submitted_by_user_id FROM payment_tokens
WHERE payer_user_id = $1
ORDER BY sequence_number ASC
`

func (q *Queries) ListPaymentsByPayer(ctx context.Context, payerUserID string) ([]PaymentToken, error) {
	rows, err := q.db.Query(ctx, listPaymentsByPayer, payerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentToken{}
	for rows.Next() {
		var i PaymentToken
		if err := rows.Scan(
			&i.ID,
			&i.CeilingID,
			&i.PayerUserID,
			&i.PayeeUserID,
			&i.AmountKobo,
			&i.SequenceNumber,
			&i.RemainingCeilingKobo,
			&i.SettledAmountKobo,
			&i.SignedAt,
			&i.PayerSig,
			&i.Status,
			&i.RejectionReason,
			&i.SettlementBatchID,
			&i.SubmittedAt,
			&i.SettledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SessionNonce,
			&i.RequestHash,
			&i.RequestAmountKobo,
			&i.SubmittedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingPaymentsByPayer = `-- name: ListPendingPaymentsByPayer :many
SELECT id, ceiling_id, payer_user_id, payee_user_id, amount_kobo, sequence_number, remaining_ceiling_kobo, settled_amount_kobo, signed_at, payer_sig, status, rejection_reason, settlement_batch_id, submitted_at, settled_at, created_at, updated_at, session_nonce, request_hash, request_amount_kobo, submitted_by_user_id FROM payment_tokens
WHERE payer_user_id = $1 AND status = 'PENDING'
ORDER BY sequence_number ASC
`

func (q *Queries) ListPendingPaymentsByPayer(ctx context.Context, payerUserID string) ([]PaymentToken, error) {
	rows, err := q.db.Query(ctx, listPendingPaymentsByPayer, payerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentToken{}
	for rows.Next() {
		var i PaymentToken
		if err := rows.Scan(
			&i.ID,
			&i.CeilingID,
			&i.PayerUserID,
			&i.PayeeUserID,
			&i.AmountKobo,
			&i.SequenceNumber,
			&i.RemainingCeilingKobo,
			&i.SettledAmountKobo,
			&i.SignedAt,
			&i.PayerSig,
			&i.Status,
			&i.RejectionReason,
			&i.SettlementBatchID,
			&i.SubmittedAt,
			&i.SettledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SessionNonce,
			&i.RequestHash,
			&i.RequestAmountKobo,
			&i.SubmittedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettlementBatches = `-- name: ListSettlementBatches :many
SELECT settlement_batch_id                                      AS id,
       COUNT(*)::BIGINT                                         AS txn_count,
       COALESCE(SUM(amount_kobo), 0)::BIGINT                    AS submitted_volume_kobo,
       COALESCE(SUM(settled_amount_kobo), 0)::BIGINT            AS settled_volume_kobo,
       MIN(submitted_at)::timestamptz                           AS first_submitted_at,
       MAX(settled_at)::timestamptz                             AS last_settled_at
FROM payment_tokens
WHERE settlement_batch_id IS NOT NULL
GROUP BY settlement_batch_id
ORDER BY MAX(COALESCE(settled_at, submitted_at, created_at)) DESC NULLS LAST
LIMIT $1 OFFSET $2
`

type ListSettlementBatchesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListSettlementBatchesRow struct {
	ID                  *string            `json:"id"`
	TxnCount            int64              `json:"txn_count"`
	SubmittedVolumeKobo int64              `json:"submitted_volume_kobo"`
	SettledVolumeKobo   int64              `json:"settled_volume_kobo"`
	FirstSubmittedAt    pgtype.Timestamptz `json:"first_submitted_at"`
	LastSettledAt       pgtype.Timestamptz `json:"last_settled_at"`
}

func (q *Queries) ListSettlementBatches(ctx context.Context, arg ListSettlementBatchesParams) ([]ListSettlementBatchesRow, error) {
	rows, err := q.db.Query(ctx, listSettlementBatches, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSettlementBatchesRow{}
	for rows.Next() {
		var i ListSettlementBatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.TxnCount,
			&i.SubmittedVolumeKobo,
			&i.SettledVolumeKobo,
			&i.FirstSubmittedAt,
			&i.LastSettledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payment_tokens
SET status = $2,
    rejection_reason = $3,
    settled_amount_kobo = $4,
    settlement_batch_id = $5,
    submitted_at = COALESCE(submitted_at, $6),
    settled_at = $7,
    updated_at = now()
WHERE id = $1
RETURNING id, ceiling_id, payer_user_id, payee_user_id, amount_kobo, sequence_number, remaining_ceiling_kobo, settled_amount_kobo, signed_at, payer_sig, status, rejection_reason, settlement_batch_id, submitted_at, settled_at, created_at, updated_at, session_nonce, request_hash, request_amount_kobo, submitted_by_user_id
`

type UpdatePaymentStatusParams struct {
	ID                string             `json:"id"`
	Status            PaymentStatus      `json:"status"`
	RejectionReason   *string            `json:"rejection_reason"`
	SettledAmountKobo int64              `json:"settled_amount_kobo"`
	SettlementBatchID *string            `json:"settlement_batch_id"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	SettledAt         pgtype.Timestamptz `json:"settled_at"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (PaymentToken, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus,
		arg.ID,
		arg.Status,
		arg.RejectionReason,
		arg.SettledAmountKobo,
		arg.SettlementBatchID,
		arg.SubmittedAt,
		arg.SettledAt,
	)
	var i PaymentToken
	err := row.Scan(
		&i.ID,
		&i.CeilingID,
		&i.PayerUserID,
		&i.PayeeUserID,
		&i.AmountKobo,
		&i.SequenceNumber,
		&i.RemainingCeilingKobo,
		&i.SettledAmountKobo,
		&i.SignedAt,
		&i.PayerSig,
		&i.Status,
		&i.RejectionReason,
		&i.SettlementBatchID,
		&i.SubmittedAt,
		&i.SettledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionNonce,
		&i.RequestHash,
		&i.RequestAmountKobo,
		&i.SubmittedByUserID,
	)
	return i, err
}
