// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: processed_events.sql

package sqlcgen

import (
	"context"
)

const isEventProcessed = `-- name: IsEventProcessed :one
SELECT EXISTS (SELECT 1 FROM processed_events WHERE outbox_id = $1) AS exists
`

func (q *Queries) IsEventProcessed(ctx context.Context, outboxID string) (bool, error) {
	row := q.db.QueryRow(ctx, isEventProcessed, outboxID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const markEventProcessed = `-- name: MarkEventProcessed :exec

INSERT INTO processed_events (outbox_id, status)
VALUES ($1, $2)
ON CONFLICT (outbox_id) DO NOTHING
`

type MarkEventProcessedParams struct {
	OutboxID string `json:"outbox_id"`
	Status   string `json:"status"`
}

// Idempotency table for outbox event processing. The processor writes
// one row per handled event; the check-before-apply step makes handler
// execution at-most-once even under dispatcher retries.
func (q *Queries) MarkEventProcessed(ctx context.Context, arg MarkEventProcessedParams) error {
	_, err := q.db.Exec(ctx, markEventProcessed, arg.OutboxID, arg.Status)
	return err
}
