// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: push_tokens.sql

package sqlcgen

import (
	"context"
)

const deletePushToken = `-- name: DeletePushToken :exec
DELETE FROM push_tokens
WHERE fcm_token = $1
  AND user_id = $2
`

type DeletePushTokenParams struct {
	FcmToken string `json:"fcm_token"`
	UserID   string `json:"user_id"`
}

func (q *Queries) DeletePushToken(ctx context.Context, arg DeletePushTokenParams) error {
	_, err := q.db.Exec(ctx, deletePushToken, arg.FcmToken, arg.UserID)
	return err
}

const deletePushTokenByValue = `-- name: DeletePushTokenByValue :exec
DELETE FROM push_tokens WHERE fcm_token = $1
`

func (q *Queries) DeletePushTokenByValue(ctx context.Context, fcmToken string) error {
	_, err := q.db.Exec(ctx, deletePushTokenByValue, fcmToken)
	return err
}

const listPushTokensForUser = `-- name: ListPushTokensForUser :many
SELECT fcm_token, platform
FROM push_tokens
WHERE user_id = $1
ORDER BY updated_at DESC
`

type ListPushTokensForUserRow struct {
	FcmToken string `json:"fcm_token"`
	Platform string `json:"platform"`
}

func (q *Queries) ListPushTokensForUser(ctx context.Context, userID string) ([]ListPushTokensForUserRow, error) {
	rows, err := q.db.Query(ctx, listPushTokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPushTokensForUserRow{}
	for rows.Next() {
		var i ListPushTokensForUserRow
		if err := rows.Scan(&i.FcmToken, &i.Platform); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPushToken = `-- name: UpsertPushToken :exec

INSERT INTO push_tokens (fcm_token, user_id, platform)
VALUES ($1, $2, $3)
ON CONFLICT (fcm_token) DO UPDATE
    SET user_id    = EXCLUDED.user_id,
        platform   = EXCLUDED.platform,
        updated_at = now()
`

type UpsertPushTokenParams struct {
	FcmToken string `json:"fcm_token"`
	UserID   string `json:"user_id"`
	Platform string `json:"platform"`
}

// FCM push-token registry. The upsert-on-register pattern reassigns
// ownership when the same token lands on a new user (device swaps,
// factory reset, multi-account). Logout deletes the row.
func (q *Queries) UpsertPushToken(ctx context.Context, arg UpsertPushTokenParams) error {
	_, err := q.db.Exec(ctx, upsertPushToken, arg.FcmToken, arg.UserID, arg.Platform)
	return err
}
