// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AccountLedgerSum(ctx context.Context, accountID string) (AccountLedgerSumRow, error)
	// ----------------------------------------------------------------------
	// Dashboard aggregates
	// ----------------------------------------------------------------------
	// AdminOverviewStats is the dashboard landing query — one round trip
	// for every tile on the landing page. Column ordering is significant:
	// the service maps the result positionally, so additions append rather
	// than insert.
	//
	// txn_count_24h / txn_volume_24h_kobo aggregate BOTH money-movement
	// streams (offline payment_tokens + online transfers). Counting only
	// one stream would under-report whenever the bulk of activity is on
	// the other, which is common early in operation.
	//
	AdminOverviewStats(ctx context.Context) (AdminOverviewStatsRow, error)
	// AdminVolumeSeries returns a per-day count + volume for the last $1
	// days, summed across payment_tokens (offline) and transfers (online
	// P2P). The inner UNION ALL keeps each row source-attributable so a
	// future chart variant can split by stream without a schema change;
	// the outer aggregate matches the single-line view the dashboard
	// currently renders.
	//
	// Caller validates the 1..180 range; we multiply the int-day value
	// into an interval rather than inline-formatting it.
	//
	AdminVolumeSeries(ctx context.Context, dollar_1 int32) ([]AdminVolumeSeriesRow, error)
	BumpOutboxAttempt(ctx context.Context, arg BumpOutboxAttemptParams) error
	// BumpPINAttempts records a mismatch below the lockout threshold.
	//
	BumpPINAttempts(ctx context.Context, arg BumpPINAttemptsParams) error
	// CheckAccountNumberExists powers /v1/accounts/resolve — returns the
	// account_number if the row exists so the caller can confirm a
	// receiver before committing to a transfer.
	//
	CheckAccountNumberExists(ctx context.Context, accountNumber string) (string, error)
	// ClaimOutboxBatch pulls up to $1 ready-to-dispatch rows and locks
	// them so competing dispatchers don't double-process. SKIP LOCKED lets
	// the dispatcher fan out horizontally without explicit coordination.
	//
	ClaimOutboxBatch(ctx context.Context, limit int32) ([]ClaimOutboxBatchRow, error)
	// ClearUserPINAttempts zeros the counter on a successful verify. The
	// guard in the WHERE clause skips the write when the row is already
	// clean, avoiding an unnecessary heap touch on every login.
	//
	ClearUserPINAttempts(ctx context.Context, userID string) error
	ConsumeOTPChallenge(ctx context.Context, arg ConsumeOTPChallengeParams) error
	CountAdminAuditLog(ctx context.Context) (int64, error)
	CountFraudSignalsByUser(ctx context.Context, userID string) (int64, error)
	CountFraudSignalsGlobal(ctx context.Context) (int64, error)
	CountInFlightPaymentsForCeiling(ctx context.Context, ceilingID string) (int64, error)
	// Count twins. Each variant shares its WHERE clause with the matching
	// List query so the page total is exactly the row count the listing
	// would produce.
	// CountPaymentTokensForAdmin counts both streams of the unified feed
	// (payment_tokens + transfers) so the unfiltered page total matches
	// the UNION ALL in ListPaymentTokensForAdmin.
	//
	CountPaymentTokensForAdmin(ctx context.Context) (int64, error)
	CountPaymentTokensForAdminByBatch(ctx context.Context, settlementBatchID *string) (int64, error)
	CountPaymentTokensForAdminByPayee(ctx context.Context, payeeUserID string) (int64, error)
	CountPaymentTokensForAdminByPayer(ctx context.Context, payerUserID string) (int64, error)
	CountPaymentTokensForAdminByPayerAndPayee(ctx context.Context, arg CountPaymentTokensForAdminByPayerAndPayeeParams) (int64, error)
	CountPaymentTokensForAdminByStatus(ctx context.Context, status PaymentStatus) (int64, error)
	CountPaymentTokensForAdminByStatusAndPayee(ctx context.Context, arg CountPaymentTokensForAdminByStatusAndPayeeParams) (int64, error)
	CountPaymentTokensForAdminByStatusAndPayer(ctx context.Context, arg CountPaymentTokensForAdminByStatusAndPayerParams) (int64, error)
	CountPaymentTokensForAdminByStatusAndPayerAndPayee(ctx context.Context, arg CountPaymentTokensForAdminByStatusAndPayerAndPayeeParams) (int64, error)
	// CountRecentTransfersBySender counts transfers from one sender inside
	// a trailing time window, short-circuiting at $3 so velocity rules
	// stop scanning at threshold+1. Drives the fraud scorer's 1m and 1h
	// velocity rules; the caller passes the window as a Postgres interval
	// text (e.g. '60 seconds', '1 hour').
	//
	CountRecentTransfersBySender(ctx context.Context, arg CountRecentTransfersBySenderParams) (int64, error)
	// ----------------------------------------------------------------------
	// Settlement batch rollups
	// ----------------------------------------------------------------------
	CountSettlementBatches(ctx context.Context) (int64, error)
	CountTransactionsForUser(ctx context.Context, userID string) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountUsersByPhone(ctx context.Context, phone string) (int64, error)
	// Account CRUD + balance mutators. The ledger layer owns all writes to
	// balance_kobo via the Increment/Decrement helpers so the account row
	// and its ledger entries always move together inside one tx.
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	// Admin refresh-session storage. Login creates a session; rotation
	// inserts the replacement row and revokes the predecessor in one tx;
	// logout revokes by hash.
	// CreateAdminSession records a freshly issued refresh token at login.
	// user_agent + ip are captured for audit/session-list rendering.
	//
	CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) error
	// CreateAdminSessionRotation records a post-refresh replacement
	// session. user_agent + ip are not re-captured on rotation; the
	// columns default to '' at the DB level.
	//
	CreateAdminSessionRotation(ctx context.Context, arg CreateAdminSessionRotationParams) error
	// Admin user + role queries for the backoffice. admin_users is the
	// internal-staff identity table — distinct from the end-user `users`
	// table and its auth surface in user_auth.sql. Session and audit
	// queries live in admin_sessions.sql / admin_audit.sql respectively.
	// CreateAdminUser inserts a bcrypt-hashed admin user. Role grants are
	// applied separately via GrantAdminRoleByName so the admin-create
	// service can iterate over a caller-supplied role slice.
	//
	CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) error
	// Bank-side Ed25519 signing keys. Rotation is "insert new, retire old";
	// historical ceilings verify against the snapshotted pubkey stored in
	// ceiling_tokens.payer_pubkey rather than the live row here.
	CreateBankSigningKey(ctx context.Context, arg CreateBankSigningKeyParams) (BankSigningKey, error)
	// Ceiling-token CRUD + lifecycle transitions. Ceilings drive the
	// offline-spending authorisation budget; each payer can have at most
	// one live (ACTIVE or RECOVERY_PENDING) ceiling at a time.
	CreateCeilingToken(ctx context.Context, arg CreateCeilingTokenParams) (CeilingToken, error)
	// Device registry. One active device per user is enforced at the
	// schema level (partial unique index); these queries own the lifecycle
	// (register, touch, deactivate) plus the admin read surface.
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	// Payment-token CRUD + lifecycle updates, plus the admin/dashboard
	// projections that read across payment_tokens and transfers as one
	// unified money-movement feed.
	CreatePaymentToken(ctx context.Context, arg CreatePaymentTokenParams) (PaymentToken, error)
	// Realm key (Layer 1 AES-256 QR encryption) lifecycle. Rotation mints
	// a new version, retires the prior one with a grace-window overlap,
	// and GCs anything past its overlap. QRs sealed under a GC'd version
	// are accepted as undecryptable — the grace window is the design.
	CreateRealmKey(ctx context.Context, arg CreateRealmKeyParams) (RealmKey, error)
	// Reconciliation run history + the read queries that back each
	// reconciler. Three reconcilers drive off this file:
	//   PAYER     — per-user offline-settled payment mismatch scan.
	//   MERCHANT  — per-receiver settlement-batch roll-up.
	//   LEDGER    — global account-balance vs ledger-sum check.
	CreateReconciliationRun(ctx context.Context, arg CreateReconciliationRunParams) (ReconciliationRun, error)
	// Online intra-bank P2P transfers. Two parallel accept-insert forms:
	// one for paths that don't fraud-score (tests, internal tooling) and
	// one that captures the fraud decision. Projection reads (the suffix
	// `Projection` variants) omit the `flagged` column so the BFF surface
	// doesn't leak the internal fraud flag to the user-facing client.
	CreateTransferAccepted(ctx context.Context, arg CreateTransferAcceptedParams) (Transfer, error)
	// CreateTransferAcceptedFlagged is the accept-path insert that carries
	// the fraud-scorer's FLAG decision. BLOCK outcomes short-circuit
	// upstream and never produce a transfer row; ALLOW outcomes use the
	// narrow form above.
	//
	CreateTransferAcceptedFlagged(ctx context.Context, arg CreateTransferAcceptedFlaggedParams) (CreateTransferAcceptedFlaggedRow, error)
	// End-user CRUD and narrow projections. Each fetch variant returns
	// exactly the columns its caller renders — SELECT * is reserved for the
	// generic GetUser path. Narrow projections keep the row cache hot on
	// the latency-sensitive auth + transfer-accept flows.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserSession(ctx context.Context, arg CreateUserSessionParams) error
	// CreateUserSessionRotation records the replacement refresh row after
	// a successful /auth/refresh. user_agent/ip/device_id are not
	// re-captured on rotation — the DB-level defaults ('' / NULL) apply.
	//
	CreateUserSessionRotation(ctx context.Context, arg CreateUserSessionRotationParams) error
	// CreateUserWithAccountNumber is the signup-path insert. Stores the
	// minimum identity + credential set (names, email, password_hash)
	// alongside phone + account_number. kyc_tier is caller-supplied so
	// tests can seed arbitrary tiers without hitting the promotion path.
	//
	CreateUserWithAccountNumber(ctx context.Context, arg CreateUserWithAccountNumberParams) (CreateUserWithAccountNumberRow, error)
	DeactivateDevice(ctx context.Context, id string) error
	DecrementAccountBalance(ctx context.Context, arg DecrementAccountBalanceParams) (Account, error)
	// DeleteExpiredRealmKeys hard-deletes any key whose retired_at has
	// elapsed. Used by the rotate-realm-key ops command to GC keys past
	// their overlap window.
	//
	DeleteExpiredRealmKeys(ctx context.Context) error
	DeletePushToken(ctx context.Context, arg DeletePushTokenParams) error
	DeletePushTokenByValue(ctx context.Context, fcmToken string) error
	// DeleteRetiredRealmKeysBefore hard-deletes any row whose retired_at
	// is already past the supplied cutoff. Pairs with opsctl's prune step.
	//
	DeleteRetiredRealmKeysBefore(ctx context.Context, retiredAt pgtype.Timestamptz) error
	// EnsureSystemSuspenseAccount is an idempotent boot-time safety net for
	// the singleton suspense account + its owning system user. The initial
	// schema seeds both rows, so on a freshly migrated DB this is a no-op;
	// the upsert exists to keep Phase 4a ledger posts (which DEBIT
	// system-suspense) working against DBs restored from partial backups or
	// ad-hoc dev wipes.
	//
	// The system user is invisible to any human-facing surface — it never
	// logs in, and the SYSTEM kyc_tier + non-numeric account_number keep it
	// out of the signup/transfer paths.
	//
	EnsureSystemSuspenseAccount(ctx context.Context) error
	// ExistsTransferBetween returns whether this sender has ever transferred
	// to this receiver before. Powers the novel-receiver fraud rule.
	//
	ExistsTransferBetween(ctx context.Context, arg ExistsTransferBetweenParams) (bool, error)
	// ForceDecrementAccountBalance is the unguarded decrement path. Only
	// valid for account kinds exempt from the non-negative check — in
	// practice, the suspense account while it briefly holds the merchant
	// leg of a two-phase settlement.
	//
	ForceDecrementAccountBalance(ctx context.Context, arg ForceDecrementAccountBalanceParams) (Account, error)
	// ForceExpireActiveCeiling flips one ceiling to EXPIRED iff it is
	// currently ACTIVE. Used by opsctl force-expire-ceiling; returns
	// rows-affected so the caller can distinguish "id not found / already
	// terminal" from a real transition.
	//
	ForceExpireActiveCeiling(ctx context.Context, id string) (int64, error)
	GetAccount(ctx context.Context, id string) (Account, error)
	GetAccountByUserAndKind(ctx context.Context, arg GetAccountByUserAndKindParams) (Account, error)
	GetActiveBankSigningKey(ctx context.Context) (BankSigningKey, error)
	GetActiveCeilingForUser(ctx context.Context, payerUserID string) (CeilingToken, error)
	GetActiveDeviceForUser(ctx context.Context, userID string) (Device, error)
	GetActiveRealmKey(ctx context.Context) (RealmKey, error)
	// GetActiveSigningKey returns the user's currently active key.
	//
	GetActiveSigningKey(ctx context.Context, userID string) (SigningKey, error)
	// GetActiveSigningKeyPubkey is the narrow hot-path lookup used at
	// ceiling-issue time. No row means the user has not registered a
	// signing key yet.
	//
	GetActiveSigningKeyPubkey(ctx context.Context, userID string) ([]byte, error)
	// GetAdminSessionByRefreshHash returns the refresh-validation
	// projection: the session id (to revoke on rotate), admin_user_id
	// (to reload roles), and the lifecycle timestamps (to detect expiry
	// and prior revocation).
	//
	GetAdminSessionByRefreshHash(ctx context.Context, refreshHash string) (GetAdminSessionByRefreshHashRow, error)
	// GetAdminUserByID returns the public-facing admin profile. Used after
	// create, and after refresh to reload the session's admin context.
	//
	GetAdminUserByID(ctx context.Context, id string) (GetAdminUserByIDRow, error)
	// GetAdminUserForLogin returns the login-path projection: the public
	// profile fields plus password_hash so the service bcrypt-checks in
	// one round trip.
	//
	GetAdminUserForLogin(ctx context.Context, email string) (GetAdminUserForLoginRow, error)
	GetBankSigningKey(ctx context.Context, keyID string) (BankSigningKey, error)
	// GetCeilingRecoveryDetails returns the narrow projection the BFF
	// surfaces to the Flutter client while it polls recovery status.
	// status + release_after + ceiling_kobo are the client-rendered
	// fields; the remaining columns support the admin-side overlay.
	//
	GetCeilingRecoveryDetails(ctx context.Context, id string) (GetCeilingRecoveryDetailsRow, error)
	GetCeilingToken(ctx context.Context, id string) (CeilingToken, error)
	// GetCurrentCeilingForPayer returns the payer's most recent non-
	// terminal ceiling with its live settled and remaining totals. The
	// Flutter client uses the single result to render the tri-state panel
	// (active / recovery_pending / none) in one round trip.
	//
	// `remaining_kobo` = ceiling_kobo - SUM(settled across attached
	// payment tokens). Same math releaseCeiling uses to size the lien
	// release, so ops surfaces can cross-check against the lien balance.
	//
	GetCurrentCeilingForPayer(ctx context.Context, payerUserID string) (GetCurrentCeilingForPayerRow, error)
	GetDevice(ctx context.Context, id string) (Device, error)
	// GetKYCSubmissionSubmittedAt reads back the DB-assigned default
	// timestamp post-insert so the caller's returned struct reflects the
	// server clock rather than a client-supplied value.
	//
	GetKYCSubmissionSubmittedAt(ctx context.Context, id string) (pgtype.Timestamptz, error)
	// GetMeProjection is the /v1/me handler's narrow fetch — exactly the
	// profile fields the client renders.
	//
	GetMeProjection(ctx context.Context, id string) (GetMeProjectionRow, error)
	GetOTPChallenge(ctx context.Context, arg GetOTPChallengeParams) (OtpChallenge, error)
	GetPaymentBySequence(ctx context.Context, arg GetPaymentBySequenceParams) (PaymentToken, error)
	GetPaymentToken(ctx context.Context, id string) (PaymentToken, error)
	// GetPaymentTokenForAdmin is the single-row accessor for the
	// transaction-detail endpoint. Column set matches the List variants
	// above so the UI renders with one adapter.
	//
	GetPaymentTokenForAdmin(ctx context.Context, id string) (GetPaymentTokenForAdminRow, error)
	GetRealmKey(ctx context.Context, version int32) (RealmKey, error)
	GetReconciliationRun(ctx context.Context, id string) (ReconciliationRun, error)
	GetSettlementBatchHeader(ctx context.Context, dollar_1 string) (GetSettlementBatchHeaderRow, error)
	GetSettlementBatchStatusCounts(ctx context.Context, settlementBatchID *string) ([]GetSettlementBatchStatusCountsRow, error)
	GetTransaction(ctx context.Context, id string) (Transaction, error)
	// GetTransactionAnchorForPayment returns the DEBIT-side (payer-side)
	// row's id + group_id for a payment token. Phase 4b reuses this id
	// as the ledger txn_id so the FK holds and the balance trigger sees
	// one grouped posting, then flips both paired rows' status via
	// ListTransactionsByGroup.
	//
	GetTransactionAnchorForPayment(ctx context.Context, paymentTokenID *string) (GetTransactionAnchorForPaymentRow, error)
	// GetTransactionAnchorForTransfer is the transfer-processor analogue
	// for online P2P transfers; same reuse-the-DEBIT-id contract.
	//
	GetTransactionAnchorForTransfer(ctx context.Context, transferID *string) (GetTransactionAnchorForTransferRow, error)
	GetTransfer(ctx context.Context, id string) (Transfer, error)
	GetTransferByRef(ctx context.Context, arg GetTransferByRefParams) (Transfer, error)
	// GetTransferByRefProjection mirrors GetTransferProjection but looks
	// up by (sender, reference) — the transfer idempotency key.
	//
	GetTransferByRefProjection(ctx context.Context, arg GetTransferByRefProjectionParams) (GetTransferByRefProjectionRow, error)
	// GetTransferForAdmin is the transfer-detail accessor. Returns the
	// same shape as GetPaymentTokenForAdmin so the admin service can
	// look up either kind by id and hand the dashboard a uniform row.
	//
	GetTransferForAdmin(ctx context.Context, id string) (GetTransferForAdminRow, error)
	// GetTransferProjection is the user-facing single-row fetch. Omits
	// `flagged` so the BFF never surfaces the internal fraud flag.
	//
	GetTransferProjection(ctx context.Context, id string) (GetTransferProjectionRow, error)
	GetUser(ctx context.Context, id string) (User, error)
	// GetUserAccountAgeHours returns the sender's account age in hours
	// (EXTRACT yields a double; sqlc maps it to float64). Drives the
	// fraud scorer's new-account rule.
	//
	GetUserAccountAgeHours(ctx context.Context, id string) (float64, error)
	// GetUserAccountNumber fetches just the 10-digit account number.
	// Used by the refresh flow which already has a user id and needs the
	// account number to mint the next access token.
	//
	GetUserAccountNumber(ctx context.Context, id string) (string, error)
	// GetUserBalancesForAdmin is the backoffice user-detail single-row
	// lookup. Joins the main + lien-holding balances so one round trip
	// renders the whole panel. Returns one row even when the user has no
	// accounts provisioned yet — COALESCE holds the balances at 0.
	//
	// The "lien" balance is the live offline-wallet float: funds committed
	// to an active ceiling and spendable offline via signed payment tokens.
	//
	GetUserBalancesForAdmin(ctx context.Context, id string) (GetUserBalancesForAdminRow, error)
	GetUserByAccountNumber(ctx context.Context, accountNumber string) (GetUserByAccountNumberRow, error)
	// GetUserByEmail locates a user by registered email (case-insensitive).
	// Used by the password-reset flow to issue a reset code.
	//
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	// GetUserDisplayNamesByIDs batches the display-name join used by
	// activity feeds so the UI shows "Jane Doe" rather than a raw user id.
	// Returns one row per matching id; callers tolerate arbitrary
	// ordering and hash rows by id.
	//
	GetUserDisplayNamesByIDs(ctx context.Context, dollar_1 []string) ([]GetUserDisplayNamesByIDsRow, error)
	// GetUserIDAndAccountNumberByPhone is the login-path lookup: normalise
	// the phone, then fetch id + account_number for session creation.
	//
	GetUserIDAndAccountNumberByPhone(ctx context.Context, phone string) (GetUserIDAndAccountNumberByPhoneRow, error)
	// GetUserIDByAccountNumber is the receiver-resolution step of the
	// transfer-accept flow.
	//
	GetUserIDByAccountNumber(ctx context.Context, accountNumber string) (string, error)
	// GetUserKYCTier is the narrow tier lookup inside the transfer-accept
	// tx. Kept separate from GetUser so hot-path reads skip unused columns.
	//
	GetUserKYCTier(ctx context.Context, id string) (string, error)
	// GetUserLoginByPhone returns the password-login projection: id,
	// account_number, password_hash. Bundled so the login hot path
	// bcrypt-checks in a single round trip.
	//
	GetUserLoginByPhone(ctx context.Context, phone string) (GetUserLoginByPhoneRow, error)
	// GetUserNameByAccountNumber powers the demo-mint name-enquiry step:
	// given a 10-digit account number, return the holder's names so the
	// frontend can confirm the recipient before funding. System accounts
	// (kyc_tier='SYSTEM') are excluded so treasury owners never appear as
	// valid recipients.
	//
	GetUserNameByAccountNumber(ctx context.Context, accountNumber string) (GetUserNameByAccountNumberRow, error)
	// GetUserPINState returns the VerifyPIN projection. No row means the
	// user has not set a PIN yet; the service maps that to "pin_not_set".
	//
	GetUserPINState(ctx context.Context, userID string) (GetUserPINStateRow, error)
	// GetUserPhoneAndTier returns the fields the KYC flow needs to decide
	// whether to promote: the phone (to compute the expected mock id) and
	// the current tier (so only strictly-higher promotions apply).
	//
	GetUserPhoneAndTier(ctx context.Context, id string) (GetUserPhoneAndTierRow, error)
	// GetUserPhoneByID powers KYCHint; narrow projection keeps it
	// independent from GetUser even when the full row shape changes.
	//
	GetUserPhoneByID(ctx context.Context, id string) (string, error)
	GetUserSessionByRefreshHash(ctx context.Context, refreshHash string) (GetUserSessionByRefreshHashRow, error)
	// GetUserSessionOwner returns owner + revocation state for one
	// session id. RevokeSession uses this to enforce per-user ownership
	// before the revocation write.
	//
	GetUserSessionOwner(ctx context.Context, id string) (GetUserSessionOwnerRow, error)
	// GrantAdminRoleByName binds one role to an admin user by role name.
	// A non-existent role name silently no-ops — the inner SELECT returns
	// zero rows and the INSERT inserts zero.
	//
	GrantAdminRoleByName(ctx context.Context, arg GrantAdminRoleByNameParams) error
	IncrementAccountBalance(ctx context.Context, arg IncrementAccountBalanceParams) (Account, error)
	IncrementOTPAttempts(ctx context.Context, arg IncrementOTPAttemptsParams) error
	// Admin audit log. The service's Audit() helper is best-effort — the
	// insert returns nothing and errors are logged, not surfaced. The
	// list/count pair powers the backoffice audit page.
	// InsertAdminAuditLog appends one audit row. `payload` is JSONB;
	// callers pre-marshal to []byte before invoking.
	//
	InsertAdminAuditLog(ctx context.Context, arg InsertAdminAuditLogParams) error
	// InsertFraudScore records a BLOCK or FLAG decision for one transfer.
	// ALLOW outcomes are trace-only and never written to this table so it
	// stays small and queryable.
	//
	InsertFraudScore(ctx context.Context, arg InsertFraudScoreParams) error
	// Fraud signals (cryptographic/offline anomalies on payment_tokens)
	// and fraud scores (scoring decisions on online transfers). The two
	// streams are distinct domains and deliberately unioned only at the
	// admin-reporting layer.
	InsertFraudSignal(ctx context.Context, arg InsertFraudSignalParams) (FraudSignal, error)
	// KYC submissions + history reads. Tier promotion itself mutates the
	// users table and lives in users.sql (PromoteUserToTier).
	// InsertKYCSubmission records one submission. Status is caller-
	// computed ('VERIFIED' or 'REJECTED'); the column's check constraint
	// rejects stray values.
	//
	InsertKYCSubmission(ctx context.Context, arg InsertKYCSubmissionParams) error
	// Double-entry ledger primitives. Every posting is a pair (DEBIT +
	// CREDIT) sharing one txn_id; the deferred constraint trigger on
	// ledger_entries enforces balance at COMMIT. These queries are the
	// mechanical insert/read path — ledger-balance invariants live in the
	// trigger and the Repo.Tx boundary.
	InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (LedgerEntry, error)
	// Transactional outbox for async event dispatch. Writes land in the
	// same tx as the aggregate mutation; the dispatcher picks rows up
	// with Claim → Mark (on success) / BumpAttempt (on retry) so at-least-
	// once delivery is preserved across crashes.
	InsertOutboxEntry(ctx context.Context, arg InsertOutboxEntryParams) error
	// End-user Ed25519 signing keys. Only the active row's pubkey issues
	// new ceiling tokens; historical ceilings verify against the
	// snapshotted pubkey stored in ceiling_tokens.payer_pubkey, so
	// rotation never invalidates in-flight offline payments.
	// InsertSigningKey records a freshly-provisioned active key. Callers
	// must retire any previous active key (RetireActiveSigningKey) in
	// the same tx — the partial unique index enforces one active row
	// per user.
	//
	InsertSigningKey(ctx context.Context, arg InsertSigningKeyParams) (SigningKey, error)
	IsEventProcessed(ctx context.Context, outboxID string) (bool, error)
	ListAccountsByUser(ctx context.Context, userID string) ([]Account, error)
	// ListAccountsForAdmin returns every account row for one user, with
	// `kind` cast to text for the admin JSON payload (the frontend treats
	// it as an opaque string).
	//
	ListAccountsForAdmin(ctx context.Context, userID string) ([]ListAccountsForAdminRow, error)
	ListActiveBankSigningKeys(ctx context.Context) ([]BankSigningKey, error)
	// ListActiveRealmKeys returns every key still inside its overlap
	// window — not yet retired, or retired with retired_at in the future.
	// Clients fetch the full set so a device can decrypt a backlog of QRs
	// sealed under any version still in overlap. Newest first.
	//
	ListActiveRealmKeys(ctx context.Context, limit int32) ([]RealmKey, error)
	// ListActiveUserSessions returns every non-revoked, non-expired
	// refresh session for userID. Powers the end-user devices/sessions
	// screen.
	//
	ListActiveUserSessions(ctx context.Context, userID string) ([]ListActiveUserSessionsRow, error)
	ListAdminAuditLog(ctx context.Context, arg ListAdminAuditLogParams) ([]ListAdminAuditLogRow, error)
	// ListAdminRoleNamesForUser returns the caller's role names, alpha
	// sorted. Feeds both Login and Refresh so the issued JWT carries the
	// current role set.
	//
	ListAdminRoleNamesForUser(ctx context.Context, adminUserID string) ([]string, error)
	ListAllAccounts(ctx context.Context) ([]Account, error)
	ListAllCeilings(ctx context.Context) ([]CeilingToken, error)
	ListCeilingsByUser(ctx context.Context, payerUserID string) ([]CeilingToken, error)
	// ListCeilingsForAdmin returns the payer's most recent ceilings with
	// their live remaining balance (ceiling_kobo - SUM(settled across
	// attached payment_tokens)). Feeds the backoffice user-detail view.
	//
	ListCeilingsForAdmin(ctx context.Context, arg ListCeilingsForAdminParams) ([]ListCeilingsForAdminRow, error)
	// ListDevicesForAdmin returns the backoffice projection for one
	// user's devices, newest first. Narrow column set so the backoffice
	// payload stays stable independent of internal schema additions.
	//
	ListDevicesForAdmin(ctx context.Context, userID string) ([]ListDevicesForAdminRow, error)
	ListExpiredActiveCeilings(ctx context.Context, expiresAt pgtype.Timestamptz) ([]CeilingToken, error)
	ListFraudSignalsByUser(ctx context.Context, arg ListFraudSignalsByUserParams) ([]FraudSignal, error)
	// ListFraudSignalsForAdmin powers the backoffice user-detail view.
	// Caller caps via $2; typical page is 20 newest signals.
	//
	ListFraudSignalsForAdmin(ctx context.Context, arg ListFraudSignalsForAdminParams) ([]ListFraudSignalsForAdminRow, error)
	ListFraudSignalsForUser(ctx context.Context, userID string) ([]FraudSignal, error)
	// ListFraudSignalsGlobal powers the fraud dashboard. Widens the
	// per-user projection with user_id, details, and the optional ceiling
	// and transaction refs so the operator can click through to context
	// from a single page.
	//
	ListFraudSignalsGlobal(ctx context.Context, arg ListFraudSignalsGlobalParams) ([]ListFraudSignalsGlobalRow, error)
	// ListKYCSubmissionsByUser powers the per-user KYC history view.
	//
	ListKYCSubmissionsByUser(ctx context.Context, userID string) ([]KycSubmission, error)
	ListLedgerEntriesByAccount(ctx context.Context, arg ListLedgerEntriesByAccountParams) ([]LedgerEntry, error)
	ListLedgerEntriesByTxn(ctx context.Context, txnID string) ([]LedgerEntry, error)
	// Returns distinct payer_user_ids whose oldest PENDING payment is older
	// than $1. Used by the auto-settle sweeper.
	ListPayersWithStalePending(ctx context.Context, submittedAt pgtype.Timestamptz) ([]ListPayersWithStalePendingRow, error)
	// ----------------------------------------------------------------------
	// Admin list + count projections for payment_tokens.
	//
	// The backoffice supports filtering by any combination of {status,
	// payer, payee, settlement_batch_id}. Following the codebase's "no
	// runtime-built SQL" rule, the eight combinations are spelled out as
	// named queries with matching count twins; the service layer dispatches
	// on which filter fields are non-empty.
	// ----------------------------------------------------------------------
	// ListPaymentTokensForAdmin is the unfiltered admin transactions feed:
	// UNION-ALL of `payment_tokens` (offline ceiling-backed flow) and
	// `transfers` (online P2P flow), normalised to a single row shape
	// tagged with `kind` so the UI can distinguish the source.
	//
	// The filtered variants below stay payment_tokens-only — their
	// predicates (payment_status enum, batch_id, sequence_number) don't
	// have analogues on the transfers side.
	//
	ListPaymentTokensForAdmin(ctx context.Context, arg ListPaymentTokensForAdminParams) ([]ListPaymentTokensForAdminRow, error)
	ListPaymentTokensForAdminByBatch(ctx context.Context, arg ListPaymentTokensForAdminByBatchParams) ([]ListPaymentTokensForAdminByBatchRow, error)
	ListPaymentTokensForAdminByPayee(ctx context.Context, arg ListPaymentTokensForAdminByPayeeParams) ([]ListPaymentTokensForAdminByPayeeRow, error)
	ListPaymentTokensForAdminByPayer(ctx context.Context, arg ListPaymentTokensForAdminByPayerParams) ([]ListPaymentTokensForAdminByPayerRow, error)
	ListPaymentTokensForAdminByPayerAndPayee(ctx context.Context, arg ListPaymentTokensForAdminByPayerAndPayeeParams) ([]ListPaymentTokensForAdminByPayerAndPayeeRow, error)
	ListPaymentTokensForAdminByStatus(ctx context.Context, arg ListPaymentTokensForAdminByStatusParams) ([]ListPaymentTokensForAdminByStatusRow, error)
	ListPaymentTokensForAdminByStatusAndPayee(ctx context.Context, arg ListPaymentTokensForAdminByStatusAndPayeeParams) ([]ListPaymentTokensForAdminByStatusAndPayeeRow, error)
	ListPaymentTokensForAdminByStatusAndPayer(ctx context.Context, arg ListPaymentTokensForAdminByStatusAndPayerParams) ([]ListPaymentTokensForAdminByStatusAndPayerRow, error)
	ListPaymentTokensForAdminByStatusAndPayerAndPayee(ctx context.Context, arg ListPaymentTokensForAdminByStatusAndPayerAndPayeeParams) ([]ListPaymentTokensForAdminByStatusAndPayerAndPayeeRow, error)
	ListPaymentsByBatch(ctx context.Context, settlementBatchID *string) ([]PaymentToken, error)
	ListPaymentsByPayee(ctx context.Context, payeeUserID string) ([]PaymentToken, error)
	ListPaymentsByPayer(ctx context.Context, payerUserID string) ([]PaymentToken, error)
	ListPendingPaymentsByPayer(ctx context.Context, payerUserID string) ([]PaymentToken, error)
	ListPushTokensForUser(ctx context.Context, userID string) ([]ListPushTokensForUserRow, error)
	ListRecentReconciliationRuns(ctx context.Context, arg ListRecentReconciliationRunsParams) ([]ReconciliationRun, error)
	// ListReleasableExpiredCeilings picks up ceilings ready to be released
	// back to the main wallet:
	//   1. ACTIVE ceilings past their grace window (normal expiry path).
	//   2. RECOVERY_PENDING ceilings past release_after (recovery
	//      quarantine elapsed).
	// Rows with in-flight payment claims are skipped — those funds are
	// legitimately owed and will be claimed by the merchant settlement.
	//
	ListReleasableExpiredCeilings(ctx context.Context, expiresAt pgtype.Timestamptz) ([]CeilingToken, error)
	ListSettledTxnsForPayer(ctx context.Context, payerUserID string) ([]PaymentToken, error)
	ListSettledTxnsForReceiver(ctx context.Context, payeeUserID string) ([]PaymentToken, error)
	ListSettlementBatches(ctx context.Context, arg ListSettlementBatchesParams) ([]ListSettlementBatchesRow, error)
	// ListSigningKeysByUser returns rotation history newest first.
	// Powers the backoffice key-history view.
	//
	ListSigningKeysByUser(ctx context.Context, userID string) ([]SigningKey, error)
	// ListTransactionsByGroup returns both rows of a paired two-party
	// event. Settlement and transfer-finalise paths use this to flip
	// both sides' status atomically inside the finalising tx.
	//
	ListTransactionsByGroup(ctx context.Context, groupID string) ([]Transaction, error)
	// ListTransactionsForUser is the user-facing history feed. Newest
	// first, with a stable id tiebreaker so the page boundary doesn't
	// shift between reads at the same timestamp.
	//
	ListTransactionsForUser(ctx context.Context, arg ListTransactionsForUserParams) ([]Transaction, error)
	// ListTransfersForUser returns transfers where the user is either
	// sender or receiver. Powers the BFF /v1/transfers list.
	//
	ListTransfersForUser(ctx context.Context, arg ListTransfersForUserParams) ([]ListTransfersForUserRow, error)
	ListTransfersReceived(ctx context.Context, arg ListTransfersReceivedParams) ([]Transfer, error)
	ListTransfersSent(ctx context.Context, arg ListTransfersSentParams) ([]Transfer, error)
	// ListUsersForAdmin returns one admin-projection page, newest first.
	// Shares its row shape with SearchUsersForAdminByPhone so scan adapters
	// can be reused across the listing and search paths.
	//
	ListUsersForAdmin(ctx context.Context, arg ListUsersForAdminParams) ([]ListUsersForAdminRow, error)
	// LockMainAccountForUser takes a row-level lock on the user's main
	// account so the transfer processor can debit and credit inside one tx.
	// FOR UPDATE is required: concurrent transfer ledger writes must
	// serialise through this lock to preserve balance invariants.
	//
	LockMainAccountForUser(ctx context.Context, userID string) (LockMainAccountForUserRow, error)
	// LockUserPIN records the mismatch that crosses the lockout threshold
	// and latches locked_at.
	//
	LockUserPIN(ctx context.Context, arg LockUserPINParams) error
	// MarkCeilingRecoveryPending transitions an ACTIVE ceiling into
	// RECOVERY_PENDING and stamps release_after. Returns rows-affected so
	// the caller can distinguish "no active ceiling", "already
	// recovering", and "success".
	//
	MarkCeilingRecoveryPending(ctx context.Context, arg MarkCeilingRecoveryPendingParams) (int64, error)
	// MarkEmailVerified flips email_verified to true. Idempotent.
	//
	MarkEmailVerified(ctx context.Context, id string) error
	// Idempotency table for outbox event processing. The processor writes
	// one row per handled event; the check-before-apply step makes handler
	// execution at-most-once even under dispatcher retries.
	MarkEventProcessed(ctx context.Context, arg MarkEventProcessedParams) error
	MarkOutboxDispatched(ctx context.Context, id string) error
	MarkTransferFailed(ctx context.Context, arg MarkTransferFailedParams) error
	// MarkTransferSettled + MarkTransferFailed are the terminal status
	// setters used by the transfer processor. Named queries (rather than
	// parameterised UpdateTransferStatus calls) keep processor code free
	// of inline SQL.
	//
	MarkTransferSettled(ctx context.Context, id string) error
	// NextRealmKeyVersion returns max(version)+1 for minting a fresh key.
	// opsctl rotate-realm-key runs this inside the rotation tx.
	//
	NextRealmKeyVersion(ctx context.Context) (int32, error)
	// PromoteUserToTier moves the user to a new KYC tier, but only if the
	// target tier is strictly higher in the TIER_0..TIER_3 ordering. The
	// CASE guard makes the promotion idempotent and prevents a lower tier
	// from clobbering an already-granted higher one.
	//
	PromoteUserToTier(ctx context.Context, arg PromoteUserToTierParams) error
	// transactions is the business-event log that anchors the ledger. Any
	// service mutating the ledger inserts a transactions row in the same
	// tx as its ledger posts; ledger_entries.txn_id FKs transactions.id,
	// so the row MUST land before COMMIT for the FK to hold.
	RecordTransaction(ctx context.Context, arg RecordTransactionParams) error
	// RetireActiveSigningKey flips the active key to inactive and stamps
	// rotated_at. The first step of rotation; InsertSigningKey follows
	// inside the same tx.
	//
	RetireActiveSigningKey(ctx context.Context, userID string) error
	// RetireAllActiveBankSigningKeys stamps retired_at on every still-active
	// row. Called by opsctl rotate-bank-key immediately before inserting
	// the freshly minted key so the new key is the only live one.
	//
	RetireAllActiveBankSigningKeys(ctx context.Context, retiredAt pgtype.Timestamptz) error
	RetireBankSigningKey(ctx context.Context, arg RetireBankSigningKeyParams) error
	// RetireOtherRealmKeys stamps retired_at on every still-active row
	// whose version differs from $1. opsctl invokes this right after
	// inserting the newly minted key.
	//
	RetireOtherRealmKeys(ctx context.Context, arg RetireOtherRealmKeysParams) error
	RetireRealmKey(ctx context.Context, arg RetireRealmKeyParams) error
	// RevokeAdminSessionByHash is the logout path. The revoked_at IS NULL
	// guard keeps logout idempotent — repeat calls do nothing.
	//
	RevokeAdminSessionByHash(ctx context.Context, refreshHash string) error
	// RevokeAdminSessionByID marks one session revoked. Used by the
	// rotate leg of Refresh when the id is already resolved.
	//
	RevokeAdminSessionByID(ctx context.Context, id string) error
	// RevokeOtherUserSessions revokes every active session for userID
	// except the one identified by $2. Pass '' in $2 to revoke all
	// sessions (the "sign me out everywhere" flow).
	//
	RevokeOtherUserSessions(ctx context.Context, arg RevokeOtherUserSessionsParams) (int64, error)
	RevokeUserSessionByHash(ctx context.Context, refreshHash string) error
	RevokeUserSessionByID(ctx context.Context, id string) error
	// SearchUsersForAdminByPhone matches phone or id against a lowercase
	// LIKE pattern (caller passes '%' + lower(q) + '%'). Column list
	// matches ListUsersForAdmin so the admin service layer shares scan
	// adapters.
	//
	SearchUsersForAdminByPhone(ctx context.Context, arg SearchUsersForAdminByPhoneParams) ([]SearchUsersForAdminByPhoneRow, error)
	// Per-user transaction PIN. user_pins is 1:1 with users; the row is
	// created on first PIN-set and refreshed via UPSERT on subsequent
	// resets.
	// SetUserPIN stores a freshly-hashed PIN and clears any prior lockout.
	// Returns rows-affected (always 1 after the upsert) so the caller can
	// confirm the write landed.
	//
	SetUserPIN(ctx context.Context, arg SetUserPINParams) (int64, error)
	SettledTotalForCeiling(ctx context.Context, ceilingID string) (int64, error)
	SumAccountCredits(ctx context.Context, accountID string) (int64, error)
	SumAccountDebits(ctx context.Context, accountID string) (int64, error)
	// SumSenderTransfersToday totals kobo spent today (Africa/Lagos) on
	// in-flight or settled transfers for one sender. Drives the high-daily-
	// share fraud rule.
	//
	SumSenderTransfersToday(ctx context.Context, senderUserID string) (int64, error)
	// SumSettledForCeiling returns the total settled amount across every
	// payment token attached to this ceiling. releaseCeiling subtracts
	// this from ceiling_kobo to derive the remaining lien — attempting
	// to debit the full ceiling would trip the balance_kobo >= $amount
	// guard the moment any merchant claim has landed.
	//
	SumSettledForCeiling(ctx context.Context, ceilingID string) (int64, error)
	// TouchAdminUserLastLogin stamps a successful login. Best-effort: the
	// service intentionally ignores errors so login never fails on this.
	//
	TouchAdminUserLastLogin(ctx context.Context, id string) error
	TouchDevice(ctx context.Context, arg TouchDeviceParams) error
	UpdateCeilingStatus(ctx context.Context, arg UpdateCeilingStatusParams) error
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (PaymentToken, error)
	UpdateReconciliationRun(ctx context.Context, arg UpdateReconciliationRunParams) error
	// UpdateTransactionStatus transitions status and optionally carries
	// a settled amount + failure reason. Callers pass NULLs for fields
	// that should not change; updated_at always bumps so observers can
	// detect the transition.
	//
	UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) error
	UpdateTransferStatus(ctx context.Context, arg UpdateTransferStatusParams) error
	UpdateUserKYC(ctx context.Context, arg UpdateUserKYCParams) error
	// UpdateUserPassword replaces the bcrypt password hash. Used by the
	// forgot-password reset flow.
	//
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	// End-user auth storage: OTP challenges driving signup-email-verify
	// and password-reset, plus refresh-session CRUD for login/rotate/
	// logout. admin auth queries live in admin.sql / admin_sessions.sql
	// because admin_users is a separate identity surface.
	// UpsertOTPChallenge stores or replaces the single active challenge
	// per (identifier, purpose). A re-send resets attempts + expires_at
	// and clears consumed_at so the fresh code is usable.
	//
	UpsertOTPChallenge(ctx context.Context, arg UpsertOTPChallengeParams) error
	// FCM push-token registry. The upsert-on-register pattern reassigns
	// ownership when the same token lands on a new user (device swaps,
	// factory reset, multi-account). Logout deletes the row.
	UpsertPushToken(ctx context.Context, arg UpsertPushTokenParams) error
}

var _ Querier = (*Queries)(nil)
