// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: realm_keys.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRealmKey = `-- name: CreateRealmKey :one

INSERT INTO realm_keys (version, key_enc, active_from)
VALUES ($1, $2, $3)
RETURNING version, key_enc, active_from, retired_at, created_at
`

type CreateRealmKeyParams struct {
	Version    int32              `json:"version"`
	KeyEnc     []byte             `json:"key_enc"`
	ActiveFrom pgtype.Timestamptz `json:"active_from"`
}

// Realm key (Layer 1 AES-256 QR encryption) lifecycle. Rotation mints
// a new version, retires the prior one with a grace-window overlap,
// and GCs anything past its overlap. QRs sealed under a GC'd version
// are accepted as undecryptable — the grace window is the design.
func (q *Queries) CreateRealmKey(ctx context.Context, arg CreateRealmKeyParams) (RealmKey, error) {
	row := q.db.QueryRow(ctx, createRealmKey, arg.Version, arg.KeyEnc, arg.ActiveFrom)
	var i RealmKey
	err := row.Scan(
		&i.Version,
		&i.KeyEnc,
		&i.ActiveFrom,
		&i.RetiredAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredRealmKeys = `-- name: DeleteExpiredRealmKeys :exec
DELETE FROM realm_keys
WHERE retired_at IS NOT NULL AND retired_at <= now()
`

// DeleteExpiredRealmKeys hard-deletes any key whose retired_at has
// elapsed. Used by the rotate-realm-key ops command to GC keys past
// their overlap window.
func (q *Queries) DeleteExpiredRealmKeys(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRealmKeys)
	return err
}

const deleteRetiredRealmKeysBefore = `-- name: DeleteRetiredRealmKeysBefore :exec
DELETE FROM realm_keys
WHERE retired_at IS NOT NULL AND retired_at < $1
`

// DeleteRetiredRealmKeysBefore hard-deletes any row whose retired_at
// is already past the supplied cutoff. Pairs with opsctl's prune step.
func (q *Queries) DeleteRetiredRealmKeysBefore(ctx context.Context, retiredAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteRetiredRealmKeysBefore, retiredAt)
	return err
}

const getActiveRealmKey = `-- name: GetActiveRealmKey :one
SELECT version, key_enc, active_from, retired_at, created_at FROM realm_keys
WHERE retired_at IS NULL
ORDER BY active_from DESC
LIMIT 1
`

func (q *Queries) GetActiveRealmKey(ctx context.Context) (RealmKey, error) {
	row := q.db.QueryRow(ctx, getActiveRealmKey)
	var i RealmKey
	err := row.Scan(
		&i.Version,
		&i.KeyEnc,
		&i.ActiveFrom,
		&i.RetiredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRealmKey = `-- name: GetRealmKey :one
SELECT version, key_enc, active_from, retired_at, created_at FROM realm_keys WHERE version = $1
`

func (q *Queries) GetRealmKey(ctx context.Context, version int32) (RealmKey, error) {
	row := q.db.QueryRow(ctx, getRealmKey, version)
	var i RealmKey
	err := row.Scan(
		&i.Version,
		&i.KeyEnc,
		&i.ActiveFrom,
		&i.RetiredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveRealmKeys = `-- name: ListActiveRealmKeys :many
SELECT version, key_enc, active_from, retired_at, created_at FROM realm_keys
WHERE retired_at IS NULL OR retired_at > now()
ORDER BY version DESC
LIMIT $1
`

// ListActiveRealmKeys returns every key still inside its overlap
// window — not yet retired, or retired with retired_at in the future.
// Clients fetch the full set so a device can decrypt a backlog of QRs
// sealed under any version still in overlap. Newest first.
func (q *Queries) ListActiveRealmKeys(ctx context.Context, limit int32) ([]RealmKey, error) {
	rows, err := q.db.Query(ctx, listActiveRealmKeys, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RealmKey{}
	for rows.Next() {
		var i RealmKey
		if err := rows.Scan(
			&i.Version,
			&i.KeyEnc,
			&i.ActiveFrom,
			&i.RetiredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextRealmKeyVersion = `-- name: NextRealmKeyVersion :one
SELECT COALESCE(MAX(version), 0) + 1 AS next_version FROM realm_keys
`

// NextRealmKeyVersion returns max(version)+1 for minting a fresh key.
// opsctl rotate-realm-key runs this inside the rotation tx.
func (q *Queries) NextRealmKeyVersion(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, nextRealmKeyVersion)
	var next_version int32
	err := row.Scan(&next_version)
	return next_version, err
}

const retireOtherRealmKeys = `-- name: RetireOtherRealmKeys :exec
UPDATE realm_keys
SET retired_at = $2
WHERE retired_at IS NULL AND version <> $1
`

type RetireOtherRealmKeysParams struct {
	Version   int32              `json:"version"`
	RetiredAt pgtype.Timestamptz `json:"retired_at"`
}

// RetireOtherRealmKeys stamps retired_at on every still-active row
// whose version differs from $1. opsctl invokes this right after
// inserting the newly minted key.
func (q *Queries) RetireOtherRealmKeys(ctx context.Context, arg RetireOtherRealmKeysParams) error {
	_, err := q.db.Exec(ctx, retireOtherRealmKeys, arg.Version, arg.RetiredAt)
	return err
}

const retireRealmKey = `-- name: RetireRealmKey :exec
UPDATE realm_keys SET retired_at = $2 WHERE version = $1
`

type RetireRealmKeyParams struct {
	Version   int32              `json:"version"`
	RetiredAt pgtype.Timestamptz `json:"retired_at"`
}

func (q *Queries) RetireRealmKey(ctx context.Context, arg RetireRealmKeyParams) error {
	_, err := q.db.Exec(ctx, retireRealmKey, arg.Version, arg.RetiredAt)
	return err
}
