// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reconciliation.sql

package sqlcgen

import (
	"context"
)

const accountLedgerSum = `-- name: AccountLedgerSum :one
SELECT
    COALESCE(SUM(CASE WHEN direction = 'DEBIT'  THEN amount_kobo ELSE 0 END), 0)::BIGINT AS debit_total,
    COALESCE(SUM(CASE WHEN direction = 'CREDIT' THEN amount_kobo ELSE 0 END), 0)::BIGINT AS credit_total
FROM ledger_entries
WHERE account_id = $1
`

type AccountLedgerSumRow struct {
	DebitTotal  int64 `json:"debit_total"`
	CreditTotal int64 `json:"credit_total"`
}

func (q *Queries) AccountLedgerSum(ctx context.Context, accountID string) (AccountLedgerSumRow, error) {
	row := q.db.QueryRow(ctx, accountLedgerSum, accountID)
	var i AccountLedgerSumRow
	err := row.Scan(&i.DebitTotal, &i.CreditTotal)
	return i, err
}

const createReconciliationRun = `-- name: CreateReconciliationRun :one

INSERT INTO reconciliation_runs (id, type, entity_id, status, discrepancies)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, type, entity_id, run_at, status, discrepancies, created_at
`

type CreateReconciliationRunParams struct {
	ID            string               `json:"id"`
	Type          ReconciliationType   `json:"type"`
	EntityID      string               `json:"entity_id"`
	Status        ReconciliationStatus `json:"status"`
	Discrepancies []byte               `json:"discrepancies"`
}

// Reconciliation run history + the read queries that back each
// reconciler. Three reconcilers drive off this file:
//
//	PAYER     — per-user offline-settled payment mismatch scan.
//	MERCHANT  — per-receiver settlement-batch roll-up.
//	LEDGER    — global account-balance vs ledger-sum check.
func (q *Queries) CreateReconciliationRun(ctx context.Context, arg CreateReconciliationRunParams) (ReconciliationRun, error) {
	row := q.db.QueryRow(ctx, createReconciliationRun,
		arg.ID,
		arg.Type,
		arg.EntityID,
		arg.Status,
		arg.Discrepancies,
	)
	var i ReconciliationRun
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.EntityID,
		&i.RunAt,
		&i.Status,
		&i.Discrepancies,
		&i.CreatedAt,
	)
	return i, err
}

const getReconciliationRun = `-- name: GetReconciliationRun :one
SELECT id, type, entity_id, run_at, status, discrepancies, created_at FROM reconciliation_runs WHERE id = $1
`

func (q *Queries) GetReconciliationRun(ctx context.Context, id string) (ReconciliationRun, error) {
	row := q.db.QueryRow(ctx, getReconciliationRun, id)
	var i ReconciliationRun
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.EntityID,
		&i.RunAt,
		&i.Status,
		&i.Discrepancies,
		&i.CreatedAt,
	)
	return i, err
}

const listAllAccounts = `-- name: ListAllAccounts :many
SELECT id, user_id, kind, balance_kobo, created_at, updated_at FROM accounts ORDER BY id ASC
`

func (q *Queries) ListAllAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAllAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.BalanceKobo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCeilings = `-- name: ListAllCeilings :many
SELECT id, payer_user_id, ceiling_kobo, sequence_start, issued_at, expires_at, payer_pubkey, bank_key_id, bank_sig, status, lien_account_id, created_at, release_after FROM ceiling_tokens ORDER BY id ASC
`

func (q *Queries) ListAllCeilings(ctx context.Context) ([]CeilingToken, error) {
	rows, err := q.db.Query(ctx, listAllCeilings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CeilingToken{}
	for rows.Next() {
		var i CeilingToken
		if err := rows.Scan(
			&i.ID,
			&i.PayerUserID,
			&i.CeilingKobo,
			&i.SequenceStart,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.PayerPubkey,
			&i.BankKeyID,
			&i.BankSig,
			&i.Status,
			&i.LienAccountID,
			&i.CreatedAt,
			&i.ReleaseAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByBatch = `-- name: ListPaymentsByBatch :many
SELECT id, ceiling_id, payer_user_id, payee_user_id, amount_kobo, sequence_number, remaining_ceiling_kobo, settled_amount_kobo, signed_at, payer_sig, status, rejection_reason, settlement_batch_id, submitted_at, settled_at, created_at, updated_at, session_nonce, request_hash, request_amount_kobo, submitted_by_user_id FROM payment_tokens
WHERE settlement_batch_id = $1
ORDER BY sequence_number ASC
`

func (q *Queries) ListPaymentsByBatch(ctx context.Context, settlementBatchID *string) ([]PaymentToken, error) {
	rows, err := q.db.Query(ctx, listPaymentsByBatch, settlementBatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentToken{}
	for rows.Next() {
		var i PaymentToken
		if err := rows.Scan(
			&i.ID,
			&i.CeilingID,
			&i.PayerUserID,
			&i.PayeeUserID,
			&i.AmountKobo,
			&i.SequenceNumber,
			&i.RemainingCeilingKobo,
			&i.SettledAmountKobo,
			&i.SignedAt,
			&i.PayerSig,
			&i.Status,
			&i.RejectionReason,
			&i.SettlementBatchID,
			&i.SubmittedAt,
			&i.SettledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SessionNonce,
			&i.RequestHash,
			&i.RequestAmountKobo,
			&i.SubmittedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentReconciliationRuns = `-- name: ListRecentReconciliationRuns :many
SELECT id, type, entity_id, run_at, status, discrepancies, created_at FROM reconciliation_runs
WHERE type = $1
ORDER BY run_at DESC
LIMIT $2
`

type ListRecentReconciliationRunsParams struct {
	Type  ReconciliationType `json:"type"`
	Limit int32              `json:"limit"`
}

func (q *Queries) ListRecentReconciliationRuns(ctx context.Context, arg ListRecentReconciliationRunsParams) ([]ReconciliationRun, error) {
	rows, err := q.db.Query(ctx, listRecentReconciliationRuns, arg.Type, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconciliationRun{}
	for rows.Next() {
		var i ReconciliationRun
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.EntityID,
			&i.RunAt,
			&i.Status,
			&i.Discrepancies,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettledTxnsForPayer = `-- name: ListSettledTxnsForPayer :many
SELECT id, ceiling_id, payer_user_id, payee_user_id, amount_kobo, sequence_number, remaining_ceiling_kobo, settled_amount_kobo, signed_at, payer_sig, status, rejection_reason, settlement_batch_id, submitted_at, settled_at, created_at, updated_at, session_nonce, request_hash, request_amount_kobo, submitted_by_user_id FROM payment_tokens
WHERE payer_user_id = $1 AND status IN ('SETTLED', 'PARTIALLY_SETTLED')
ORDER BY sequence_number ASC
`

func (q *Queries) ListSettledTxnsForPayer(ctx context.Context, payerUserID string) ([]PaymentToken, error) {
	rows, err := q.db.Query(ctx, listSettledTxnsForPayer, payerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentToken{}
	for rows.Next() {
		var i PaymentToken
		if err := rows.Scan(
			&i.ID,
			&i.CeilingID,
			&i.PayerUserID,
			&i.PayeeUserID,
			&i.AmountKobo,
			&i.SequenceNumber,
			&i.RemainingCeilingKobo,
			&i.SettledAmountKobo,
			&i.SignedAt,
			&i.PayerSig,
			&i.Status,
			&i.RejectionReason,
			&i.SettlementBatchID,
			&i.SubmittedAt,
			&i.SettledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SessionNonce,
			&i.RequestHash,
			&i.RequestAmountKobo,
			&i.SubmittedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettledTxnsForReceiver = `-- name: ListSettledTxnsForReceiver :many
SELECT id, ceiling_id, payer_user_id, payee_user_id, amount_kobo, sequence_number, remaining_ceiling_kobo, settled_amount_kobo, signed_at, payer_sig, status, rejection_reason, settlement_batch_id, submitted_at, settled_at, created_at, updated_at, session_nonce, request_hash, request_amount_kobo, submitted_by_user_id FROM payment_tokens
WHERE payee_user_id = $1 AND status IN ('SETTLED', 'PARTIALLY_SETTLED')
ORDER BY created_at ASC
`

func (q *Queries) ListSettledTxnsForReceiver(ctx context.Context, payeeUserID string) ([]PaymentToken, error) {
	rows, err := q.db.Query(ctx, listSettledTxnsForReceiver, payeeUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentToken{}
	for rows.Next() {
		var i PaymentToken
		if err := rows.Scan(
			&i.ID,
			&i.CeilingID,
			&i.PayerUserID,
			&i.PayeeUserID,
			&i.AmountKobo,
			&i.SequenceNumber,
			&i.RemainingCeilingKobo,
			&i.SettledAmountKobo,
			&i.SignedAt,
			&i.PayerSig,
			&i.Status,
			&i.RejectionReason,
			&i.SettlementBatchID,
			&i.SubmittedAt,
			&i.SettledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SessionNonce,
			&i.RequestHash,
			&i.RequestAmountKobo,
			&i.SubmittedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const settledTotalForCeiling = `-- name: SettledTotalForCeiling :one
SELECT COALESCE(SUM(settled_amount_kobo), 0)::BIGINT AS total
FROM payment_tokens
WHERE ceiling_id = $1 AND status IN ('SETTLED', 'PARTIALLY_SETTLED')
`

func (q *Queries) SettledTotalForCeiling(ctx context.Context, ceilingID string) (int64, error) {
	row := q.db.QueryRow(ctx, settledTotalForCeiling, ceilingID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const updateReconciliationRun = `-- name: UpdateReconciliationRun :exec
UPDATE reconciliation_runs
SET status = $2, discrepancies = $3
WHERE id = $1
`

type UpdateReconciliationRunParams struct {
	ID            string               `json:"id"`
	Status        ReconciliationStatus `json:"status"`
	Discrepancies []byte               `json:"discrepancies"`
}

func (q *Queries) UpdateReconciliationRun(ctx context.Context, arg UpdateReconciliationRunParams) error {
	_, err := q.db.Exec(ctx, updateReconciliationRun, arg.ID, arg.Status, arg.Discrepancies)
	return err
}
