// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: signing_keys.sql

package sqlcgen

import (
	"context"
)

const getActiveSigningKey = `-- name: GetActiveSigningKey :one
SELECT id, user_id, device_id, public_key, active, rotated_at, created_at FROM signing_keys
WHERE user_id = $1 AND active = TRUE
`

// GetActiveSigningKey returns the user's currently active key.
func (q *Queries) GetActiveSigningKey(ctx context.Context, userID string) (SigningKey, error) {
	row := q.db.QueryRow(ctx, getActiveSigningKey, userID)
	var i SigningKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.PublicKey,
		&i.Active,
		&i.RotatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveSigningKeyPubkey = `-- name: GetActiveSigningKeyPubkey :one
SELECT public_key FROM signing_keys
WHERE user_id = $1 AND active = TRUE
`

// GetActiveSigningKeyPubkey is the narrow hot-path lookup used at
// ceiling-issue time. No row means the user has not registered a
// signing key yet.
func (q *Queries) GetActiveSigningKeyPubkey(ctx context.Context, userID string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getActiveSigningKeyPubkey, userID)
	var public_key []byte
	err := row.Scan(&public_key)
	return public_key, err
}

const insertSigningKey = `-- name: InsertSigningKey :one

INSERT INTO signing_keys (id, user_id, device_id, public_key, active)
VALUES ($1, $2, $3, $4, TRUE)
RETURNING id, user_id, device_id, public_key, active, rotated_at, created_at
`

type InsertSigningKeyParams struct {
	ID        string  `json:"id"`
	UserID    string  `json:"user_id"`
	DeviceID  *string `json:"device_id"`
	PublicKey []byte  `json:"public_key"`
}

// End-user Ed25519 signing keys. Only the active row's pubkey issues
// new ceiling tokens; historical ceilings verify against the
// snapshotted pubkey stored in ceiling_tokens.payer_pubkey, so
// rotation never invalidates in-flight offline payments.
// InsertSigningKey records a freshly-provisioned active key. Callers
// must retire any previous active key (RetireActiveSigningKey) in
// the same tx — the partial unique index enforces one active row
// per user.
func (q *Queries) InsertSigningKey(ctx context.Context, arg InsertSigningKeyParams) (SigningKey, error) {
	row := q.db.QueryRow(ctx, insertSigningKey,
		arg.ID,
		arg.UserID,
		arg.DeviceID,
		arg.PublicKey,
	)
	var i SigningKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.PublicKey,
		&i.Active,
		&i.RotatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listSigningKeysByUser = `-- name: ListSigningKeysByUser :many
SELECT id, user_id, device_id, public_key, active, rotated_at, created_at FROM signing_keys
WHERE user_id = $1
ORDER BY created_at DESC
`

// ListSigningKeysByUser returns rotation history newest first.
// Powers the backoffice key-history view.
func (q *Queries) ListSigningKeysByUser(ctx context.Context, userID string) ([]SigningKey, error) {
	rows, err := q.db.Query(ctx, listSigningKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SigningKey{}
	for rows.Next() {
		var i SigningKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceID,
			&i.PublicKey,
			&i.Active,
			&i.RotatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retireActiveSigningKey = `-- name: RetireActiveSigningKey :exec
UPDATE signing_keys
SET active = FALSE,
    rotated_at = now()
WHERE user_id = $1 AND active = TRUE
`

// RetireActiveSigningKey flips the active key to inactive and stamps
// rotated_at. The first step of rotation; InsertSigningKey follows
// inside the same tx.
func (q *Queries) RetireActiveSigningKey(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, retireActiveSigningKey, userID)
	return err
}
