// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package sqlcgen

import (
	"context"
)

const countTransactionsForUser = `-- name: CountTransactionsForUser :one
SELECT COUNT(*)::BIGINT AS total FROM transactions WHERE user_id = $1
`

func (q *Queries) CountTransactionsForUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionsForUser, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, user_id, counterparty_user_id, kind, status, direction, amount_kobo, settled_amount_kobo, memo, payment_token_id, transfer_id, ceiling_id, group_id, failure_reason, created_at, updated_at FROM transactions WHERE id = $1
`

func (q *Queries) GetTransaction(ctx context.Context, id string) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CounterpartyUserID,
		&i.Kind,
		&i.Status,
		&i.Direction,
		&i.AmountKobo,
		&i.SettledAmountKobo,
		&i.Memo,
		&i.PaymentTokenID,
		&i.TransferID,
		&i.CeilingID,
		&i.GroupID,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionAnchorForPayment = `-- name: GetTransactionAnchorForPayment :one
SELECT id, group_id FROM transactions
WHERE payment_token_id = $1 AND direction = 'DEBIT'
LIMIT 1
`

type GetTransactionAnchorForPaymentRow struct {
	ID      string `json:"id"`
	GroupID string `json:"group_id"`
}

// GetTransactionAnchorForPayment returns the DEBIT-side (payer-side)
// row's id + group_id for a payment token. Phase 4b reuses this id
// as the ledger txn_id so the FK holds and the balance trigger sees
// one grouped posting, then flips both paired rows' status via
// ListTransactionsByGroup.
func (q *Queries) GetTransactionAnchorForPayment(ctx context.Context, paymentTokenID *string) (GetTransactionAnchorForPaymentRow, error) {
	row := q.db.QueryRow(ctx, getTransactionAnchorForPayment, paymentTokenID)
	var i GetTransactionAnchorForPaymentRow
	err := row.Scan(&i.ID, &i.GroupID)
	return i, err
}

const getTransactionAnchorForTransfer = `-- name: GetTransactionAnchorForTransfer :one
SELECT id, group_id FROM transactions
WHERE transfer_id = $1 AND direction = 'DEBIT'
LIMIT 1
`

type GetTransactionAnchorForTransferRow struct {
	ID      string `json:"id"`
	GroupID string `json:"group_id"`
}

// GetTransactionAnchorForTransfer is the transfer-processor analogue
// for online P2P transfers; same reuse-the-DEBIT-id contract.
func (q *Queries) GetTransactionAnchorForTransfer(ctx context.Context, transferID *string) (GetTransactionAnchorForTransferRow, error) {
	row := q.db.QueryRow(ctx, getTransactionAnchorForTransfer, transferID)
	var i GetTransactionAnchorForTransferRow
	err := row.Scan(&i.ID, &i.GroupID)
	return i, err
}

const listTransactionsByGroup = `-- name: ListTransactionsByGroup :many
SELECT id, user_id, counterparty_user_id, kind, status, direction, amount_kobo, settled_amount_kobo, memo, payment_token_id, transfer_id, ceiling_id, group_id, failure_reason, created_at, updated_at FROM transactions
WHERE group_id = $1
ORDER BY direction
`

// ListTransactionsByGroup returns both rows of a paired two-party
// event. Settlement and transfer-finalise paths use this to flip
// both sides' status atomically inside the finalising tx.
func (q *Queries) ListTransactionsByGroup(ctx context.Context, groupID string) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CounterpartyUserID,
			&i.Kind,
			&i.Status,
			&i.Direction,
			&i.AmountKobo,
			&i.SettledAmountKobo,
			&i.Memo,
			&i.PaymentTokenID,
			&i.TransferID,
			&i.CeilingID,
			&i.GroupID,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsForUser = `-- name: ListTransactionsForUser :many
SELECT id, user_id, counterparty_user_id, kind, status, direction, amount_kobo, settled_amount_kobo, memo, payment_token_id, transfer_id, ceiling_id, group_id, failure_reason, created_at, updated_at FROM transactions
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsForUserParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

// ListTransactionsForUser is the user-facing history feed. Newest
// first, with a stable id tiebreaker so the page boundary doesn't
// shift between reads at the same timestamp.
func (q *Queries) ListTransactionsForUser(ctx context.Context, arg ListTransactionsForUserParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsForUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CounterpartyUserID,
			&i.Kind,
			&i.Status,
			&i.Direction,
			&i.AmountKobo,
			&i.SettledAmountKobo,
			&i.Memo,
			&i.PaymentTokenID,
			&i.TransferID,
			&i.CeilingID,
			&i.GroupID,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordTransaction = `-- name: RecordTransaction :exec

INSERT INTO transactions (
    id, group_id, user_id, counterparty_user_id,
    kind, status, direction,
    amount_kobo, settled_amount_kobo,
    memo,
    payment_token_id, transfer_id, ceiling_id,
    failure_reason
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type RecordTransactionParams struct {
	ID                 string                     `json:"id"`
	GroupID            string                     `json:"group_id"`
	UserID             string                     `json:"user_id"`
	CounterpartyUserID *string                    `json:"counterparty_user_id"`
	Kind               TransactionKind            `json:"kind"`
	Status             TransactionLifecycleStatus `json:"status"`
	Direction          LedgerDirection            `json:"direction"`
	AmountKobo         int64                      `json:"amount_kobo"`
	SettledAmountKobo  *int64                     `json:"settled_amount_kobo"`
	Memo               *string                    `json:"memo"`
	PaymentTokenID     *string                    `json:"payment_token_id"`
	TransferID         *string                    `json:"transfer_id"`
	CeilingID          *string                    `json:"ceiling_id"`
	FailureReason      *string                    `json:"failure_reason"`
}

// transactions is the business-event log that anchors the ledger. Any
// service mutating the ledger inserts a transactions row in the same
// tx as its ledger posts; ledger_entries.txn_id FKs transactions.id,
// so the row MUST land before COMMIT for the FK to hold.
func (q *Queries) RecordTransaction(ctx context.Context, arg RecordTransactionParams) error {
	_, err := q.db.Exec(ctx, recordTransaction,
		arg.ID,
		arg.GroupID,
		arg.UserID,
		arg.CounterpartyUserID,
		arg.Kind,
		arg.Status,
		arg.Direction,
		arg.AmountKobo,
		arg.SettledAmountKobo,
		arg.Memo,
		arg.PaymentTokenID,
		arg.TransferID,
		arg.CeilingID,
		arg.FailureReason,
	)
	return err
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :exec
UPDATE transactions
SET status              = $2,
    settled_amount_kobo = COALESCE($3, settled_amount_kobo),
    failure_reason      = COALESCE($4, failure_reason),
    updated_at          = now()
WHERE id = $1
`

type UpdateTransactionStatusParams struct {
	ID                string                     `json:"id"`
	Status            TransactionLifecycleStatus `json:"status"`
	SettledAmountKobo *int64                     `json:"settled_amount_kobo"`
	FailureReason     *string                    `json:"failure_reason"`
}

// UpdateTransactionStatus transitions status and optionally carries
// a settled amount + failure reason. Callers pass NULLs for fields
// that should not change; updated_at always bumps so observers can
// detect the transition.
func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) error {
	_, err := q.db.Exec(ctx, updateTransactionStatus,
		arg.ID,
		arg.Status,
		arg.SettledAmountKobo,
		arg.FailureReason,
	)
	return err
}
