// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transfers.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRecentTransfersBySender = `-- name: CountRecentTransfersBySender :one
SELECT COUNT(*)::BIGINT AS count FROM (
    SELECT 1 FROM transfers
    WHERE sender_user_id = $1
      AND created_at >= now() - $2::interval
    LIMIT $3
) t
`

type CountRecentTransfersBySenderParams struct {
	SenderUserID string          `json:"sender_user_id"`
	Column2      pgtype.Interval `json:"column_2"`
	Limit        int32           `json:"limit"`
}

// CountRecentTransfersBySender counts transfers from one sender inside
// a trailing time window, short-circuiting at $3 so velocity rules
// stop scanning at threshold+1. Drives the fraud scorer's 1m and 1h
// velocity rules; the caller passes the window as a Postgres interval
// text (e.g. '60 seconds', '1 hour').
func (q *Queries) CountRecentTransfersBySender(ctx context.Context, arg CountRecentTransfersBySenderParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentTransfersBySender, arg.SenderUserID, arg.Column2, arg.Limit)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransferAccepted = `-- name: CreateTransferAccepted :one

INSERT INTO transfers (id, sender_user_id, receiver_user_id, receiver_account_number, amount_kobo, status, reference)
VALUES ($1, $2, $3, $4, $5, 'ACCEPTED', $6)
RETURNING id, sender_user_id, receiver_user_id, receiver_account_number, amount_kobo, status, reference, failure_reason, flagged, created_at, settled_at
`

type CreateTransferAcceptedParams struct {
	ID                    string `json:"id"`
	SenderUserID          string `json:"sender_user_id"`
	ReceiverUserID        string `json:"receiver_user_id"`
	ReceiverAccountNumber string `json:"receiver_account_number"`
	AmountKobo            int64  `json:"amount_kobo"`
	Reference             string `json:"reference"`
}

// Online intra-bank P2P transfers. Two parallel accept-insert forms:
// one for paths that don't fraud-score (tests, internal tooling) and
// one that captures the fraud decision. Projection reads (the suffix
// `Projection` variants) omit the `flagged` column so the BFF surface
// doesn't leak the internal fraud flag to the user-facing client.
func (q *Queries) CreateTransferAccepted(ctx context.Context, arg CreateTransferAcceptedParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, createTransferAccepted,
		arg.ID,
		arg.SenderUserID,
		arg.ReceiverUserID,
		arg.ReceiverAccountNumber,
		arg.AmountKobo,
		arg.Reference,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.SenderUserID,
		&i.ReceiverUserID,
		&i.ReceiverAccountNumber,
		&i.AmountKobo,
		&i.Status,
		&i.Reference,
		&i.FailureReason,
		&i.Flagged,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}

const createTransferAcceptedFlagged = `-- name: CreateTransferAcceptedFlagged :one
INSERT INTO transfers (id, sender_user_id, receiver_user_id, receiver_account_number, amount_kobo, status, reference, flagged)
VALUES ($1, $2, $3, $4, $5, 'ACCEPTED', $6, $7)
RETURNING id, sender_user_id, receiver_user_id, receiver_account_number,
          amount_kobo, status, reference, failure_reason, created_at, settled_at
`

type CreateTransferAcceptedFlaggedParams struct {
	ID                    string `json:"id"`
	SenderUserID          string `json:"sender_user_id"`
	ReceiverUserID        string `json:"receiver_user_id"`
	ReceiverAccountNumber string `json:"receiver_account_number"`
	AmountKobo            int64  `json:"amount_kobo"`
	Reference             string `json:"reference"`
	Flagged               bool   `json:"flagged"`
}

type CreateTransferAcceptedFlaggedRow struct {
	ID                    string             `json:"id"`
	SenderUserID          string             `json:"sender_user_id"`
	ReceiverUserID        string             `json:"receiver_user_id"`
	ReceiverAccountNumber string             `json:"receiver_account_number"`
	AmountKobo            int64              `json:"amount_kobo"`
	Status                string             `json:"status"`
	Reference             string             `json:"reference"`
	FailureReason         *string            `json:"failure_reason"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	SettledAt             pgtype.Timestamptz `json:"settled_at"`
}

// CreateTransferAcceptedFlagged is the accept-path insert that carries
// the fraud-scorer's FLAG decision. BLOCK outcomes short-circuit
// upstream and never produce a transfer row; ALLOW outcomes use the
// narrow form above.
func (q *Queries) CreateTransferAcceptedFlagged(ctx context.Context, arg CreateTransferAcceptedFlaggedParams) (CreateTransferAcceptedFlaggedRow, error) {
	row := q.db.QueryRow(ctx, createTransferAcceptedFlagged,
		arg.ID,
		arg.SenderUserID,
		arg.ReceiverUserID,
		arg.ReceiverAccountNumber,
		arg.AmountKobo,
		arg.Reference,
		arg.Flagged,
	)
	var i CreateTransferAcceptedFlaggedRow
	err := row.Scan(
		&i.ID,
		&i.SenderUserID,
		&i.ReceiverUserID,
		&i.ReceiverAccountNumber,
		&i.AmountKobo,
		&i.Status,
		&i.Reference,
		&i.FailureReason,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}

const existsTransferBetween = `-- name: ExistsTransferBetween :one
SELECT EXISTS (
    SELECT 1 FROM transfers
    WHERE sender_user_id = $1 AND receiver_user_id = $2
    LIMIT 1
) AS exists
`

type ExistsTransferBetweenParams struct {
	SenderUserID   string `json:"sender_user_id"`
	ReceiverUserID string `json:"receiver_user_id"`
}

// ExistsTransferBetween returns whether this sender has ever transferred
// to this receiver before. Powers the novel-receiver fraud rule.
func (q *Queries) ExistsTransferBetween(ctx context.Context, arg ExistsTransferBetweenParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsTransferBetween, arg.SenderUserID, arg.ReceiverUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getTransfer = `-- name: GetTransfer :one
SELECT id, sender_user_id, receiver_user_id, receiver_account_number, amount_kobo, status, reference, failure_reason, flagged, created_at, settled_at FROM transfers WHERE id = $1
`

func (q *Queries) GetTransfer(ctx context.Context, id string) (Transfer, error) {
	row := q.db.QueryRow(ctx, getTransfer, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.SenderUserID,
		&i.ReceiverUserID,
		&i.ReceiverAccountNumber,
		&i.AmountKobo,
		&i.Status,
		&i.Reference,
		&i.FailureReason,
		&i.Flagged,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}

const getTransferByRef = `-- name: GetTransferByRef :one
SELECT id, sender_user_id, receiver_user_id, receiver_account_number, amount_kobo, status, reference, failure_reason, flagged, created_at, settled_at FROM transfers WHERE sender_user_id = $1 AND reference = $2
`

type GetTransferByRefParams struct {
	SenderUserID string `json:"sender_user_id"`
	Reference    string `json:"reference"`
}

func (q *Queries) GetTransferByRef(ctx context.Context, arg GetTransferByRefParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, getTransferByRef, arg.SenderUserID, arg.Reference)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.SenderUserID,
		&i.ReceiverUserID,
		&i.ReceiverAccountNumber,
		&i.AmountKobo,
		&i.Status,
		&i.Reference,
		&i.FailureReason,
		&i.Flagged,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}

const getTransferByRefProjection = `-- name: GetTransferByRefProjection :one
SELECT id, sender_user_id, receiver_user_id, receiver_account_number,
       amount_kobo, status, reference, failure_reason, created_at, settled_at
FROM transfers WHERE sender_user_id = $1 AND reference = $2
`

type GetTransferByRefProjectionParams struct {
	SenderUserID string `json:"sender_user_id"`
	Reference    string `json:"reference"`
}

type GetTransferByRefProjectionRow struct {
	ID                    string             `json:"id"`
	SenderUserID          string             `json:"sender_user_id"`
	ReceiverUserID        string             `json:"receiver_user_id"`
	ReceiverAccountNumber string             `json:"receiver_account_number"`
	AmountKobo            int64              `json:"amount_kobo"`
	Status                string             `json:"status"`
	Reference             string             `json:"reference"`
	FailureReason         *string            `json:"failure_reason"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	SettledAt             pgtype.Timestamptz `json:"settled_at"`
}

// GetTransferByRefProjection mirrors GetTransferProjection but looks
// up by (sender, reference) — the transfer idempotency key.
func (q *Queries) GetTransferByRefProjection(ctx context.Context, arg GetTransferByRefProjectionParams) (GetTransferByRefProjectionRow, error) {
	row := q.db.QueryRow(ctx, getTransferByRefProjection, arg.SenderUserID, arg.Reference)
	var i GetTransferByRefProjectionRow
	err := row.Scan(
		&i.ID,
		&i.SenderUserID,
		&i.ReceiverUserID,
		&i.ReceiverAccountNumber,
		&i.AmountKobo,
		&i.Status,
		&i.Reference,
		&i.FailureReason,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}

const getTransferProjection = `-- name: GetTransferProjection :one
SELECT id, sender_user_id, receiver_user_id, receiver_account_number,
       amount_kobo, status, reference, failure_reason, created_at, settled_at
FROM transfers WHERE id = $1
`

type GetTransferProjectionRow struct {
	ID                    string             `json:"id"`
	SenderUserID          string             `json:"sender_user_id"`
	ReceiverUserID        string             `json:"receiver_user_id"`
	ReceiverAccountNumber string             `json:"receiver_account_number"`
	AmountKobo            int64              `json:"amount_kobo"`
	Status                string             `json:"status"`
	Reference             string             `json:"reference"`
	FailureReason         *string            `json:"failure_reason"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	SettledAt             pgtype.Timestamptz `json:"settled_at"`
}

// GetTransferProjection is the user-facing single-row fetch. Omits
// `flagged` so the BFF never surfaces the internal fraud flag.
func (q *Queries) GetTransferProjection(ctx context.Context, id string) (GetTransferProjectionRow, error) {
	row := q.db.QueryRow(ctx, getTransferProjection, id)
	var i GetTransferProjectionRow
	err := row.Scan(
		&i.ID,
		&i.SenderUserID,
		&i.ReceiverUserID,
		&i.ReceiverAccountNumber,
		&i.AmountKobo,
		&i.Status,
		&i.Reference,
		&i.FailureReason,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}

const listTransfersForUser = `-- name: ListTransfersForUser :many
SELECT id, sender_user_id, receiver_user_id, receiver_account_number,
       amount_kobo, status, reference, failure_reason, created_at, settled_at
FROM transfers
WHERE sender_user_id = $1 OR receiver_user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListTransfersForUserParams struct {
	SenderUserID string `json:"sender_user_id"`
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
}

type ListTransfersForUserRow struct {
	ID                    string             `json:"id"`
	SenderUserID          string             `json:"sender_user_id"`
	ReceiverUserID        string             `json:"receiver_user_id"`
	ReceiverAccountNumber string             `json:"receiver_account_number"`
	AmountKobo            int64              `json:"amount_kobo"`
	Status                string             `json:"status"`
	Reference             string             `json:"reference"`
	FailureReason         *string            `json:"failure_reason"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	SettledAt             pgtype.Timestamptz `json:"settled_at"`
}

// ListTransfersForUser returns transfers where the user is either
// sender or receiver. Powers the BFF /v1/transfers list.
func (q *Queries) ListTransfersForUser(ctx context.Context, arg ListTransfersForUserParams) ([]ListTransfersForUserRow, error) {
	rows, err := q.db.Query(ctx, listTransfersForUser, arg.SenderUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransfersForUserRow{}
	for rows.Next() {
		var i ListTransfersForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderUserID,
			&i.ReceiverUserID,
			&i.ReceiverAccountNumber,
			&i.AmountKobo,
			&i.Status,
			&i.Reference,
			&i.FailureReason,
			&i.CreatedAt,
			&i.SettledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfersReceived = `-- name: ListTransfersReceived :many
SELECT id, sender_user_id, receiver_user_id, receiver_account_number, amount_kobo, status, reference, failure_reason, flagged, created_at, settled_at FROM transfers
WHERE receiver_user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListTransfersReceivedParams struct {
	ReceiverUserID string `json:"receiver_user_id"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListTransfersReceived(ctx context.Context, arg ListTransfersReceivedParams) ([]Transfer, error) {
	rows, err := q.db.Query(ctx, listTransfersReceived, arg.ReceiverUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transfer{}
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.SenderUserID,
			&i.ReceiverUserID,
			&i.ReceiverAccountNumber,
			&i.AmountKobo,
			&i.Status,
			&i.Reference,
			&i.FailureReason,
			&i.Flagged,
			&i.CreatedAt,
			&i.SettledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfersSent = `-- name: ListTransfersSent :many
SELECT id, sender_user_id, receiver_user_id, receiver_account_number, amount_kobo, status, reference, failure_reason, flagged, created_at, settled_at FROM transfers
WHERE sender_user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListTransfersSentParams struct {
	SenderUserID string `json:"sender_user_id"`
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
}

func (q *Queries) ListTransfersSent(ctx context.Context, arg ListTransfersSentParams) ([]Transfer, error) {
	rows, err := q.db.Query(ctx, listTransfersSent, arg.SenderUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transfer{}
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.SenderUserID,
			&i.ReceiverUserID,
			&i.ReceiverAccountNumber,
			&i.AmountKobo,
			&i.Status,
			&i.Reference,
			&i.FailureReason,
			&i.Flagged,
			&i.CreatedAt,
			&i.SettledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTransferFailed = `-- name: MarkTransferFailed :exec
UPDATE transfers
SET status = 'FAILED',
    failure_reason = $2,
    settled_at = now()
WHERE id = $1
`

type MarkTransferFailedParams struct {
	ID            string  `json:"id"`
	FailureReason *string `json:"failure_reason"`
}

func (q *Queries) MarkTransferFailed(ctx context.Context, arg MarkTransferFailedParams) error {
	_, err := q.db.Exec(ctx, markTransferFailed, arg.ID, arg.FailureReason)
	return err
}

const markTransferSettled = `-- name: MarkTransferSettled :exec
UPDATE transfers
SET status = 'SETTLED',
    failure_reason = NULL,
    settled_at = now()
WHERE id = $1
`

// MarkTransferSettled + MarkTransferFailed are the terminal status
// setters used by the transfer processor. Named queries (rather than
// parameterised UpdateTransferStatus calls) keep processor code free
// of inline SQL.
func (q *Queries) MarkTransferSettled(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markTransferSettled, id)
	return err
}

const sumSenderTransfersToday = `-- name: SumSenderTransfersToday :one
SELECT COALESCE(SUM(amount_kobo), 0)::BIGINT AS total_kobo
FROM transfers
WHERE sender_user_id = $1
  AND status IN ('ACCEPTED','PROCESSING','SETTLED')
  AND created_at >= date_trunc('day', now() AT TIME ZONE 'Africa/Lagos')
`

// SumSenderTransfersToday totals kobo spent today (Africa/Lagos) on
// in-flight or settled transfers for one sender. Drives the high-daily-
// share fraud rule.
func (q *Queries) SumSenderTransfersToday(ctx context.Context, senderUserID string) (int64, error) {
	row := q.db.QueryRow(ctx, sumSenderTransfersToday, senderUserID)
	var total_kobo int64
	err := row.Scan(&total_kobo)
	return total_kobo, err
}

const updateTransferStatus = `-- name: UpdateTransferStatus :exec
UPDATE transfers
SET status = $2,
    failure_reason = $3,
    settled_at = $4
WHERE id = $1
`

type UpdateTransferStatusParams struct {
	ID            string             `json:"id"`
	Status        string             `json:"status"`
	FailureReason *string            `json:"failure_reason"`
	SettledAt     pgtype.Timestamptz `json:"settled_at"`
}

func (q *Queries) UpdateTransferStatus(ctx context.Context, arg UpdateTransferStatusParams) error {
	_, err := q.db.Exec(ctx, updateTransferStatus,
		arg.ID,
		arg.Status,
		arg.FailureReason,
		arg.SettledAt,
	)
	return err
}
