// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkAccountNumberExists = `-- name: CheckAccountNumberExists :one
SELECT account_number FROM users WHERE account_number = $1
`

// CheckAccountNumberExists powers /v1/accounts/resolve — returns the
// account_number if the row exists so the caller can confirm a
// receiver before committing to a transfer.
func (q *Queries) CheckAccountNumberExists(ctx context.Context, accountNumber string) (string, error) {
	row := q.db.QueryRow(ctx, checkAccountNumberExists, accountNumber)
	var account_number string
	err := row.Scan(&account_number)
	return account_number, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)::BIGINT AS total FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countUsersByPhone = `-- name: CountUsersByPhone :one
SELECT COUNT(*)::BIGINT AS total FROM users
WHERE lower(phone) LIKE $1 OR lower(id) LIKE $1
`

func (q *Queries) CountUsersByPhone(ctx context.Context, phone string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByPhone, phone)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (id, phone, account_number, bvn, kyc_tier, device_attestation_id,
                   realm_key_version, first_name, last_name, email, password_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, phone, account_number, bvn, kyc_tier, device_attestation_id, realm_key_version, first_name, last_name, email, password_hash, email_verified, created_at, updated_at
`

type CreateUserParams struct {
	ID                  string  `json:"id"`
	Phone               string  `json:"phone"`
	AccountNumber       string  `json:"account_number"`
	Bvn                 *string `json:"bvn"`
	KycTier             string  `json:"kyc_tier"`
	DeviceAttestationID *string `json:"device_attestation_id"`
	RealmKeyVersion     int32   `json:"realm_key_version"`
	FirstName           string  `json:"first_name"`
	LastName            string  `json:"last_name"`
	Email               string  `json:"email"`
	PasswordHash        string  `json:"password_hash"`
}

// End-user CRUD and narrow projections. Each fetch variant returns
// exactly the columns its caller renders — SELECT * is reserved for the
// generic GetUser path. Narrow projections keep the row cache hot on
// the latency-sensitive auth + transfer-accept flows.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Phone,
		arg.AccountNumber,
		arg.Bvn,
		arg.KycTier,
		arg.DeviceAttestationID,
		arg.RealmKeyVersion,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.AccountNumber,
		&i.Bvn,
		&i.KycTier,
		&i.DeviceAttestationID,
		&i.RealmKeyVersion,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserWithAccountNumber = `-- name: CreateUserWithAccountNumber :one
INSERT INTO users (id, phone, account_number, kyc_tier, realm_key_version,
                   first_name, last_name, email, password_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, phone, account_number, kyc_tier, realm_key_version,
          first_name, last_name, email, email_verified,
          created_at, updated_at
`

type CreateUserWithAccountNumberParams struct {
	ID              string `json:"id"`
	Phone           string `json:"phone"`
	AccountNumber   string `json:"account_number"`
	KycTier         string `json:"kyc_tier"`
	RealmKeyVersion int32  `json:"realm_key_version"`
	FirstName       string `json:"first_name"`
	LastName        string `json:"last_name"`
	Email           string `json:"email"`
	PasswordHash    string `json:"password_hash"`
}

type CreateUserWithAccountNumberRow struct {
	ID              string             `json:"id"`
	Phone           string             `json:"phone"`
	AccountNumber   string             `json:"account_number"`
	KycTier         string             `json:"kyc_tier"`
	RealmKeyVersion int32              `json:"realm_key_version"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	Email           string             `json:"email"`
	EmailVerified   bool               `json:"email_verified"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// CreateUserWithAccountNumber is the signup-path insert. Stores the
// minimum identity + credential set (names, email, password_hash)
// alongside phone + account_number. kyc_tier is caller-supplied so
// tests can seed arbitrary tiers without hitting the promotion path.
func (q *Queries) CreateUserWithAccountNumber(ctx context.Context, arg CreateUserWithAccountNumberParams) (CreateUserWithAccountNumberRow, error) {
	row := q.db.QueryRow(ctx, createUserWithAccountNumber,
		arg.ID,
		arg.Phone,
		arg.AccountNumber,
		arg.KycTier,
		arg.RealmKeyVersion,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PasswordHash,
	)
	var i CreateUserWithAccountNumberRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.AccountNumber,
		&i.KycTier,
		&i.RealmKeyVersion,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMeProjection = `-- name: GetMeProjection :one
SELECT id, phone, account_number, kyc_tier, first_name, last_name, email, email_verified
FROM users WHERE id = $1
`

type GetMeProjectionRow struct {
	ID            string `json:"id"`
	Phone         string `json:"phone"`
	AccountNumber string `json:"account_number"`
	KycTier       string `json:"kyc_tier"`
	FirstName     string `json:"first_name"`
	LastName      string `json:"last_name"`
	Email         string `json:"email"`
	EmailVerified bool   `json:"email_verified"`
}

// GetMeProjection is the /v1/me handler's narrow fetch — exactly the
// profile fields the client renders.
func (q *Queries) GetMeProjection(ctx context.Context, id string) (GetMeProjectionRow, error) {
	row := q.db.QueryRow(ctx, getMeProjection, id)
	var i GetMeProjectionRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.AccountNumber,
		&i.KycTier,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.EmailVerified,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, phone, account_number, bvn, kyc_tier, device_attestation_id, realm_key_version, first_name, last_name, email, password_hash, email_verified, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.AccountNumber,
		&i.Bvn,
		&i.KycTier,
		&i.DeviceAttestationID,
		&i.RealmKeyVersion,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAccountAgeHours = `-- name: GetUserAccountAgeHours :one
SELECT (EXTRACT(EPOCH FROM now() - created_at) / 3600)::float8 AS age_hours
FROM users WHERE id = $1
`

// GetUserAccountAgeHours returns the sender's account age in hours
// (EXTRACT yields a double; sqlc maps it to float64). Drives the
// fraud scorer's new-account rule.
func (q *Queries) GetUserAccountAgeHours(ctx context.Context, id string) (float64, error) {
	row := q.db.QueryRow(ctx, getUserAccountAgeHours, id)
	var age_hours float64
	err := row.Scan(&age_hours)
	return age_hours, err
}

const getUserAccountNumber = `-- name: GetUserAccountNumber :one
SELECT account_number FROM users WHERE id = $1
`

// GetUserAccountNumber fetches just the 10-digit account number.
// Used by the refresh flow which already has a user id and needs the
// account number to mint the next access token.
func (q *Queries) GetUserAccountNumber(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getUserAccountNumber, id)
	var account_number string
	err := row.Scan(&account_number)
	return account_number, err
}

const getUserByAccountNumber = `-- name: GetUserByAccountNumber :one
SELECT id, phone, account_number, kyc_tier, realm_key_version, created_at, updated_at
FROM users WHERE account_number = $1
`

type GetUserByAccountNumberRow struct {
	ID              string             `json:"id"`
	Phone           string             `json:"phone"`
	AccountNumber   string             `json:"account_number"`
	KycTier         string             `json:"kyc_tier"`
	RealmKeyVersion int32              `json:"realm_key_version"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByAccountNumber(ctx context.Context, accountNumber string) (GetUserByAccountNumberRow, error) {
	row := q.db.QueryRow(ctx, getUserByAccountNumber, accountNumber)
	var i GetUserByAccountNumberRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.AccountNumber,
		&i.KycTier,
		&i.RealmKeyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, phone, account_number, bvn, kyc_tier, device_attestation_id, realm_key_version, first_name, last_name, email, password_hash, email_verified, created_at, updated_at FROM users WHERE lower(email) = lower($1)
`

// GetUserByEmail locates a user by registered email (case-insensitive).
// Used by the password-reset flow to issue a reset code.
func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.AccountNumber,
		&i.Bvn,
		&i.KycTier,
		&i.DeviceAttestationID,
		&i.RealmKeyVersion,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone, account_number, bvn, kyc_tier, device_attestation_id, realm_key_version, first_name, last_name, email, password_hash, email_verified, created_at, updated_at FROM users WHERE phone = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.AccountNumber,
		&i.Bvn,
		&i.KycTier,
		&i.DeviceAttestationID,
		&i.RealmKeyVersion,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserDisplayNamesByIDs = `-- name: GetUserDisplayNamesByIDs :many
SELECT id, first_name, last_name
FROM users
WHERE id = ANY($1::text[])
`

type GetUserDisplayNamesByIDsRow struct {
	ID        string `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}

// GetUserDisplayNamesByIDs batches the display-name join used by
// activity feeds so the UI shows "Jane Doe" rather than a raw user id.
// Returns one row per matching id; callers tolerate arbitrary
// ordering and hash rows by id.
func (q *Queries) GetUserDisplayNamesByIDs(ctx context.Context, dollar_1 []string) ([]GetUserDisplayNamesByIDsRow, error) {
	rows, err := q.db.Query(ctx, getUserDisplayNamesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserDisplayNamesByIDsRow{}
	for rows.Next() {
		var i GetUserDisplayNamesByIDsRow
		if err := rows.Scan(&i.ID, &i.FirstName, &i.LastName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserIDAndAccountNumberByPhone = `-- name: GetUserIDAndAccountNumberByPhone :one
SELECT id, account_number FROM users WHERE phone = $1
`

type GetUserIDAndAccountNumberByPhoneRow struct {
	ID            string `json:"id"`
	AccountNumber string `json:"account_number"`
}

// GetUserIDAndAccountNumberByPhone is the login-path lookup: normalise
// the phone, then fetch id + account_number for session creation.
func (q *Queries) GetUserIDAndAccountNumberByPhone(ctx context.Context, phone string) (GetUserIDAndAccountNumberByPhoneRow, error) {
	row := q.db.QueryRow(ctx, getUserIDAndAccountNumberByPhone, phone)
	var i GetUserIDAndAccountNumberByPhoneRow
	err := row.Scan(&i.ID, &i.AccountNumber)
	return i, err
}

const getUserIDByAccountNumber = `-- name: GetUserIDByAccountNumber :one
SELECT id FROM users WHERE account_number = $1
`

// GetUserIDByAccountNumber is the receiver-resolution step of the
// transfer-accept flow.
func (q *Queries) GetUserIDByAccountNumber(ctx context.Context, accountNumber string) (string, error) {
	row := q.db.QueryRow(ctx, getUserIDByAccountNumber, accountNumber)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getUserKYCTier = `-- name: GetUserKYCTier :one
SELECT kyc_tier FROM users WHERE id = $1
`

// GetUserKYCTier is the narrow tier lookup inside the transfer-accept
// tx. Kept separate from GetUser so hot-path reads skip unused columns.
func (q *Queries) GetUserKYCTier(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getUserKYCTier, id)
	var kyc_tier string
	err := row.Scan(&kyc_tier)
	return kyc_tier, err
}

const getUserLoginByPhone = `-- name: GetUserLoginByPhone :one
SELECT id, account_number, password_hash FROM users WHERE phone = $1
`

type GetUserLoginByPhoneRow struct {
	ID            string `json:"id"`
	AccountNumber string `json:"account_number"`
	PasswordHash  string `json:"password_hash"`
}

// GetUserLoginByPhone returns the password-login projection: id,
// account_number, password_hash. Bundled so the login hot path
// bcrypt-checks in a single round trip.
func (q *Queries) GetUserLoginByPhone(ctx context.Context, phone string) (GetUserLoginByPhoneRow, error) {
	row := q.db.QueryRow(ctx, getUserLoginByPhone, phone)
	var i GetUserLoginByPhoneRow
	err := row.Scan(&i.ID, &i.AccountNumber, &i.PasswordHash)
	return i, err
}

const getUserNameByAccountNumber = `-- name: GetUserNameByAccountNumber :one
SELECT id, first_name, last_name, account_number
FROM users
WHERE account_number = $1 AND kyc_tier <> 'SYSTEM'
`

type GetUserNameByAccountNumberRow struct {
	ID            string `json:"id"`
	FirstName     string `json:"first_name"`
	LastName      string `json:"last_name"`
	AccountNumber string `json:"account_number"`
}

// GetUserNameByAccountNumber powers the demo-mint name-enquiry step:
// given a 10-digit account number, return the holder's names so the
// frontend can confirm the recipient before funding. System accounts
// (kyc_tier='SYSTEM') are excluded so treasury owners never appear as
// valid recipients.
func (q *Queries) GetUserNameByAccountNumber(ctx context.Context, accountNumber string) (GetUserNameByAccountNumberRow, error) {
	row := q.db.QueryRow(ctx, getUserNameByAccountNumber, accountNumber)
	var i GetUserNameByAccountNumberRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.AccountNumber,
	)
	return i, err
}

const getUserPhoneAndTier = `-- name: GetUserPhoneAndTier :one
SELECT phone, kyc_tier FROM users WHERE id = $1
`

type GetUserPhoneAndTierRow struct {
	Phone   string `json:"phone"`
	KycTier string `json:"kyc_tier"`
}

// GetUserPhoneAndTier returns the fields the KYC flow needs to decide
// whether to promote: the phone (to compute the expected mock id) and
// the current tier (so only strictly-higher promotions apply).
func (q *Queries) GetUserPhoneAndTier(ctx context.Context, id string) (GetUserPhoneAndTierRow, error) {
	row := q.db.QueryRow(ctx, getUserPhoneAndTier, id)
	var i GetUserPhoneAndTierRow
	err := row.Scan(&i.Phone, &i.KycTier)
	return i, err
}

const getUserPhoneByID = `-- name: GetUserPhoneByID :one
SELECT phone FROM users WHERE id = $1
`

// GetUserPhoneByID powers KYCHint; narrow projection keeps it
// independent from GetUser even when the full row shape changes.
func (q *Queries) GetUserPhoneByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getUserPhoneByID, id)
	var phone string
	err := row.Scan(&phone)
	return phone, err
}

const listUsersForAdmin = `-- name: ListUsersForAdmin :many
SELECT u.id,
       u.phone,
       u.kyc_tier,
       u.realm_key_version,
       u.created_at,
       COALESCE(am.balance_kobo, 0)::BIGINT AS main_balance_kobo,
       COALESCE(al.balance_kobo, 0)::BIGINT AS lien_balance_kobo,
       (SELECT MAX(last_seen_at) FROM devices d WHERE d.user_id = u.id)::timestamptz AS last_seen_at
FROM users u
LEFT JOIN accounts am ON am.user_id = u.id AND am.kind = 'main'
LEFT JOIN accounts al ON al.user_id = u.id AND al.kind = 'lien_holding'
ORDER BY u.created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersForAdminParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersForAdminRow struct {
	ID              string             `json:"id"`
	Phone           string             `json:"phone"`
	KycTier         string             `json:"kyc_tier"`
	RealmKeyVersion int32              `json:"realm_key_version"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	MainBalanceKobo int64              `json:"main_balance_kobo"`
	LienBalanceKobo int64              `json:"lien_balance_kobo"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
}

// ListUsersForAdmin returns one admin-projection page, newest first.
// Shares its row shape with SearchUsersForAdminByPhone so scan adapters
// can be reused across the listing and search paths.
func (q *Queries) ListUsersForAdmin(ctx context.Context, arg ListUsersForAdminParams) ([]ListUsersForAdminRow, error) {
	rows, err := q.db.Query(ctx, listUsersForAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersForAdminRow{}
	for rows.Next() {
		var i ListUsersForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Phone,
			&i.KycTier,
			&i.RealmKeyVersion,
			&i.CreatedAt,
			&i.MainBalanceKobo,
			&i.LienBalanceKobo,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users SET email_verified = true, updated_at = now()
WHERE id = $1
`

// MarkEmailVerified flips email_verified to true. Idempotent.
func (q *Queries) MarkEmailVerified(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markEmailVerified, id)
	return err
}

const promoteUserToTier = `-- name: PromoteUserToTier :exec
UPDATE users
SET kyc_tier = $2, updated_at = now()
WHERE id = $1
  AND (
    CASE kyc_tier
      WHEN 'TIER_0' THEN 0
      WHEN 'TIER_1' THEN 1
      WHEN 'TIER_2' THEN 2
      WHEN 'TIER_3' THEN 3
      ELSE 0
    END
  ) < (
    CASE $2::text
      WHEN 'TIER_0' THEN 0
      WHEN 'TIER_1' THEN 1
      WHEN 'TIER_2' THEN 2
      WHEN 'TIER_3' THEN 3
      ELSE 0
    END
  )
`

type PromoteUserToTierParams struct {
	ID      string `json:"id"`
	KycTier string `json:"kyc_tier"`
}

// PromoteUserToTier moves the user to a new KYC tier, but only if the
// target tier is strictly higher in the TIER_0..TIER_3 ordering. The
// CASE guard makes the promotion idempotent and prevents a lower tier
// from clobbering an already-granted higher one.
func (q *Queries) PromoteUserToTier(ctx context.Context, arg PromoteUserToTierParams) error {
	_, err := q.db.Exec(ctx, promoteUserToTier, arg.ID, arg.KycTier)
	return err
}

const searchUsersForAdminByPhone = `-- name: SearchUsersForAdminByPhone :many
SELECT u.id,
       u.phone,
       u.kyc_tier,
       u.realm_key_version,
       u.created_at,
       COALESCE(am.balance_kobo, 0)::BIGINT AS main_balance_kobo,
       COALESCE(al.balance_kobo, 0)::BIGINT AS lien_balance_kobo,
       (SELECT MAX(last_seen_at) FROM devices d WHERE d.user_id = u.id)::timestamptz AS last_seen_at
FROM users u
LEFT JOIN accounts am ON am.user_id = u.id AND am.kind = 'main'
LEFT JOIN accounts al ON al.user_id = u.id AND al.kind = 'lien_holding'
WHERE lower(u.phone) LIKE $1 OR lower(u.id) LIKE $1
ORDER BY u.created_at DESC
LIMIT $2 OFFSET $3
`

type SearchUsersForAdminByPhoneParams struct {
	Phone  string `json:"phone"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type SearchUsersForAdminByPhoneRow struct {
	ID              string             `json:"id"`
	Phone           string             `json:"phone"`
	KycTier         string             `json:"kyc_tier"`
	RealmKeyVersion int32              `json:"realm_key_version"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	MainBalanceKobo int64              `json:"main_balance_kobo"`
	LienBalanceKobo int64              `json:"lien_balance_kobo"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
}

// SearchUsersForAdminByPhone matches phone or id against a lowercase
// LIKE pattern (caller passes '%' + lower(q) + '%'). Column list
// matches ListUsersForAdmin so the admin service layer shares scan
// adapters.
func (q *Queries) SearchUsersForAdminByPhone(ctx context.Context, arg SearchUsersForAdminByPhoneParams) ([]SearchUsersForAdminByPhoneRow, error) {
	rows, err := q.db.Query(ctx, searchUsersForAdminByPhone, arg.Phone, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersForAdminByPhoneRow{}
	for rows.Next() {
		var i SearchUsersForAdminByPhoneRow
		if err := rows.Scan(
			&i.ID,
			&i.Phone,
			&i.KycTier,
			&i.RealmKeyVersion,
			&i.CreatedAt,
			&i.MainBalanceKobo,
			&i.LienBalanceKobo,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserKYC = `-- name: UpdateUserKYC :exec
UPDATE users SET kyc_tier = $2, updated_at = now() WHERE id = $1
`

type UpdateUserKYCParams struct {
	ID      string `json:"id"`
	KycTier string `json:"kyc_tier"`
}

func (q *Queries) UpdateUserKYC(ctx context.Context, arg UpdateUserKYCParams) error {
	_, err := q.db.Exec(ctx, updateUserKYC, arg.ID, arg.KycTier)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = now()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           string `json:"id"`
	PasswordHash string `json:"password_hash"`
}

// UpdateUserPassword replaces the bcrypt password hash. Used by the
// forgot-password reset flow.
func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
