// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_pins.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpPINAttempts = `-- name: BumpPINAttempts :exec
UPDATE user_pins
SET attempts   = $2,
    updated_at = now()
WHERE user_id = $1
`

type BumpPINAttemptsParams struct {
	UserID   string `json:"user_id"`
	Attempts int32  `json:"attempts"`
}

// BumpPINAttempts records a mismatch below the lockout threshold.
func (q *Queries) BumpPINAttempts(ctx context.Context, arg BumpPINAttemptsParams) error {
	_, err := q.db.Exec(ctx, bumpPINAttempts, arg.UserID, arg.Attempts)
	return err
}

const clearUserPINAttempts = `-- name: ClearUserPINAttempts :exec
UPDATE user_pins
SET attempts   = 0,
    locked_at  = NULL,
    updated_at = now()
WHERE user_id = $1 AND (attempts <> 0 OR locked_at IS NOT NULL)
`

// ClearUserPINAttempts zeros the counter on a successful verify. The
// guard in the WHERE clause skips the write when the row is already
// clean, avoiding an unnecessary heap touch on every login.
func (q *Queries) ClearUserPINAttempts(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, clearUserPINAttempts, userID)
	return err
}

const getUserPINState = `-- name: GetUserPINState :one
SELECT pin_hash, attempts, locked_at
FROM user_pins
WHERE user_id = $1
`

type GetUserPINStateRow struct {
	PinHash  string             `json:"pin_hash"`
	Attempts int32              `json:"attempts"`
	LockedAt pgtype.Timestamptz `json:"locked_at"`
}

// GetUserPINState returns the VerifyPIN projection. No row means the
// user has not set a PIN yet; the service maps that to "pin_not_set".
func (q *Queries) GetUserPINState(ctx context.Context, userID string) (GetUserPINStateRow, error) {
	row := q.db.QueryRow(ctx, getUserPINState, userID)
	var i GetUserPINStateRow
	err := row.Scan(&i.PinHash, &i.Attempts, &i.LockedAt)
	return i, err
}

const lockUserPIN = `-- name: LockUserPIN :exec
UPDATE user_pins
SET attempts   = $2,
    locked_at  = now(),
    updated_at = now()
WHERE user_id = $1
`

type LockUserPINParams struct {
	UserID   string `json:"user_id"`
	Attempts int32  `json:"attempts"`
}

// LockUserPIN records the mismatch that crosses the lockout threshold
// and latches locked_at.
func (q *Queries) LockUserPIN(ctx context.Context, arg LockUserPINParams) error {
	_, err := q.db.Exec(ctx, lockUserPIN, arg.UserID, arg.Attempts)
	return err
}

const setUserPIN = `-- name: SetUserPIN :execrows

INSERT INTO user_pins (user_id, pin_hash, attempts, locked_at, updated_at)
VALUES ($1, $2, 0, NULL, now())
ON CONFLICT (user_id) DO UPDATE
SET pin_hash   = EXCLUDED.pin_hash,
    attempts   = 0,
    locked_at  = NULL,
    updated_at = now()
`

type SetUserPINParams struct {
	UserID  string `json:"user_id"`
	PinHash string `json:"pin_hash"`
}

// Per-user transaction PIN. user_pins is 1:1 with users; the row is
// created on first PIN-set and refreshed via UPSERT on subsequent
// resets.
// SetUserPIN stores a freshly-hashed PIN and clears any prior lockout.
// Returns rows-affected (always 1 after the upsert) so the caller can
// confirm the write landed.
func (q *Queries) SetUserPIN(ctx context.Context, arg SetUserPINParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserPIN, arg.UserID, arg.PinHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
