// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_auth.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeOTPChallenge = `-- name: ConsumeOTPChallenge :exec
UPDATE otp_challenges SET consumed_at = now()
WHERE identifier = $1 AND purpose = $2
`

type ConsumeOTPChallengeParams struct {
	Identifier string `json:"identifier"`
	Purpose    string `json:"purpose"`
}

func (q *Queries) ConsumeOTPChallenge(ctx context.Context, arg ConsumeOTPChallengeParams) error {
	_, err := q.db.Exec(ctx, consumeOTPChallenge, arg.Identifier, arg.Purpose)
	return err
}

const createUserSession = `-- name: CreateUserSession :exec
INSERT INTO user_sessions (id, user_id, refresh_hash, user_agent, ip, device_id, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateUserSessionParams struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	RefreshHash string             `json:"refresh_hash"`
	UserAgent   string             `json:"user_agent"`
	Ip          string             `json:"ip"`
	DeviceID    *string            `json:"device_id"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) error {
	_, err := q.db.Exec(ctx, createUserSession,
		arg.ID,
		arg.UserID,
		arg.RefreshHash,
		arg.UserAgent,
		arg.Ip,
		arg.DeviceID,
		arg.ExpiresAt,
	)
	return err
}

const createUserSessionRotation = `-- name: CreateUserSessionRotation :exec
INSERT INTO user_sessions (id, user_id, refresh_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateUserSessionRotationParams struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	RefreshHash string             `json:"refresh_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// CreateUserSessionRotation records the replacement refresh row after
// a successful /auth/refresh. user_agent/ip/device_id are not
// re-captured on rotation — the DB-level defaults (” / NULL) apply.
func (q *Queries) CreateUserSessionRotation(ctx context.Context, arg CreateUserSessionRotationParams) error {
	_, err := q.db.Exec(ctx, createUserSessionRotation,
		arg.ID,
		arg.UserID,
		arg.RefreshHash,
		arg.ExpiresAt,
	)
	return err
}

const getOTPChallenge = `-- name: GetOTPChallenge :one
SELECT identifier, code_hash, purpose, attempts, created_at, expires_at, consumed_at
FROM otp_challenges
WHERE identifier = $1 AND purpose = $2
`

type GetOTPChallengeParams struct {
	Identifier string `json:"identifier"`
	Purpose    string `json:"purpose"`
}

func (q *Queries) GetOTPChallenge(ctx context.Context, arg GetOTPChallengeParams) (OtpChallenge, error) {
	row := q.db.QueryRow(ctx, getOTPChallenge, arg.Identifier, arg.Purpose)
	var i OtpChallenge
	err := row.Scan(
		&i.Identifier,
		&i.CodeHash,
		&i.Purpose,
		&i.Attempts,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const getUserSessionByRefreshHash = `-- name: GetUserSessionByRefreshHash :one
SELECT s.id, s.user_id, s.expires_at, s.revoked_at
FROM user_sessions s
WHERE s.refresh_hash = $1
`

type GetUserSessionByRefreshHashRow struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) GetUserSessionByRefreshHash(ctx context.Context, refreshHash string) (GetUserSessionByRefreshHashRow, error) {
	row := q.db.QueryRow(ctx, getUserSessionByRefreshHash, refreshHash)
	var i GetUserSessionByRefreshHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserSessionOwner = `-- name: GetUserSessionOwner :one
SELECT user_id, revoked_at FROM user_sessions WHERE id = $1
`

type GetUserSessionOwnerRow struct {
	UserID    string             `json:"user_id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

// GetUserSessionOwner returns owner + revocation state for one
// session id. RevokeSession uses this to enforce per-user ownership
// before the revocation write.
func (q *Queries) GetUserSessionOwner(ctx context.Context, id string) (GetUserSessionOwnerRow, error) {
	row := q.db.QueryRow(ctx, getUserSessionOwner, id)
	var i GetUserSessionOwnerRow
	err := row.Scan(&i.UserID, &i.RevokedAt)
	return i, err
}

const incrementOTPAttempts = `-- name: IncrementOTPAttempts :exec
UPDATE otp_challenges SET attempts = attempts + 1
WHERE identifier = $1 AND purpose = $2
`

type IncrementOTPAttemptsParams struct {
	Identifier string `json:"identifier"`
	Purpose    string `json:"purpose"`
}

func (q *Queries) IncrementOTPAttempts(ctx context.Context, arg IncrementOTPAttemptsParams) error {
	_, err := q.db.Exec(ctx, incrementOTPAttempts, arg.Identifier, arg.Purpose)
	return err
}

const listActiveUserSessions = `-- name: ListActiveUserSessions :many
SELECT id, user_agent, ip, device_id, created_at, expires_at
FROM user_sessions
WHERE user_id = $1
  AND revoked_at IS NULL
  AND expires_at > now()
ORDER BY created_at DESC
`

type ListActiveUserSessionsRow struct {
	ID        string             `json:"id"`
	UserAgent string             `json:"user_agent"`
	Ip        string             `json:"ip"`
	DeviceID  *string            `json:"device_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// ListActiveUserSessions returns every non-revoked, non-expired
// refresh session for userID. Powers the end-user devices/sessions
// screen.
func (q *Queries) ListActiveUserSessions(ctx context.Context, userID string) ([]ListActiveUserSessionsRow, error) {
	rows, err := q.db.Query(ctx, listActiveUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveUserSessionsRow{}
	for rows.Next() {
		var i ListActiveUserSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserAgent,
			&i.Ip,
			&i.DeviceID,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeOtherUserSessions = `-- name: RevokeOtherUserSessions :execrows
UPDATE user_sessions
SET revoked_at = now()
WHERE user_id = $1
  AND revoked_at IS NULL
  AND id <> $2
`

type RevokeOtherUserSessionsParams struct {
	UserID string `json:"user_id"`
	ID     string `json:"id"`
}

// RevokeOtherUserSessions revokes every active session for userID
// except the one identified by $2. Pass ” in $2 to revoke all
// sessions (the "sign me out everywhere" flow).
func (q *Queries) RevokeOtherUserSessions(ctx context.Context, arg RevokeOtherUserSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeOtherUserSessions, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserSessionByHash = `-- name: RevokeUserSessionByHash :exec
UPDATE user_sessions SET revoked_at = now()
WHERE refresh_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeUserSessionByHash(ctx context.Context, refreshHash string) error {
	_, err := q.db.Exec(ctx, revokeUserSessionByHash, refreshHash)
	return err
}

const revokeUserSessionByID = `-- name: RevokeUserSessionByID :exec
UPDATE user_sessions SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeUserSessionByID(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, revokeUserSessionByID, id)
	return err
}

const upsertOTPChallenge = `-- name: UpsertOTPChallenge :exec

INSERT INTO otp_challenges (identifier, purpose, code_hash, expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (identifier, purpose) DO UPDATE
SET code_hash = EXCLUDED.code_hash,
    attempts = 0,
    created_at = now(),
    expires_at = EXCLUDED.expires_at,
    consumed_at = NULL
`

type UpsertOTPChallengeParams struct {
	Identifier string             `json:"identifier"`
	Purpose    string             `json:"purpose"`
	CodeHash   string             `json:"code_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

// End-user auth storage: OTP challenges driving signup-email-verify
// and password-reset, plus refresh-session CRUD for login/rotate/
// logout. admin auth queries live in admin.sql / admin_sessions.sql
// because admin_users is a separate identity surface.
// UpsertOTPChallenge stores or replaces the single active challenge
// per (identifier, purpose). A re-send resets attempts + expires_at
// and clears consumed_at so the fresh code is usable.
func (q *Queries) UpsertOTPChallenge(ctx context.Context, arg UpsertOTPChallengeParams) error {
	_, err := q.db.Exec(ctx, upsertOTPChallenge,
		arg.Identifier,
		arg.Purpose,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	return err
}
