-- PaymentRequest binding. Every payment_token now references a receiver-
-- issued PaymentRequest. We persist the fields the server re-checks
-- so a later audit can reproduce the contract without the full PR blob
-- (the blob itself lives on the submitter device's SQLite queue).
--
--   * session_nonce (16 bytes) — random per-request nonce generated by
--     the receiver's device. Single-use per receiver: the unique index
--     below + Phase 4a's (payer, sequence) dedupe together close the
--     replay window.
--
--   * request_hash (32 bytes) — sha256(canonical(PaymentRequest)). The
--     server recomputes this from the submitted PR blob to detect
--     tampering.
--
--   * request_amount_kobo — mirrors PR.amount and is used to check the
--     payer paid exactly what was asked. 0 means "unbound": the P2P
--     fallback where the payer entered the amount themselves.

ALTER TABLE payment_tokens
    ADD COLUMN session_nonce        BYTEA  NOT NULL,
    ADD COLUMN request_hash         BYTEA  NOT NULL,
    ADD COLUMN request_amount_kobo  BIGINT NOT NULL;

CREATE UNIQUE INDEX idx_payment_session_nonce
    ON payment_tokens (payee_user_id, session_nonce);
